(function(){var g={};
(function(window){var k,aa=this;function m(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function p(a,b){function c(){}c.prototype=b.prototype;a.pb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.mb=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};/*

 Copyright 2015 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function ba(){};function ca(a){var b=console[a];b?b.bind||(console[a]=function(){b.apply(console,arguments)}):console[a]=function(){}}ca("error");ca("warn");ca("info");ca("log");ca("debug");function da(a){ea[a]={fa:fa(),end:NaN}}function ga(a){if(a=ea[a])a.end=fa()}function ha(a){return(a=ea[a])&&a.end?a.end-a.fa:NaN}var fa=window.performance&&window.performance.now?window.performance.now.bind(window.performance):Date.now,ea={};function ia(a,b,c){this.id=a;this.bandwidth=b||0;this.lang=c||"unknown";this.active=!1}m("shaka.player.AudioTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0});function ja(){this.minBandwidth=this.maxBandwidth=this.maxWidth=this.minHeight=this.maxHeight=null}ja.prototype.clone=function(){var a=new ja;a.maxHeight=this.maxHeight;a.minHeight=this.minHeight;a.maxWidth=this.maxWidth;a.maxBandwidth=this.maxBandwidth;a.minBandwidth=this.minBandwidth;return a};function q(){this.fontSize="100%";this.fontColor=ka;this.fontOpacity=la;this.backgroundColor=ma;this.backgroundOpacity=la;this.fontEdge=na}m("shaka.player.TextStyle",q);q.prototype.a=function(){var a=window.localStorage.getItem("ShakaPlayerTextStyle");if(a){var b;try{b=JSON.parse(a)}catch(c){return}if(b&&"object"==typeof b){var a=b,d;for(d in a)d in this&&(this[d]=a[d])}}};q.prototype.load=q.prototype.a;q.prototype.b=function(){window.localStorage.setItem("ShakaPlayerTextStyle",JSON.stringify(this))};
q.prototype.store=q.prototype.b;function oa(a){var b=[];b.push("font-size: "+a.fontSize);b.push("color: "+pa(a.fontColor,a.fontOpacity));b.push("background-color: "+pa(a.backgroundColor,a.backgroundOpacity));for(var c=[],d=0;d<a.fontEdge.length;++d){var e=a.fontEdge[d].slice(3,6);c.push(pa(a.fontEdge[d].slice(0,3),a.fontOpacity)+" "+e.join("px ")+"px")}b.push("text-shadow: "+c.join(","));return b.join("; ")}function pa(a,b){return"rgba("+a.concat(b).join(",")+")"}var ka=[255,255,255],ma=[0,0,0];
q.StandardColors={WHITE:ka,BLACK:ma,RED:[255,0,0],GREEN:[0,255,0],BLUE:[0,0,255],YELLOW:[255,255,0],MAGENTA:[255,0,255],CYAN:[0,255,255]};var la=1;q.StandardOpacities={OPAQUE:la,SEMI_HIGH:.75,SEMI_LOW:.25,TRANSPARENT:0};var na=[];
q.EdgeStyles={NONE:na,RAISED:[[34,34,34,1,1,0],[34,34,34,2,2,0],[34,34,34,3,3,0]],DEPRESSED:[[204,204,204,1,1,0],[204,204,204,0,1,0],[34,34,34,-1,-1,0],[34,34,34,0,-1,0]],UNIFORM:[[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4]],DROP:[[34,34,34,2,2,3],[34,34,34,2,2,4],[34,34,34,2,2,5]]};function qa(a,b){this.id=a;this.lang=b||"unknown";this.enabled=this.active=!1}m("shaka.player.TextTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:0});function ra(a,b,c,d){this.id=a;this.bandwidth=b||0;this.width=c||0;this.height=d||0;this.active=!1}function sa(a,b){var c=a.width*a.height,d=b.width*b.height;return c<d?-1:c>d?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0}m("shaka.player.VideoTrack.compare",sa);function ta(){var a="CustomEvent"in window;if(a)try{new CustomEvent("")}catch(b){a=!1}a||(window.CustomEvent=ua)}m("shaka.polyfill.CustomEvent.install",ta);function ua(a,b){var c=document.createEvent("CustomEvent"),d=b||{bubbles:!1,cancelable:!1,detail:null};c.initCustomEvent(a,!!d.bubbles,!!d.cancelable,d.detail);return c};function va(){var a=Element.prototype;a.requestFullscreen=a.requestFullscreen||a.mozRequestFullScreen||a.msRequestFullscreen||a.webkitRequestFullscreen;a=Document.prototype;a.exitFullscreen=a.exitFullscreen||a.mozCancelFullScreen||a.msExitFullscreen||a.webkitExitFullscreen;"fullscreenElement"in document||Object.defineProperty(document,"fullscreenElement",{get:function(){return document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement}});document.addEventListener("webkitfullscreenchange",
wa);document.addEventListener("webkitfullscreenerror",wa);document.addEventListener("mozfullscreenchange",wa);document.addEventListener("mozfullscreenerror",wa);document.addEventListener("MSFullscreenChange",wa);document.addEventListener("MSFullscreenError",wa)}m("shaka.polyfill.Fullscreen.install",va);function wa(a){var b=a.type.replace(/^(webkit|moz|MS)/,"").toLowerCase(),b=new Event(b,a);a.target.dispatchEvent(b)};function xa(){return Promise.reject(Error("The key system specified is not supported."))}function ya(a){return null==a?Promise.resolve():Promise.reject(Error("MediaKeys not supported."))}function za(){throw new TypeError("Illegal constructor.");}za.prototype.createSession=function(){};za.prototype.setServerCertificate=function(){};function Aa(){throw new TypeError("Illegal constructor.");}Aa.prototype.getConfiguration=function(){};Aa.prototype.createMediaKeys=function(){};function u(a){this.c=[];this.b=[];this.N=Ba;if(a)try{a(this.I.bind(this),this.a.bind(this))}catch(b){this.a(b)}}var Ba=0;function Ca(){window.Promise||(window.Promise=u,window.Promise.resolve=Da,window.Promise.reject=Ea,window.Promise.all=Fa,window.Promise.race=Ga,window.setImmediate?(Ha=function(a){return window.setImmediate(a)},Ia=function(a){return window.clearImmediate(a)}):(Ha=function(a){return window.setTimeout(a,0)},Ia=function(a){return window.clearTimeout(a)}))}
m("shaka.polyfill.Promise.install",Ca);function Da(a){var b=new u;b.I(a);return b}function Ea(a){var b=new u;b.a(a);return b}function Fa(a){function b(a,b,c){a.N==Ba&&(e[b]=c,d++,d==e.length&&a.I(e))}var c=new u;if(!a.length)return c.I([]),c;for(var d=0,e=Array(a.length),f=c.a.bind(c),g=0;g<a.length;++g)a[g]&&a[g].then?a[g].then(b.bind(null,c,g),f):b(c,g,a[g]);return c}function Ga(a){for(var b=new u,c=b.I.bind(b),d=b.a.bind(b),e=0;e<a.length;++e)a[e]&&a[e].then?a[e].then(c,d):c(a[e]);return b}
u.prototype.then=function(a,b){var c=new u;switch(this.N){case 1:Ja(this,c,a);break;case 2:Ja(this,c,b);break;case Ba:this.c.push({oa:c,la:a}),this.b.push({oa:c,la:b})}return c};u.prototype.then=u.prototype.then;u.prototype.catch=function(a){return this.then(void 0,a)};u.prototype["catch"]=u.prototype.catch;u.prototype.I=function(a){if(this.N==Ba){this.ja=a;this.N=1;for(a=0;a<this.c.length;++a)Ja(this,this.c[a].oa,this.c[a].la);this.c=[];this.b=[]}};
u.prototype.a=function(a){if(this.N==Ba){this.ja=a;this.N=2;for(a=0;a<this.b.length;++a)Ja(this,this.b[a].oa,this.b[a].la);this.c=[];this.b=[]}};function Ja(a,b,c){Ka.push(function(){if(c&&"function"==typeof c){try{var a=c(this.ja)}catch(e){b.a(e);return}a instanceof u?a==b?b.a(new TypeError("Chaining cycle detected")):a.then(b.I.bind(b),b.a.bind(b)):b.I(a)}else 1==this.N?b.I(this.ja):b.a(this.ja)}.bind(a));null==La&&(La=Ha(Ma))}
function Ma(){for(;Ka.length;){null!=La&&(Ia(La),La=null);var a=Ka;Ka=[];for(var b=0;b<a.length;++b)a[b]()}}function Ha(){return 0}function Ia(){}var La=null,Ka=[];function Na(){var a=HTMLVideoElement.prototype;!a.getVideoPlaybackQuality&&"webkitDroppedFrameCount"in a&&(a.getVideoPlaybackQuality=Oa)}m("shaka.polyfill.VideoPlaybackQuality.install",Na);function Oa(){return{droppedVideoFrames:this.webkitDroppedFrameCount,totalVideoFrames:this.webkitDecodedFrameCount,corruptedVideoFrames:0,creationTime:NaN,totalFrameDelay:0}};function Pa(a,b){for(var c=[],d=0;d<a.length;++d){for(var e=!1,f=0;f<c.length&&!(e=b?b(a[d],c[f]):a[d]===c[f]);++f);e||c.push(a[d])}return c};var Qa=0;function Ra(a){this.b=a;this.c=0==Sa;this.a=0}var Sa=1;function Ta(a){var b=a.b.getUint8(a.a);a.a+=1;return b}function v(a){var b=a.b.getUint32(a.a,a.c);a.a+=4;return b}function Ua(a){var b,c;a.c?(b=a.b.getUint32(a.a,!0),c=a.b.getUint32(a.a+4,!0)):(c=a.b.getUint32(a.a,!1),b=a.b.getUint32(a.a+4,!1));if(2097151<c)throw new RangeError("DataViewReader: Overflow reading 64-bit value.");a.a+=8;return c*Math.pow(2,32)+b}
function Va(a){if(a.a+16>a.b.byteLength)throw new RangeError("DataViewReader: Read past end of DataView.");var b=new Uint8Array(a.b.buffer,a.a,16);a.a+=16;return b}function w(a,b){if(a.a+b>a.b.byteLength)throw new RangeError("DataViewReader: Skip past end of DataView.");a.a+=b};var Wa={"output-restricted":"The required output protection is not available.","output-not-allowed":"The required output protection is not available.",expired:"The decryption key has expired.","internal-error":"The key system has encountered an unspecified error."};function Xa(a){this.c=Math.exp(Math.log(.5)/a);this.a=this.b=0}Xa.prototype.sample=function(a,b){var c=Math.pow(this.c,a);this.b=b*(1-c)+c*this.b;this.a+=a};function Ya(a){return a.b/(1-Math.pow(a.c,a.a))};function x(a){var b=new CustomEvent(a.type,{detail:a.detail,bubbles:!!a.bubbles}),c;for(c in a)c in b||(b[c]=a[c]);return b}function y(a){return new CustomEvent("error",{detail:a,bubbles:!0})};function Za(a,b){var c=window.hola_cdn&&window.hola_cdn.api;if(c&&c[a])return c[a].apply(c,Array.prototype.slice.call(arguments,1))};function $a(a,b,c){ab(b);ab(c);return c==b||a>=bb&&c==b.split("-")[0]||a>=cb&&c.split("-")[0]==b.split("-")[0]?!0:!1}var bb=1,cb=2;function ab(a){a=a.toLowerCase().split("-");var b=db[a[0]];b&&(a[0]=b);return a.join("-")}
var db={aar:"aa",abk:"ab",afr:"af",aka:"ak",alb:"sq",amh:"am",ara:"ar",arg:"an",arm:"hy",asm:"as",ava:"av",ave:"ae",aym:"ay",aze:"az",bak:"ba",bam:"bm",baq:"eu",bel:"be",ben:"bn",bih:"bh",bis:"bi",bod:"bo",bos:"bs",bre:"br",bul:"bg",bur:"my",cat:"ca",ces:"cs",cha:"ch",che:"ce",chi:"zh",chu:"cu",chv:"cv",cor:"kw",cos:"co",cre:"cr",cym:"cy",cze:"cs",dan:"da",deu:"de",div:"dv",dut:"nl",dzo:"dz",ell:"el",eng:"en",epo:"eo",est:"et",eus:"eu",ewe:"ee",fao:"fo",fas:"fa",fij:"fj",fin:"fi",fra:"fr",fre:"fr",
fry:"fy",ful:"ff",geo:"ka",ger:"de",gla:"gd",gle:"ga",glg:"gl",glv:"gv",gre:"el",grn:"gn",guj:"gu",hat:"ht",hau:"ha",heb:"he",her:"hz",hin:"hi",hmo:"ho",hrv:"hr",hun:"hu",hye:"hy",ibo:"ig",ice:"is",ido:"io",iii:"ii",iku:"iu",ile:"ie",ina:"ia",ind:"id",ipk:"ik",isl:"is",ita:"it",jav:"jv",jpn:"ja",kal:"kl",kan:"kn",kas:"ks",kat:"ka",kau:"kr",kaz:"kk",khm:"km",kik:"ki",kin:"rw",kir:"ky",kom:"kv",kon:"kg",kor:"ko",kua:"kj",kur:"ku",lao:"lo",lat:"la",lav:"lv",lim:"li",lin:"ln",lit:"lt",ltz:"lb",lub:"lu",
lug:"lg",mac:"mk",mah:"mh",mal:"ml",mao:"mi",mar:"mr",may:"ms",mkd:"mk",mlg:"mg",mlt:"mt",mon:"mn",mri:"mi",msa:"ms",mya:"my",nau:"na",nav:"nv",nbl:"nr",nde:"nd",ndo:"ng",nep:"ne",nld:"nl",nno:"nn",nob:"nb",nor:"no",nya:"ny",oci:"oc",oji:"oj",ori:"or",orm:"om",oss:"os",pan:"pa",per:"fa",pli:"pi",pol:"pl",por:"pt",pus:"ps",que:"qu",roh:"rm",ron:"ro",rum:"ro",run:"rn",rus:"ru",sag:"sg",san:"sa",sin:"si",slk:"sk",slo:"sk",slv:"sl",sme:"se",smo:"sm",sna:"sn",snd:"sd",som:"so",sot:"st",spa:"es",sqi:"sq",
srd:"sc",srp:"sr",ssw:"ss",sun:"su",swa:"sw",swe:"sv",tah:"ty",tam:"ta",tat:"tt",tel:"te",tgk:"tg",tgl:"tl",tha:"th",tib:"bo",tir:"ti",ton:"to",tsn:"tn",tso:"ts",tuk:"tk",tur:"tr",twi:"tw",uig:"ug",ukr:"uk",urd:"ur",uzb:"uz",ven:"ve",vie:"vi",vol:"vo",wel:"cy",wln:"wa",wol:"wo",xho:"xh",yid:"yi",yor:"yo",zha:"za",zho:"zh",zul:"zu"};function eb(a){return Object.keys(a).map(function(b){return a[b]})}function fb(a,b){return gb(a,b,"boolean")}function hb(a,b){var c=gb(a,b,"number");if(null==c)return null;if(isNaN(c)||c==Number.NEGATIVE_INFINITY||c==Number.POSITIVE_INFINITY)throw new RangeError("'"+b+"' must be finite.");if(0>c)throw new RangeError("'"+b+"' must be >= 0");return c}function z(a,b){return gb(a,b,"string")}
function gb(a,b,c){a=a[b];if(null==a)return null;if(typeof a!=c)throw new TypeError("'"+b+"' must be a "+c+".");return a}function A(a,b,c){a=a[b];if(null==a)return null;if(!(a instanceof c))throw new TypeError("'"+b+"' must be an instance of "+c.name+".");return a};function C(){this.a={}}C.prototype.push=function(a,b){this.a.hasOwnProperty(a)?this.a[a].push(b):this.a[a]=[b]};C.prototype.set=function(a,b){this.a[a]=b};C.prototype.get=function(a){return(a=this.a[a])?a.slice():null};function jb(a){var b=[],c;for(c in a.a)b.push.apply(b,a.a[c]);return b}function kb(a,b,c){if(a=a.a[b])for(b=0;b<a.length;++b)a[b]==c&&(a.splice(b,1),--b)}function lb(a){var b=[],c;for(c in a.a)b.push(c);return b};function D(){this.a=new C}D.prototype.destroy=function(){mb(this);this.a=null};function E(a,b,c,d){b=new nb(b,c,d);a.a.push(c,b)}D.prototype.aa=function(a,b){for(var c=this.a.get(b)||[],d=0;d<c.length;++d){var e=c[d];e.target==a&&(e.aa(),kb(this.a,b,e))}};function mb(a){for(var b=jb(a.a),c=0;c<b.length;++c)b[c].aa();a.a.a={}}function nb(a,b,c){this.target=a;this.type=b;this.a=c;this.target.addEventListener(b,c,!1)}
nb.prototype.aa=function(){this.target&&(this.target.removeEventListener(this.type,this.a,!1),this.a=this.target=null)};function F(a){this.ka=new C;this.u=a}m("shaka.util.FakeEventTarget",F);F.prototype.addEventListener=function(a,b,c){c||this.ka.push(a,b)};F.prototype.removeEventListener=function(a,b,c){c||kb(this.ka,a,b)};
F.prototype.dispatchEvent=function(a){a.hasOwnProperty("srcElement")||(delete a.srcElement,Object.defineProperty(a,"srcElement",{get:function(){return null}}));if(a.hasOwnProperty("target"))a.target=this;else{delete a.target;var b=this;Object.defineProperty(a,"target",{get:function(){return b},set:function(a){b=a}})}if(a.hasOwnProperty("currentTarget"))a.currentTarget=null;else{delete a.currentTarget;var c=null;Object.defineProperty(a,"currentTarget",{get:function(){return c},set:function(a){c=a}})}return ob(this,
a)};function ob(a,b){b.currentTarget=a;for(var c=a.ka.get(b.type)||[],d=0;d<c.length;++d){var e=c[d];try{e.handleEvent?e.handleEvent(b):e.call(a,b)}catch(f){}}a.u&&b.bubbles&&ob(a.u,b);return b.defaultPrevented};function G(){F.call(this,null);this.a=new Xa(3);this.c=new Xa(10);this.b=0}p(G,F);m("shaka.util.EWMABandwidthEstimator",G);G.prototype.sample=function(a,b){if(!(65536>b)){a=Math.max(a,50);var c=8E3*b/a,d=a/1E3;this.a.sample(d,c);this.c.sample(d,c);this.dispatchEvent(x({type:"bandwidth"}));this.b=Date.now()}};G.prototype.getBandwidth=function(){return.5>this.a.a?5E5:Math.min(Ya(this.a),Ya(this.c))};G.prototype.getDataAge=function(){return(Date.now()-this.b)/1E3};G.prototype.supportsCaching=function(){return!1};function H(){var a,b,c=new Promise(function(c,e){a=c;b=e});c.resolve=a;c.reject=b;c.destroy=H.prototype.destroy;return c}H.prototype.destroy=function(){this.catch(function(){});var a=Error("Destroyed!");a.type="destroy";this.reject(a)};function pb(a){a.split("").reduce(function(a,c,d){return a+(d&&0==d%4?" "+c:c)})};function qb(){this.g=new H;this.f=!1;this.a=null;this.b=[];this.c=null}function rb(a,b){if(a.f)throw Error("Cannot append to a running task!");a.b.push(b)}qb.prototype.start=function(){if(this.f)throw Error("Task already started!");this.f=!0;this.b.unshift(function(){});sb(this,void 0)};qb.prototype.end=function(){this.b.splice(1)};
function sb(a,b){var c=a.b[0](b),d;c?(d=c[0],a.c=c[1]):(d=Promise.resolve(),a.c=null);d.then(I(a,function(a){this.a?(this.b=[],this.c=null,tb(this)):(this.b.shift(),this.b.length?sb(this,a):(this.g.resolve(a),this.c=null))})).catch(I(a,function(a){this.b=[];this.c=null;this.a?tb(this):this.g.reject(a)}))}function tb(a){var b=Error("Task aborted.");b.type="aborted";a.g.reject(b);window.setTimeout(function(){this.a.resolve();this.a=null}.bind(a),5)};function I(a,b){return b.bind(a)};function ub(a,b,c){MediaSource.isTypeSupported(b);b=a.addSourceBuffer(b);this.h=a;this.c=b;this.u=c;this.i=new D;this.s=null;this.b=[];this.o=0;this.f=this.a=null;this.m=0;E(this.i,this.c,"updateend",this.v.bind(this))}var vb=1/60;ub.prototype.destroy=function(){wb(this).catch(function(){});this.f&&this.f.destroy();this.b=this.a=this.f=null;this.i.destroy();this.h=this.c=this.i=null};
function xb(a,b){for(var c=a.c.buffered,d=0;d<c.length;++d){var e=c.start(d)-vb,f=c.end(d)+vb;if(b>=e&&b<=f)return c.end(d)-b}return 0}
ub.prototype.fetch=function(a,b,c){if(this.a)return b=Error("Cannot fetch ("+this.j+"): previous operation not complete."),b.type="stream",Promise.reject(b);this.a=new qb;b!=this.c.timestampOffset&&(this.c.timestampOffset=b);c&&rb(this.a,function(){return[yb(this,c),this.g.bind(this)]}.bind(this));rb(this.a,function(){var b=a.endTime?a.endTime-a.startTime:1,c=new zb;c.a=3;c.h=1E3*b;c.c=1E3*this.m;c.j=this.s;return[a.url.fetch(c,this.u),J.prototype.c.bind(a.url)]}.bind(this));rb(this.a,I(this,function(a){this.u.getBandwidth();
return[yb(this,a),this.g.bind(this)]}));var d=0==this.c.buffered.length&&0==this.b.length,e=null;rb(this.a,function(){if(0==this.c.buffered.length){var b=Error("Failed to buffer segment ("+this.j+").");b.type="stream";return[Promise.reject(b)]}d&&(b=a.startTime,e=this.c.buffered.start(0)-b);b=Ab(this.b,a.startTime);0<=b?this.b.splice(b+1,0,a):this.b.push(a)}.bind(this));return Bb(this).then(function(){return Promise.resolve(e)}.bind(this))};
function Cb(a){if(a.a)return a=Error("Cannot clear ("+a.j+"): previous operation not complete."),a.type="stream",Promise.reject(a);a.a=new qb;rb(a.a,function(){var a;a:if(0==this.c.buffered.length)a=Promise.resolve();else{try{this.c.remove(0,this.h.duration)}catch(c){a=Promise.reject(c);break a}this.b=[];a=this.f=new H}return[a,this.g.bind(this)]}.bind(a));return Bb(a)}
function Db(a,b){if(a.a){var c=Error("Cannot clearAfter ("+a.j+"): previous operation not complete.");c.type="stream";return Promise.reject(c)}a.a=new qb;rb(a.a,function(){return[Eb(this,b),this.g.bind(this)]}.bind(a));return Bb(a)}function wb(a){a.a?(a=a.a,a.a?a=a.a:a.f?(a.c&&a.c(),a.a=new H,a=a.a):(a.f=!0,a=Promise.resolve())):a=Promise.resolve();return a}function Bb(a){a.a.start();return a.a.g.then(I(a,function(){this.a=null})).catch(I(a,function(a){this.a=null;return Promise.reject(a)}))}
function yb(a,b){try{a.c.appendBuffer(b)}catch(c){return Promise.reject(c)}a.f=new H;return a.f}function Eb(a,b){if(0==a.c.buffered.length)return Promise.resolve();var c=Ab(a.b,b);if(-1==c||c==a.b.length-1)return Promise.resolve();try{a.c.remove(a.b[c+1].startTime,a.h.duration)}catch(d){return Promise.reject(d)}a.b=a.b.slice(0,c+1);a.f=new H;return a.f}ub.prototype.g=function(){this.f&&"open"==this.h.readyState&&this.c.abort()};ub.prototype.v=function(){this.f&&(this.f.resolve(),this.f=null)};function Fb(a){return String.fromCharCode.apply(null,a)}m("shaka.util.Uint8ArrayUtils.toString",Fb);function Gb(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;++c)b[c]=a.charCodeAt(c);return b}m("shaka.util.Uint8ArrayUtils.fromString",Gb);m("shaka.util.Uint8ArrayUtils.toBase64",function(a,b){var c=void 0==b?!0:b,d=window.btoa(Fb(a)).replace(/\+/g,"-").replace(/\//g,"_");return c?d:d.replace(/=*$/,"")});function Hb(a){return Gb(window.atob(a.replace(/-/g,"+").replace(/_/g,"/")))}
m("shaka.util.Uint8ArrayUtils.fromBase64",Hb);m("shaka.util.Uint8ArrayUtils.fromHex",function(a){for(var b=new Uint8Array(a.length/2),c=0;c<a.length;c+=2)b[c/2]=window.parseInt(a.substr(c,2),16);return b});function Ib(a){for(var b="",c=0;c<a.length;++c){var d=a[c].toString(16);1==d.length&&(d="0"+d);b+=d}return b}m("shaka.util.Uint8ArrayUtils.toHex",Ib);function Jb(a,b){if(!a&&!b)return!0;if(!a||!b||a.length!=b.length)return!1;for(var c=0;c<a.length;++c)if(a[c]!=b[c])return!1;return!0};function Kb(){this.h=this.a="";this.j=!1;this.o=this.m=null;this.i=this.g=!1;this.u=this.f="";this.c=null;this.b=[]}function Lb(a,b){var c=new Kb;c.a=a.a;c.h=a.h;c.j=a.j;c.m=a.m;c.o=a.o;c.g=a.g;c.i=a.i;c.f=a.f;c.u=a.u;c.c=a.c?new Uint8Array(a.c.buffer):null;Mb(c,a.b);Mb(c,b.b);return c}function Mb(a,b){var c=a.b.concat(b.map(function(a){return{initData:new Uint8Array(a.initData.buffer),initDataType:a.initDataType}}));a.b=Pa(c,Nb)}
function Nb(a,b){return a.initDataType==b.initDataType&&Jb(a.initData,b.initData)};function Ob(a,b){try{var c=new Pb(a,b);return Promise.resolve(c)}catch(d){return Promise.reject(d)}}function Qb(a){var b=this.mediaKeys;b&&b!=a&&Rb(b,null);delete this.mediaKeys;(this.mediaKeys=a)&&Rb(a,this);return Promise.resolve()}
function Pb(a,b){this.a=this.keySystem=a;var c=!0;"org.w3.clearkey"==a&&(this.a="webkit-org.w3.clearkey",c=!1);var d=!1,e;e=document.getElementsByTagName("video");e=e.length?e[0]:document.createElement("video");for(var f=0;f<b.length;++f){var g=b[f],h={audioCapabilities:[],videoCapabilities:[],persistentState:"optional",distinctiveIdentifier:"optional",initDataTypes:g.initDataTypes,sessionTypes:["temporary"]},l=!1;if(g.audioCapabilities)for(var n=0;n<g.audioCapabilities.length;++n){var r=g.audioCapabilities[n];
r.contentType&&(l=!0,e.canPlayType(r.contentType.split(";")[0],this.a)&&(h.audioCapabilities.push(r),d=!0))}if(g.videoCapabilities)for(n=0;n<g.videoCapabilities.length;++n)r=g.videoCapabilities[n],r.contentType&&(l=!0,e.canPlayType(r.contentType,this.a)&&(h.videoCapabilities.push(r),d=!0));l||(d=e.canPlayType("video/mp4",this.a)||e.canPlayType("video/webm",this.a));"required"==g.persistentState&&(c?(h.persistentState="required",h.sessionTypes=["persistent-license"]):d=!1);if(d){this.b=h;return}}c=
"Unsupported keySystem";if("org.w3.clearkey"==a||"com.widevine.alpha"==a)c="None of the requested configurations were supported.";c=Error(c);c.name="NotSupportedError";c.code=DOMException.NOT_SUPPORTED_ERR;throw c;}Pb.prototype.createMediaKeys=function(){var a=new Sb(this.a);return Promise.resolve(a)};Pb.prototype.getConfiguration=function(){return this.b};function Sb(a){this.g=a;this.b=null;this.a=new D;this.c=[];this.f={}}
function Rb(a,b){a.b=b;mb(a.a);b&&(E(a.a,b,"webkitneedkey",a.ib.bind(a)),E(a.a,b,"webkitkeymessage",a.hb.bind(a)),E(a.a,b,"webkitkeyadded",a.fb.bind(a)),E(a.a,b,"webkitkeyerror",a.gb.bind(a)))}k=Sb.prototype;k.createSession=function(a){var b=a||"temporary";if("temporary"!=b&&"persistent-license"!=b)throw new TypeError("Session type "+a+" is unsupported on this platform.");a=this.b||document.createElement("video");a.src||(a.src="about:blank");b=new Tb(a,this.g,b);this.c.push(b);return b};
k.setServerCertificate=function(){return Promise.reject(Error("setServerCertificate not supported on this platform."))};k.ib=function(a){a=x({type:"encrypted",initDataType:"webm",initData:a.initData});this.b.dispatchEvent(a)};k.hb=function(a){var b=Ub(this,a.sessionId);b&&(a=x({type:"message",messageType:void 0==b.keyStatuses.na()?"licenserequest":"licenserenewal",message:a.message}),b.b&&(b.b.resolve(),b.b=null),b.dispatchEvent(a))};
k.fb=function(a){if(a=Ub(this,a.sessionId))Vb(a,"usable"),a.a&&a.a.resolve(),a.a=null};
k.gb=function(a){var b=Ub(this,a.sessionId);if(b){var c=Error("EME v0.1b key error");c.errorCode=a.errorCode;c.errorCode.systemCode=a.systemCode;!a.sessionId&&b.b?(c.method="generateRequest",45==a.systemCode&&(c.message="Unsupported session type."),b.b.reject(c),b.b=null):a.sessionId&&b.a?(c.method="update",b.a.reject(c),b.a=null):(c=a.systemCode,a.errorCode.code==MediaKeyError.MEDIA_KEYERR_OUTPUT?Vb(b,"output-restricted"):1==c?Vb(b,"expired"):Vb(b,"internal-error"))}};
function Ub(a,b){var c=a.f[b];return c?c:(c=a.c.shift())?(c.sessionId=b,a.f[b]=c):null}function Tb(a,b,c){F.call(this,null);this.f=a;this.h=!1;this.a=this.b=null;this.c=b;this.g=c;this.sessionId="";this.expiration=NaN;this.closed=new H;this.keyStatuses=new Wb}p(Tb,F);
function Xb(a,b,c){if(a.h)return Promise.reject(Error("The session is already initialized."));a.h=!0;var d;try{if("persistent-license"==a.g)if(c)d=Gb("LOAD_SESSION|"+c);else{var e=new Uint8Array(b);d=Gb("PERSISTENT|"+Fb(e))}else d=new Uint8Array(b)}catch(f){return Promise.reject(f)}a.b=new H;try{a.f.webkitGenerateKeyRequest(a.c,d)}catch(g){if("InvalidStateError"!=g.name)return a.b=null,Promise.reject(g);setTimeout(function(){try{this.f.webkitGenerateKeyRequest(this.c,d)}catch(a){this.b.reject(a),
this.b=null}}.bind(a),10)}return a.b}k=Tb.prototype;k.ra=function(a,b){if(this.a)this.a.then(this.ra.bind(this,a,b)).catch(this.ra.bind(this,a,b));else{this.a=a;var c,d;"webkit-org.w3.clearkey"==this.c?(c=Fb(new Uint8Array(b)),d=JSON.parse(c),"oct"!=d.keys[0].kty&&(this.a.reject(Error("Response is not a valid JSON Web Key Set.")),this.a=null),c=Hb(d.keys[0].k),d=Hb(d.keys[0].kid)):(c=new Uint8Array(b),d=null);try{this.f.webkitAddKey(this.c,c,d,this.sessionId)}catch(e){this.a.reject(e),this.a=null}}};
function Vb(a,b){a.keyStatuses.qa(b);var c=x({type:"keystatuseschange"});a.dispatchEvent(c)}k.generateRequest=function(a,b){return Xb(this,b,null)};k.load=function(a){return"persistent-license"==this.g?Xb(this,null,a):Promise.reject(Error("Not a persistent session."))};k.update=function(a){var b=new H;this.ra(b,a);return b};
k.close=function(){if("persistent-license"!=this.g){if(!this.sessionId)return this.closed.reject(Error("The session is not callable.")),this.closed;this.f.webkitCancelKeyRequest(this.c,this.sessionId)}this.closed.resolve();return this.closed};k.remove=function(){return"persistent-license"!=this.g?Promise.reject(Error("Not a persistent session.")):this.close()};function Wb(){this.size=0;this.a=void 0}var Yb;k=Wb.prototype;k.qa=function(a){this.size=void 0==a?0:1;this.a=a};k.na=function(){return this.a};
k.forEach=function(a){this.a&&a(Yb,this.a)};k.get=function(a){if(this.has(a))return this.a};k.has=function(a){var b=Yb;return this.a&&Jb(new Uint8Array(a),new Uint8Array(b))?!0:!1};function Zb(a){this.systemIds=[];this.cencKeyIds=[];this.a=[];a=new Ra(new DataView(a.buffer));try{for(;a.a<a.b.byteLength;){var b=a.a,c=v(a),d=v(a);1==c?c=Ua(a):0==c&&(c=a.b.byteLength-b);if(1886614376!=d)w(a,c-(a.a-b));else{var e=Ta(a);if(1<e)w(a,c-(a.a-b));else{w(a,3);var f=Ib(Va(a)),g=[];if(0<e)for(var h=v(a),l=0;l<h;++l){var n=Ib(Va(a));g.push(n)}var r=v(a);w(a,r);this.cencKeyIds.push.apply(this.cencKeyIds,g);this.systemIds.push(f);this.a.push({start:b,end:a.a-1});a.a!=b+c&&w(a,c-(a.a-b))}}}}catch(t){}}
;function $b(a,b){try{var c=new ac(a,b);return Promise.resolve(c)}catch(d){return Promise.reject(d)}}
function ac(a,b){this.keySystem=a;for(var c=!1,d=0;d<b.length;++d){var e=b[d],f={audioCapabilities:[],videoCapabilities:[],persistentState:"optional",distinctiveIdentifier:"optional",initDataTypes:e.initDataTypes,sessionTypes:["temporary"]},g=!1;if(e.audioCapabilities)for(var h=0;h<e.audioCapabilities.length;++h){var l=e.audioCapabilities[h];if(l.contentType){var g=!0,n=l.contentType.split(";")[0];MSMediaKeys.isTypeSupported(this.keySystem,n)&&(f.audioCapabilities.push(l),c=!0)}}if(e.videoCapabilities)for(h=
0;h<e.videoCapabilities.length;++h)l=e.videoCapabilities[h],l.contentType&&(g=!0,n=l.contentType.split(";")[0],MSMediaKeys.isTypeSupported(this.keySystem,n)&&(f.videoCapabilities.push(l),c=!0));g||(c=MSMediaKeys.isTypeSupported(this.keySystem,"video/mp4"));"required"==e.persistentState&&(f.persistentState="required",f.sessionTypes=["persistent-license"]);if(c){this.a=f;return}}c=Error("Unsupported keySystem");c.name="NotSupportedError";c.code=DOMException.NOT_SUPPORTED_ERR;throw c;}
ac.prototype.createMediaKeys=function(){var a=new bc(this.keySystem);return Promise.resolve(a)};ac.prototype.getConfiguration=function(){return this.a};function cc(a){var b=this.mediaKeys;b&&b!=a&&dc(b,null);delete this.mediaKeys;return(this.mediaKeys=a)?dc(a,this):Promise.resolve()}function bc(a){this.a=new MSMediaKeys(a);this.b=new D}bc.prototype.createSession=function(a){if("temporary"!=(a||"temporary"))throw new TypeError("Session type "+a+" is unsupported on this platform.");return new ec(this.a)};
bc.prototype.setServerCertificate=function(){return Promise.reject(Error("setServerCertificate not supported on this platform."))};function dc(a,b){function c(){b.msSetMediaKeys(d.a);b.removeEventListener("loadedmetadata",c)}mb(a.b);if(!b)return Promise.resolve();E(a.b,b,"msneedkey",fc);var d=a;try{return 1<=b.readyState?b.msSetMediaKeys(a.a):b.addEventListener("loadedmetadata",c),Promise.resolve()}catch(e){return Promise.reject(e)}}
function ec(a){F.call(this,null);this.c=null;this.g=a;this.b=this.a=null;this.f=new D;this.sessionId="";this.expiration=NaN;this.closed=new H;this.keyStatuses=new gc}p(ec,F);k=ec.prototype;k.generateRequest=function(a,b){this.a=new H;try{this.c=this.g.createSession("video/mp4",new Uint8Array(b),null),E(this.f,this.c,"mskeymessage",this.Va.bind(this)),E(this.f,this.c,"mskeyadded",this.Ta.bind(this)),E(this.f,this.c,"mskeyerror",this.Ua.bind(this)),hc(this,"status-pending")}catch(c){this.a.reject(c)}return this.a};
k.load=function(){return Promise.reject(Error("MediaKeySession.load not yet supported"))};k.update=function(a){this.b=new H;try{this.c.update(new Uint8Array(a))}catch(b){this.b.reject(b)}return this.b};k.close=function(){try{this.c.close(),this.closed.resolve(),mb(this.f)}catch(a){this.closed.reject(a)}return this.closed};k.remove=function(){return Promise.reject(Error("MediaKeySession.remove is only applicable for persistent licenses, which are not supported on this platform"))};
function fc(a){var b=a.initData;if(b){var c=new Zb(b);if(1>=c.a.length)a=b;else{var d=[];for(a=0;a<c.a.length;a++)d.push(b.subarray(c.a[a].start,c.a[a].end+1));b=Pa(d,ic);for(a=c=0;a<b.length;a++)c+=b[a].length;c=new Uint8Array(c);for(a=d=0;a<b.length;a++)c.set(b[a],d),d+=b[a].length;a=c}}else a=b;a=x({type:"encrypted",initDataType:"cenc",initData:a});this.dispatchEvent(a)}function ic(a,b){return Jb(a,b)}
k.Va=function(a){this.a&&(this.a.resolve(),this.a=null);a=x({type:"message",messageType:void 0==this.keyStatuses.na()?"licenserequest":"licenserenewal",message:a.message.buffer});this.dispatchEvent(a)};k.Ta=function(){this.a?(this.a.resolve(),this.a=null):this.b&&(hc(this,"usable"),this.b.resolve(),this.b=null)};
k.Ua=function(){var a=Error("EME v20140218 key error");a.errorCode=this.c.error;if(null!=this.a)this.a.reject(a),this.a=null;else if(null!=this.b)this.b.reject(a),this.b=null;else switch(this.c.error.code){case MSMediaKeyError.MS_MEDIA_KEYERR_OUTPUT:case MSMediaKeyError.MS_MEDIA_KEYERR_HARDWARECHANGE:hc(this,"output-not-allowed");default:hc(this,"internal-error")}};function hc(a,b){a.keyStatuses.qa(b);var c=x({type:"keystatuseschange"});a.dispatchEvent(c)}function gc(){this.size=0;this.a=void 0}var jc;
k=gc.prototype;k.qa=function(a){this.size=void 0==a?0:1;this.a=a};k.na=function(){return this.a};k.forEach=function(a){this.a&&a(jc,this.a)};k.get=function(a){if(this.has(a))return this.a};k.has=function(a){var b=jc;return this.a&&Jb(new Uint8Array(a),new Uint8Array(b))?!0:!1};function kc(){Navigator.prototype.requestMediaKeySystemAccess&&MediaKeySystemAccess.prototype.getConfiguration||(HTMLMediaElement.prototype.webkitGenerateKeyRequest?(Yb=(new Uint8Array([0])).buffer,Navigator.prototype.requestMediaKeySystemAccess=Ob,delete HTMLMediaElement.prototype.mediaKeys,HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=Qb,window.MediaKeys=Sb,window.MediaKeySystemAccess=Pb):window.MSMediaKeys?(jc=(new Uint8Array([0])).buffer,delete HTMLMediaElement.prototype.mediaKeys,
HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=cc,window.MediaKeys=bc,window.MediaKeySystemAccess=ac,Navigator.prototype.requestMediaKeySystemAccess=$b):(Navigator.prototype.requestMediaKeySystemAccess=xa,delete HTMLMediaElement.prototype.mediaKeys,HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=ya,window.MediaKeys=za,window.MediaKeySystemAccess=Aa))}m("shaka.polyfill.MediaKeys.install",kc);m("shaka.polyfill.installAll",function(){ta();va();Na();Ca();kc()});var lc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function K(a){var b;a instanceof K?(mc(this,a.H),this.O=a.O,this.G=a.G,nc(this,a.X),this.D=a.D,oc(this,a.a.clone()),this.L=a.L):a&&(b=String(a).match(lc))?(mc(this,b[1]||"",!0),this.O=pc(b[2]||""),this.G=pc(b[3]||"",!0),nc(this,b[4]),this.D=pc(b[5]||"",!0),oc(this,b[6]||"",!0),this.L=pc(b[7]||"")):this.a=new L(null)}k=K.prototype;k.H="";k.O="";k.G="";k.X=null;k.D="";k.L="";
k.toString=function(){var a=[],b=this.H;b&&a.push(qc(b,rc,!0),":");if(b=this.G){a.push("//");var c=this.O;c&&a.push(qc(c,rc,!0),"@");a.push(encodeURIComponent(b).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.X;null!=b&&a.push(":",String(b))}if(b=this.D)this.G&&"/"!=b.charAt(0)&&a.push("/"),a.push(qc(b,"/"==b.charAt(0)?sc:tc,!0));(b=this.a.toString())&&a.push("?",b);(b=this.L)&&a.push("#",qc(b,uc));return a.join("")};
k.resolve=function(a){var b=this.clone();"data"===b.H&&(b=new K);var c=!!a.H;c?mc(b,a.H):c=!!a.O;c?b.O=a.O:c=!!a.G;c?b.G=a.G:c=null!=a.X;var d=a.D;if(c)nc(b,a.X);else if(c=!!a.D){if("/"!=d.charAt(0))if(this.G&&!this.D)d="/"+d;else{var e=b.D.lastIndexOf("/");-1!=e&&(d=b.D.substr(0,e+1)+d)}if(".."==d||"."==d)d="";else if(-1!=d.indexOf("./")||-1!=d.indexOf("/.")){for(var e=0==d.lastIndexOf("/",0),d=d.split("/"),f=[],g=0;g<d.length;){var h=d[g++];"."==h?e&&g==d.length&&f.push(""):".."==h?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),e&&g==d.length&&f.push("")):(f.push(h),e=!0)}d=f.join("/")}}c?b.D=d:c=""!==a.a.toString();c?oc(b,a.a.clone()):c=!!a.L;c&&(b.L=a.L);return b};k.clone=function(){return new K(this)};function mc(a,b,c){a.H=c?pc(b,!0):b;a.H&&(a.H=a.H.replace(/:$/,""))}function nc(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.X=b}else a.X=null}function oc(a,b,c){b instanceof L?a.a=b:(c||(b=qc(b,vc)),a.a=new L(b))}
function pc(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}function qc(a,b,c){return"string"==typeof a?(a=encodeURI(a).replace(b,wc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function wc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var rc=/[#\/\?@]/g,tc=/[\#\?:]/g,sc=/[\#\?]/g,vc=/[\#\?@]/g,uc=/#/g;function L(a){this.b=a||null}L.prototype.a=null;L.prototype.c=null;
function xc(a,b,c){if(!a.a&&(a.a={},a.c=0,a.b))for(var d=a.b.split("&"),e=0;e<d.length;e++){var f=d[e].indexOf("="),g=null,h=null;0<=f?(g=d[e].substring(0,f),h=d[e].substring(f+1)):g=d[e];g=decodeURIComponent(g.replace(/\+/g," "));h=h||"";xc(a,g,decodeURIComponent(h.replace(/\+/g," ")))}a.b=null;(d=a.a.hasOwnProperty(b)&&a.a[b])||(a.a[b]=d=[]);d.push(c);a.c++}
L.prototype.toString=function(){if(this.b)return this.b;if(!this.a)return"";var a=[],b;for(b in this.a)for(var c=encodeURIComponent(b),d=this.a[b],e=0;e<d.length;e++){var f=c;""!==d[e]&&(f+="="+encodeURIComponent(d[e]));a.push(f)}return this.b=a.join("&")};L.prototype.clone=function(){var a=new L;a.b=this.b;if(this.a){var b={},c;for(c in this.a)b[c]=this.a[c].concat();a.a=b;a.c=this.c}return a};function yc(){this.id=this.url=null;this.type="static";this.b=this.j=this.l=this.Da=null;this.g=5;this.i=this.c=this.f=null;this.h=1;this.a=[]}function zc(){this.g=this.f=this.c=this.l=this.b=this.start=this.id=null;this.a=[]}function Ac(){this.i=this.b=this.height=this.width=this.contentType=this.lang=this.group=this.id=null;this.c=!1;this.h=this.g=this.f=this.l=null;this.j=[];this.a=[]}function Bc(){this.value=null}function Cc(){this.contentType=this.lang=this.id=null}
function Dc(){this.g=this.f=this.c=this.l=this.h=this.b=this.height=this.width=this.bandwidth=this.lang=this.id=null;this.a=[]}function Ec(){this.b=this.a=this.c=this.f=null}function Fc(){this.parsedPssh=this.psshBox=null}function Gc(){this.url=null}function Hc(){this.url=null}function M(){this.l=null;this.g=1;this.c=this.b=this.a=this.f=null}M.prototype.clone=function(){var a=new M;a.l=N(this.l);a.g=this.g;a.f=this.f;a.a=O(this.a);a.b=O(this.b);a.c=O(this.c);return a};
function Ic(){this.a=this.url=null}Ic.prototype.clone=function(){var a=new Ic;a.url=N(this.url);a.a=O(this.a);return a};function Jc(){this.a=this.url=null}Jc.prototype.clone=function(){var a=new Jc;a.url=N(this.url);a.a=O(this.a);return a};function Kc(){this.l=null;this.b=1;this.g=this.a=null;this.i=1;this.f=null;this.c=[];this.h=null}Kc.prototype.clone=function(){var a=new Kc;a.l=N(this.l);a.b=this.b;a.a=this.a;a.g=this.g;a.i=this.i;a.f=O(this.f);a.c=N(this.c)||[];a.h=O(this.h);return a};
function Lc(){this.a=this.b=null}Lc.prototype.clone=function(){var a=new Lc;a.b=N(this.b);a.a=O(this.a);return a};function Mc(){this.b=1;this.h=this.a=null;this.j=1;this.i=this.f=this.c=this.g=null}Mc.prototype.clone=function(){var a=new Mc;a.b=this.b;a.a=this.a;a.h=this.h;a.j=this.j;a.g=this.g;a.c=this.c;a.f=this.f;a.i=O(this.i);return a};function Nc(){this.a=[]}Nc.prototype.clone=function(){var a=new Nc;a.a=N(this.a)||[];return a};function Oc(){this.b=this.a=this.startTime=null}
Oc.prototype.clone=function(){var a=new Oc;a.startTime=this.startTime;a.a=this.a;a.b=this.b;return a};function Pc(a,b){this.fa=a;this.end=b}Pc.prototype.clone=function(){return new Pc(this.fa,this.end)};yc.TAG_NAME="MPD";zc.TAG_NAME="Period";Ac.TAG_NAME="AdaptationSet";Bc.TAG_NAME="Role";Cc.TAG_NAME="ContentComponent";Dc.TAG_NAME="Representation";Ec.TAG_NAME="ContentProtection";Fc.TAG_NAME="cenc:pssh";Gc.TAG_NAME="BaseURL";Hc.TAG_NAME="Location";M.TAG_NAME="SegmentBase";Ic.TAG_NAME="RepresentationIndex";
Jc.TAG_NAME="Initialization";Kc.TAG_NAME="SegmentList";Lc.TAG_NAME="SegmentURL";Mc.TAG_NAME="SegmentTemplate";Nc.TAG_NAME="SegmentTimeline";Oc.TAG_NAME="S";
yc.prototype.parse=function(a,b){this.url=a.Da;this.id=P(b,"id",Q);this.type=P(b,"type",Q)||"static";this.b=P(b,"mediaPresentationDuration",Qc);this.g=P(b,"minBufferTime",Qc,this.g);this.f=P(b,"minimumUpdatePeriod",Qc,this.f);this.c=P(b,"availabilityStartTime",Tc,this.c);this.i=P(b,"timeShiftBufferDepth",Qc,this.i);this.h=P(b,"suggestedPresentationDelay",Qc,this.h);var c=a.l,d=R(this,b,Gc);this.l=Uc(c,d);if(d=S(this,b,Hc))this.j=Vc(c,d.url);this.a=R(this,b,zc)};
zc.prototype.parse=function(a,b){this.id=P(b,"id",Q);this.start=P(b,"start",Qc);this.b=P(b,"duration",Qc);var c=R(this,b,Gc);this.l=Uc(a.l,c);this.c=S(this,b,M);this.f=S(this,b,Kc);this.g=S(this,b,Mc);this.a=R(this,b,Ac);Wc(this)};function Wc(a){for(var b=[],c=0;c<a.a.length;++c){var d=a.a[c];null!=d.group&&(b[d.group]=!0)}for(c=0;c<a.a.length;++c)if(d=a.a[c],null==d.group){for(var e=1;1==b[e];)++e;b[e]=!0;d.group=e}}
Ac.prototype.parse=function(a,b){var c=S(this,b,Cc)||{},d=S(this,b,Bc);this.id=P(b,"id",Q);this.group=P(b,"group",T);this.lang=P(b,"lang",Q,c.lang);this.contentType=P(b,"contentType",Q,c.contentType);this.width=P(b,"width",U);this.height=P(b,"height",U);this.b=P(b,"mimeType",Q);this.i=P(b,"codecs",Q);this.c=d&&"main"==d.value;this.lang&&(this.lang=ab(this.lang));c=R(this,b,Gc);this.l=Uc(a.l,c);this.j=R(this,b,Ec);!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]);this.f=a.c?Xc(this,
b,a.c):S(this,b,M);this.g=a.f?Xc(this,b,a.f):S(this,b,Kc);this.h=a.g?Xc(this,b,a.g):S(this,b,Mc);this.a=R(this,b,Dc);!this.b&&this.a.length&&(this.b=this.a[0].b,!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]))};Bc.prototype.parse=function(a,b){this.value=P(b,"value",Q)};Cc.prototype.parse=function(a,b){this.id=P(b,"id",Q);this.lang=P(b,"lang",Q);this.contentType=P(b,"contentType",Q);this.lang&&(this.lang=ab(this.lang))};
Dc.prototype.parse=function(a,b){this.id=P(b,"id",Q);this.bandwidth=P(b,"bandwidth",U);this.width=P(b,"width",U,a.width);this.height=P(b,"height",U,a.height);this.b=P(b,"mimeType",Q,a.b);this.h=P(b,"codecs",Q,a.i);this.lang=a.lang;var c=R(this,b,Gc);this.l=Uc(a.l,c);this.a=R(this,b,Ec);this.c=a.f?Xc(this,b,a.f):S(this,b,M);this.f=a.g?Xc(this,b,a.g):S(this,b,Kc);this.g=a.h?Xc(this,b,a.h):S(this,b,Mc);this.a=this.a.concat(a.j)};
Ec.prototype.parse=function(a,b){this.f=b;this.c=P(b,"schemeIdUri",Q);var c=P(b,"cenc:default_KID",Q);c&&(this.b=c.replace(/[-]/g,""));this.a=S(this,b,Fc)};Fc.prototype.parse=function(a,b){var c=Yc(b);if(c){this.psshBox=Hb(c);try{this.parsedPssh=new Zb(this.psshBox)}catch(d){if(!(d instanceof RangeError))throw d;}}};Gc.prototype.parse=function(a,b){this.url=Yc(b)};Hc.prototype.parse=function(a,b){this.url=Yc(b)};
M.prototype.parse=function(a,b){this.l=a.l||this.l;this.g=P(b,"timescale",U,this.g);this.f=P(b,"presentationTimeOffset",T,this.f);this.a=P(b,"indexRange",Zc,this.a);this.b=S(this,b,Ic)||this.b;this.c=S(this,b,Jc)||this.c};Ic.prototype.parse=function(a,b){var c=P(b,"sourceURL",Q);this.url=Vc(a.l,c);this.a=P(b,"range",Zc,O(a.a))};Jc.prototype.parse=function(a,b){var c=P(b,"sourceURL",Q);this.url=Vc(a.l,c);this.a=P(b,"range",Zc)};
Kc.prototype.parse=function(a,b){this.l=a.l||this.l;this.b=P(b,"timescale",U,this.b);this.a=P(b,"presentationTimeOffset",T,this.a);this.g=P(b,"duration",U,this.g);var c=P(b,"startNumber",U);null!=c&&(this.i=c);this.f=S(this,b,Jc)||this.f;this.c=(c=R(this,b,Lc))&&0<c.length?c:this.c;this.h=S(this,b,Nc)||this.h};Lc.prototype.parse=function(a,b){var c=P(b,"media",Q);this.b=Vc(a.l,c);this.a=P(b,"mediaRange",Zc)};
Mc.prototype.parse=function(a,b){this.b=P(b,"timescale",U,this.b);this.a=P(b,"presentationTimeOffset",T,this.a);this.h=P(b,"duration",U,this.h);var c=P(b,"startNumber",T);null!=c&&(this.j=c);this.g=P(b,"media",Q,this.g);this.c=P(b,"index",Q,this.c);this.f=P(b,"initialization",Q,this.f);this.i=S(this,b,Nc)||this.i};Nc.prototype.parse=function(a,b){this.a=R(this,b,Oc)};Oc.prototype.parse=function(a,b){this.startTime=P(b,"t",T);this.a=P(b,"d",T);this.b=P(b,"r",$c)};
function Uc(a,b){if(!b||0===b.length)return a;for(var c=[],d=0;d<b.length;d++){var e=b[d].url;null==a||0===a.length?c.push(new K(e)):(e=Vc(a.slice(0,1),e),c.push(e[0]))}return c}function Vc(a,b){if(!b)return a;var c=new K(b);return a?a.map(function(a){return a.resolve(c)}):[c]}function Xc(a,b,c){var d=O(c);(b=ad(b,c.constructor.TAG_NAME))&&d.parse(a,b);return d}function S(a,b,c){var d=null;if(b=ad(b,c.TAG_NAME))d=new c,d.parse(a,b);return d}
function ad(a,b){for(var c=null,d=0;d<a.childNodes.length;d++)if(a.childNodes[d].tagName==b){if(c)return null;c=a.childNodes[d]}return c}function R(a,b,c){for(var d=[],e=0;e<b.childNodes.length;e++)if(b.childNodes[e].tagName==c.TAG_NAME){var f=new c;f.parse.call(f,a,b.childNodes[e]);d.push(f)}return d}function Yc(a){a=a.firstChild;return a.nodeType!=Node.TEXT_NODE?null:a.nodeValue}function N(a){return a?a.map(function(a){return a.clone()}):null}function O(a){return a?a.clone():null}
function P(a,b,c,d){a=c(a.getAttribute(b));return null!=a?a:void 0!==d?d:null}function Tc(a){if(!a)return null;a=Date.parse(a);return isNaN(a)?null:Math.floor(a/1E3)}
function Qc(a){if(!a)return null;var b=/^P(?:([0-9]*)Y)?(?:([0-9]*)M)?(?:([0-9]*)D)?(?:T(?:([0-9]*)H)?(?:([0-9]*)M)?(?:([0-9.]*)S)?)?$/.exec(a);if(!b)return null;a=0;var c=T(b[1]);c&&(a+=31536E3*c);(c=T(b[2]))&&(a+=2592E3*c);(c=T(b[3]))&&(a+=86400*c);(c=T(b[4]))&&(a+=3600*c);(c=T(b[5]))&&(a+=60*c);b=window.parseFloat(b[6]);(b=isNaN(b)?null:b)&&(a+=b);return a}
function Zc(a){var b=/([0-9]+)-([0-9]+)/.exec(a);if(!b)return null;a=T(b[1]);if(null==a)return null;b=T(b[2]);return null==b?null:new Pc(a,b)}function $c(a){a=window.parseInt(a,10);return isNaN(a)?null:a}function U(a){a=window.parseInt(a,10);return 0<a?a:null}function T(a){a=window.parseInt(a,10);return 0<=a?a:null}function Q(a){return a};function bd(a,b){this.url=a;this.b=b||new zb;this.g=this.i=this.h=0;this.a=null;this.c=new H;this.f=null}function zb(){this.body=null;this.a=1;this.h=1E3;this.c=0;this.method="GET";this.f="arraybuffer";this.b={};this.g=this.i=!1;this.j=null}var cd=!0;function dd(a){ed(a);a.b.body=null;a.c.destroy();a.c=null;a.f=null}function ed(a){a.a&&(a.a.onload=null,a.a.onreadystatechange=null,a.a.onerror=null,a.a.ontimeout=null);a.a=null}k=bd.prototype;
k.Ha=function(){if(this.a)return this.c;if(0==this.url.lastIndexOf("data:",0)){var a=this.url.split(":")[1].split(";").pop().split(","),b=a.pop(),b="base64"==a.pop()?window.atob(b.replace(/-/g,"+").replace(/_/g,"/")):window.decodeURIComponent(b);"arraybuffer"==this.b.f&&(b=Gb(b).buffer);a=JSON.parse(JSON.stringify(new XMLHttpRequest));a.response=b;a.responseText=b.toString();b=this.c;b.resolve(a);dd(this);return b}if(0==this.url.lastIndexOf("idb:",0))return this.j();this.h++;this.i=Date.now();this.g||
(this.g=this.b.h);this.a=Za("new_http_request",{url:this.url});this.a||(this.a=new XMLHttpRequest);a=this.url;cd&&(this.f&&!this.f.supportsCaching()||this.b.g)&&(a=new K(a),xc(a.a,"_",Date.now()),a=a.toString());this.a.open(this.b.method,a,!0);this.a.responseType=this.b.f;this.a.timeout=this.b.c;this.a.withCredentials=this.b.i;this.a.onload=this.Ra.bind(this);this.b.g&&(this.a.onreadystatechange=this.Ya.bind(this));this.a.onerror=this.lb.bind(this);this.a.ontimeout=this.bb.bind(this);for(b in this.b.b)this.a.setRequestHeader(b,
this.b.b[b]);this.a.send(this.b.body);return this.c};function fd(a,b,c){b=Error(b);b.type=c;b.status=a.a.status;b.url=a.url;b.method=a.b.method;b.body=a.b.body;b.xhr=a.a;return b}k.Ra=function(a){this.f&&this.f.sample(Date.now()-this.i,a.loaded);200<=this.a.status&&299>=this.a.status?(this.c.resolve(this.a),dd(this)):this.h<this.b.a?gd(this):(a=fd(this,"HTTP error.","net"),this.c.reject(a),dd(this))};
k.Ya=function(){if(this.a.readyState==XMLHttpRequest.HEADERS_RECEIVED){var a=Date.parse(this.a.getResponseHeader("Date"));a&&(Qa=a-Date.now())}};k.lb=function(){var a=fd(this,"Network failure.","net");this.c.reject(a);dd(this)};k.bb=function(){if(this.h<this.b.a)gd(this);else{var a=fd(this,"Request timed out.","net");this.c.reject(a);dd(this)}};function gd(a){ed(a);window.setTimeout(a.Ha.bind(a),a.g*(1+.5*(2*Math.random()-1)));a.g*=2};function J(a,b,c,d){this.J=b;this.h=c||0;this.g=null!=d?d:null;this.b=this.a=null;this.i=a;this.f=null}J.prototype.fetch=function(a,b){if(this.a)return this.a;var c=a||new zb;if(this.h||this.g)c.b.Range="bytes="+(this.h+"-"+(null!=this.g?this.g:""));return this.a=hd(this,0,c,b)};J.prototype.c=function(){if(this.b){this.a=null;var a=this.b;if(a.a&&a.a.readyState!=XMLHttpRequest.DONE){a.a.abort();var b=fd(a,"Request aborted.","aborted");a.c.reject(b);dd(a)}this.f=this.b=null}};
function hd(a,b,c,d){var e=a.J[b].toString();a.i&&(e=a.i(e,c.b)||e);a.b=new bd(e,c);d&&(a.b.f=d);e=a.b.Ha().then(I(a,function(a){this.f=this.b=this.a=null;this.f=a.a?new K(a.a):this.J[b];return Promise.resolve(a.response)}));return e=e.catch(I(a,function(a){if(this.a&&b+1<this.J.length)return this.a=hd(this,b+1,c,d);this.a=this.b=null;return Promise.reject(a)}))}J.prototype.clone=function(){return new J(this.i,this.J.map(function(a){return a.clone()}),this.h,this.g)};J.prototype.toString=function(){return this.J[0].toString()};function id(a,b){this.a=new zb;this.a.f="text";this.a.a=3;this.a.c=1E3*(null!=b?b:0);this.a.g=!0;this.b=a}function jd(a){var b=a.b;return b.fetch(a.a).then(function(a){var d;d=b.J;var e=[b.f];d=(a=(new DOMParser).parseFromString(a,"text/xml"))?S({Da:d,l:e},a,yc):null;if(d)return Promise.resolve(d);d=Error("MPD parse failure.");d.type="dash";return Promise.reject(d)})};function kd(a,b){this.a=a;this.b=b||null}kd.prototype.destroy=function(){this.a&&(this.a.c(),this.a=null);this.b=null};kd.prototype.create=function(){return this.a?this.a.fetch():Promise.resolve(this.b)};function ld(a,b,c){this.startTime=a;this.endTime=b;this.url=c}function Ab(a,b){for(var c=a.length-1;0<=c;--c){var d=a[c];if(b>=d.startTime&&(null==d.endTime||b<d.endTime))return c}return-1}function md(a,b){return a.map(function(a){return new ld(a.startTime+b,null!=a.endTime?a.endTime+b:null,a.url)})};function nd(){}
nd.prototype.parse=function(a,b,c,d){var e=null;try{a:{var f=[],g=new Ra(a),h=v(g);if(1936286840!=v(g))e=null;else{1==h&&(h=Ua(g));var l=Ta(g);w(g,3);w(g,4);var n=v(g);if(0==n)e=null;else{var r,t;0==l?(r=v(g),t=v(g)):(r=Ua(g),t=Ua(g));w(g,2);var B=g.b.getUint16(g.a,g.c);g.a+=2;a=r;b=b+h+t;for(h=0;h<B;h++){var ib=v(g);t=(ib&2147483648)>>>31;var l=ib&2147483647,Rc=v(g);v(g);if(1==t){e=null;break a}var de=new J(d,c,b,b+l-1);f.push(new ld(a/n,(a+Rc)/n,de));a+=Rc;b+=l}e=f}}}}catch(Sc){if(!(Sc instanceof RangeError))throw Sc;
}return e};function od(a){this.references=a;this.a=0}od.prototype.destroy=function(){this.references=null};od.prototype.length=function(){return this.references.length};function pd(a){if(0==a.references.length)throw new RangeError("SegmentIndex: There is no first SegmentReference.");return a.references[0]}od.prototype.W=function(){if(0==this.references.length)throw new RangeError("SegmentIndex: There is no last SegmentReference.");return this.references[this.references.length-1]};
od.prototype.get=function(a){if(0>a||a>=this.references.length)throw new RangeError("SegmentIndex: The specified index is out of range.");return this.references[a]};function qd(a,b){var c=Ab(a.references,b);return 0<=c?a.references[c]:null}function rd(a,b){var c=b-a.a;0!=c&&(a.references=md(a.references,c),a.a=b)};function sd(){this.a=td++;this.id=this.M=this.segmentIndexSource=null;this.h=0;this.height=this.width=this.bandwidth=null;this.f=this.c="";this.g=[];this.F=!1;this.b=!0}var td=0;sd.prototype.destroy=function(){this.segmentIndexSource&&(this.segmentIndexSource.destroy(),this.segmentIndexSource=null);this.M&&(this.M.destroy(),this.M=null)};function ud(a){var b=a.c||"";a.f&&(b+='; codecs="'+a.f+'"');return b}
function vd(){this.a=wd++;this.id=null;this.contentType=this.lang="";this.c=!1;this.streamInfos=[];this.b=[]}var wd=0;vd.prototype.destroy=function(){for(var a=0;a<this.streamInfos.length;++a)this.streamInfos[a].destroy();this.b=this.streamInfos=null};function xd(a){for(var b=[],c=0;c<a.b.length;++c){var d=new yd;d.id=a.a;d.a=a.b[c];d.contentType=a.contentType;d.b=a.streamInfos.length?ud(a.streamInfos[0]):"";b.push(d)}return b}
function zd(){this.id=null;this.start=0;this.a=null;this.streamSetInfos=[]}zd.prototype.destroy=function(){for(var a=0;a<this.streamSetInfos.length;++a)this.streamSetInfos[a].destroy();this.streamSetInfos=null};function Ad(){this.a=!1;this.c=this.g=this.f=null;this.b=0;this.periodInfos=[]}Ad.prototype.destroy=function(){for(var a=0;a<this.periodInfos.length;++a)this.periodInfos[a].destroy();this.periodInfos=null};function yd(){this.id=0;this.a=null;this.b=this.contentType=""};function Bd(a,b,c,d,e){F.call(this,a);this.c=b;this.a=new ub(c,d,e);this.s=this.segmentIndex_=this.b=null;this.B=!1;this.g=null;this.m=!1;this.i=null;this.o=!1;this.h=new H;this.j=this.f=!1;this.v=0;this.C=15;this.w=!1}p(Bd,F);Bd.prototype.A=function(a){null!=a.initialStreamBufferSize&&(this.v=Number(a.initialStreamBufferSize));null!=a.streamBufferSize&&(this.C=Number(a.streamBufferSize));null!=a.segmentRequestTimeout&&(this.a.m=Number(a.segmentRequestTimeout))};
Bd.prototype.destroy=function(){Cd(this);this.h.destroy();this.b=this.h=null;this.a.destroy();this.u=this.c=this.a=null};k=Bd.prototype;k.ga=function(){return this.b};k.Ba=function(){return this.segmentIndex_};k.Ia=function(a){this.f||a.then(function(){this.f=!0;this.g||Dd(this,0)}.bind(this)).catch(function(){});return this.h};k.Ca=function(){return this.j};
k.ia=function(a,b,c){if(a!=this.b){var d=[a.segmentIndexSource.create(),a.M.create()];Promise.all(d).then(I(this,function(d){if(this.c){var f=this.b;this.b=a;this.segmentIndex_=d[0];this.s=d[1];this.B=!0;this.m||(f?b&&Ed(this,!0,c):Dd(this,0))}})).catch(I(this,function(a){"aborted"!=a.type&&(this.f?(a=y(a),this.dispatchEvent(a)):this.h.reject(a))}))}};k.Ea=function(){return Ed(this,!1)};
function Ed(a,b,c){a.b&&!a.m&&(a.m=!0,Cd(a),wb(a.a).then(I(a,function(){var a=this.c.currentTime;if(!b&&0<xb(this.a,a)&&0<=Ab(this.a.b,a))return Promise.resolve();if(c)return Db(this.a,this.c.currentTime+c);this.w=!0;return Cb(this.a)})).then(I(a,function(){this.m=!1;Dd(this,0)})).catch(I(a,function(a){this.m=!1;this.f?(a=y(a),this.dispatchEvent(a)):this.h.reject(a)})))}k.Fa=function(a){return 0<xb(this.a,a)&&0<=Ab(this.a.b,a)};k.ha=function(){};k.ma=function(){return!0};
k.eb=function(){if(this.o&&!this.f)this.g=null;else{var a;if(a=this.f&&!this.j)a=1<this.a.c.buffered.length?!0:!1;if(a)Ed(this,!0);else{this.g=null;a=this.b;var b=this.segmentIndex_,c=this.c.currentTime;xb(this.a,this.o?c:c+(this.i||0))>=(this.o?Math.max(this.v,this.C):this.v)?(Fd(this),Dd(this,1E3/(Math.abs(this.c.playbackRate)||1))):(b=Gd(this,c,b))?(b=this.a.fetch(b,a.h,this.s),this.s=null,this.B&&(this.B=!1,Hd(this,a)),this.j=!1,b.then(I(this,function(a){null==this.i&&(this.i=a);this.w&&0<xb(this.a,
c)&&(this.w=!1,this.c.currentTime+=.001);Dd(this,0)})).catch(I(this,function(a){if("aborted"!=a.type){var b=[0,404,410];"net"==a.type&&-1!=b.indexOf(a.xhr.status)&&this.b&&Dd(this,5E3);a=y(a);this.dispatchEvent(a)}}))):(Fd(this),this.f&&!this.j&&(this.j=!0,Id(this)),Dd(this,1E3))}}};function Gd(a,b,c){a=a.a;var d=a.b.length;a=0<d?a.b[d-1]:null;return null!=a?null!=a.endTime?qd(c,a.endTime):null:qd(c,b)||(c.length()?c.W():null)}
function Fd(a){if(!a.o&&null!=a.i){a.o=!0;var b=a.a,c=a.i,d=c-b.o;0!=d&&(b.b=md(b.b,d),b.o=c);a.h.resolve(a.i)}}function Hd(a,b){var c;c=b.c.split("/")[0];c=x({type:"adaptation",bubbles:!0,contentType:c,size:"video"!=c?null:{width:b.width,height:b.height},bandwidth:b.bandwidth});a.dispatchEvent(c)}function Id(a){var b=x({type:"ended"});a.dispatchEvent(b)}function Dd(a,b){a.g=window.setTimeout(a.eb.bind(a),b)}function Cd(a){null!=a.g&&(window.clearTimeout(a.g),a.g=null)};function Jd(a){this.a=a;this.segmentIndex_=null}Jd.prototype.destroy=function(){this.segmentIndex_&&(this.segmentIndex_.destroy(),this.segmentIndex_=null)};Jd.prototype.create=function(){if(this.segmentIndex_)return Promise.resolve(this.segmentIndex_);var a=new ld(0,null,this.a);this.segmentIndex_=new od([a]);return Promise.resolve(this.segmentIndex_)};function Kd(a,b){F.call(this,a);this.b=b;this.g=!0;this.segmentIndex_=this.f=null;this.c=new H;this.a=null}p(Kd,F);Kd.prototype.A=function(){};Kd.prototype.destroy=function(){this.a&&this.b.removeChild(this.a);this.c.destroy();this.u=this.b=this.f=this.segmentIndex_=this.a=this.c=null};k=Kd.prototype;k.ga=function(){return this.f};k.Ba=function(){return this.segmentIndex_};k.Ia=function(){return this.c};k.Ca=function(){return!0};
k.ia=function(a){a.segmentIndexSource.create().then(I(this,function(b){if(this.b){if(0==b.length())return Promise.reject(Error("No subtitles URL available."));var c=this.f;this.f=a;this.segmentIndex_=b;b=pd(b).url.J[0].toString();var d=this.ma();this.a&&(this.ha(!1),this.b.removeChild(this.a));this.a=document.createElement("track");this.b.appendChild(this.a);this.a.src=b;this.ha(d);b=x({type:"adaptation",bubbles:!0,contentType:"text",size:null,bandwidth:a.bandwidth});this.dispatchEvent(b);c||this.c.resolve(0)}}))};
k.Ea=function(){};k.Fa=function(){return!0};k.ha=function(a){this.g=a;this.a&&(this.a.track.mode=a?"showing":"disabled")};k.ma=function(){this.a&&(this.g="showing"==this.a.track.mode);return this.g};function Ld(a,b,c,d,e,f,g){this.f=c;this.a=d;this.c=e;this.b=null;this.g=g}Ld.prototype.destroy=function(){this.g=null;this.a.c();this.a=null;this.c&&(this.c.c(),this.c=null);this.b=null};
Ld.prototype.create=function(){if("webm"==this.f){var a=Error("WebM is not supported in this build configuration.");a.type="app";return Promise.reject(a)}if(this.b)return this.b;a=[this.a.fetch()];"webm"==this.f&&a.push(this.c.fetch());return this.b=Promise.all(a).then(I(this,function(a){a=a[0];var c=null;"mp4"==this.f&&(c=(new nd).parse(new DataView(a),this.a.h,this.a.J,this.g));return c?Promise.resolve(new od(c)):(a=Error("Failed to parse SegmentReferences from "+this.a.toString()+" (or one of its fallbacks)."),
a.type="stream",Promise.reject(a))}))};function Md(a){this.a=a}
function Nd(a){if(a.a.length){null==a.a[0].start&&(a.a[0].start=0);var b=function(a){return 0==a||!!a};"dynamic"==a.type&&(a.b=null);b(a.b)&&1==a.a.length&&!b(a.a[0].b)&&(a.a[0].b=a.b);for(var c=0,d=!0,e=0;e<a.a.length;++e){var f=a.a[e-1],g=a.a[e],h=a.a[e+1]||{start:a.b};!b(g.start)&&f&&b(f.start)&&b(f.b)&&(g.start=f.start+f.b);!b(g.b)&&b(h.start)&&(g.b=h.start-g.start);null!=g.start&&null!=g.b?c+=g.b:d=!1}b(a.b)||(e=a.a[a.a.length-1],d?a.b=c:b(e.start)&&b(e.b)?a.b=e.start+e.b:"dynamic"!=a.type&&
(a.b=c))}}function Od(a,b,c){var d=new zd;d.id=b.id;d.start=b.start;d.a=b.b;var e=new C;b.a.forEach(function(a){e.push(a.contentType||"",a)});b=lb(e);for(var f=0;f<b.length;++f){var g=new C;e.get(b[f]).forEach(function(a){g.push(a.group,a)});for(var h=lb(g),l=0;l<h.length;++l){var n=new C;g.get(h[l]).forEach(function(a){n.push(a.lang,a)});for(var r=lb(n),t=0;t<r.length;++t){var B=n.get(r[t]),B=Pd(a,B,c);d.streamSetInfos.push(B)}}}return d}
function Pd(a,b,c){ba(b.every(function(a){return a.group==b[0].group&&(a.lang||"")==(b[0].lang||"")&&(a.contentType||"")==(b[0].contentType||"")}));var d=new vd,e=b.filter(function(a){return null!=a.id});e.length==b.length&&(d.id=e.map(function(a){return a.id}).sort().reduce(function(a,b){return a+","+b}));d.lang=b[0].lang||"";d.contentType=b[0].contentType||"";d.c=b.some(function(a){return a.c});for(var e={},f=0;f<b.length;++f)for(var g=b[f],h=0;h<g.a.length;++h){var l=g.a[h],n=Qd(a,l),r=d.b.slice(0);
Rd(n,r);0==r.length&&0<d.b.length||!(l=Sd(l,c))||(d.streamInfos.push(l),d.b=r,e[l.a]=g)}if(d.b.some(function(a){return""==a.a}))return d.streamInfos.forEach(function(a){a.F=!0}),d;a=Td(b);for(f=0;f<d.streamInfos.length;++f)l=d.streamInfos[f],g=e[l.a],g==a&&(l.F=!0);return d}function Td(a){for(var b=null,c=null,d=0;d<a.length;++d)for(var e=a[d],f=0;f<e.a.length;++f){var g=e.a[f],g=(g.width||1)*(g.height||1)*(g.bandwidth||1);if(null==b||g<b)b=g,c=e}return c}
function Rd(a,b){if(0==b.length)Array.prototype.push.apply(b,a);else for(var c=0;c<b.length;++c){for(var d=!1,e=0;e<a.length;++e){var f=b[c],g=a[e];if(f.a==g.a&&f.h==g.h&&f.j==g.j&&f.g==g.g&&f.i==g.i&&f.f==g.f&&f.u==g.u&&Jb(f.c,g.c)){d=!0;Mb(b[c],a[e].b);break}}d||(b.splice(c,1),--c)}}function Qd(a,b){var c=[];if(0==b.a.length)c.push(new Kb);else if(a.a)for(var d=0;d<b.a.length;++d)c.push.apply(c,Ud(a,b.a[d]));return c}
function Ud(a,b){var c=[];if(2!=a.a.length)return[];var d=a.a(b.c||"",b.f);if(!(d&&d instanceof Array))return[];for(var e=0;e<d.length;++e){var f;var g=d[e];f=new Kb;if(g){var h=z(g,"keySystem");if(null!=h)f.a=h;else throw Error("'keySystem' cannot be null.");var l=z(g,"licenseServerUrl");if(null!=l)f.h=l;else if(h)throw Error("For encrypted streaming content, 'licenseServerUrl' cannot be null or empty.");h=fb(g,"withCredentials");null!=h&&(f.j=h);h=A(g,"licensePostProcessor",Function);null!=h&&(f.m=
h);h=A(g,"licensePreProcessor",Function);null!=h&&(f.o=h);h=fb(g,"distinctiveIdentifierRequired");null!=h&&(f.g=h);h=fb(g,"persistentStateRequired");null!=h&&(f.i=h);h=z(g,"audioRobustness");null!=h&&(f.f=h);h=z(g,"videoRobustness");null!=h&&(f.u=h);h=A(g,"serverCertificate",Uint8Array);null!=h&&(f.c=h);if(h=A(g,"initData",Object)){g=A(h,"initData",Uint8Array);if(null==g)throw Error("'initData.initData' cannot be null.");h=z(h,"initDataType");if(null==h)throw Error("'initData.initDataType' cannot be null.");
f.b.push({initData:new Uint8Array(g.buffer),initDataType:h})}}0==f.b.length&&b.a&&b.a.psshBox&&Mb(f,[{initData:b.a.psshBox,initDataType:"cenc"}]);c.push(f)}return c}
function Sd(a,b){if(!a.l||0===a.l.length)return null;var c=null,d=1,e=0;a.c?(c=a.b.split("/")[1],"mp4"!=c&&"webm"!=c?c=null:(d=a.c,"webm"!=c||d.c?d.a||d.b&&d.b.a?(e=d.b,e||(e=new Ic,e.url=a.l,e.a=d.a?d.a.clone():null),e=Vd(e,b),d=d.c?Vd(d.c,b):null,c=new Ld(0,0,c,e,d,0,b),d=new kd(d),e=new sd,e.segmentIndexSource=c,e.M=d,c=e):c=null:c=null),d=a.c.g,e=a.c.f):a.f?(c=null,d=a.f.b,e=a.f.a):a.g?(c=null,d=a.g.b,e=a.g.a):"text"==a.b.split("/")[0]&&(c=new sd,c.segmentIndexSource=new Jd(new J(b,a.l)));if(!c)return null;
c.id=a.id;e&&(c.h=-1*e/d);c.bandwidth=a.bandwidth;c.width=a.width;c.height=a.height;c.c=a.b||"";c.f=a.h||"";for(d=0;d<a.a.length;++d)e=a.a[d],e.b&&c.g.push(e.b);return c}function Vd(a,b){var c=a.url,d=0,e=null;a.a&&(d=a.a.fa,e=a.a.end);return new J(b,c,d,e)};function Wd(){this.streamStats=null;this.droppedFrames=this.decodedFrames=NaN;this.bufferingTime=this.playTime=this.estimatedBandwidth=0;this.playbackLatency=NaN;this.bufferingHistory=[];this.bandwidthHistory=[];this.streamHistory=[]}function Xd(a,b){var c=new Yd(b);a.streamHistory.push(new Zd(c));if(c.videoHeight||!a.streamStats)a.streamStats=c}function Yd(a){this.videoWidth=a.width;this.videoHeight=a.height;this.videoMimeType=a.c;this.videoBandwidth=a.bandwidth}
function Zd(a){this.timestamp=(Date.now()+Qa)/1E3;this.value=a};function $d(a,b,c,d,e){this.b=new J(null,[new K(a)]);this.a=new zb;this.a.body=b;this.a.method=c;this.a.a=3;this.a.i=d;this.a.c=0;a=e||{};for(var f in a)this.a.b[f]=a[f]}function ae(a){return a.b.fetch(a.a).then(function(a){return Promise.resolve(new Uint8Array(a))})};function V(a,b,c){F.call(this,a);this.c=b;this.j=c;this.a=this.h=null;this.i=new D;this.b=[];this.f=[];this.o=0;this.g=new H;this.m=null}p(V,F);V.prototype.destroy=function(){this.u=null;for(var a=0;a<this.f.length;++a)this.f[a].close().catch(function(){});this.f=[];this.b=this.a=this.h=null;this.g.destroy();this.g=null;this.i.destroy();this.i=null;this.m&&(window.clearTimeout(this.m),this.m=null);this.c=this.j=null};
V.prototype.initialize=function(){var a=new C,b;b=this.j;if(b.v){b=b.a.periodInfos[0];for(var c=[],d=0;d<b.streamSetInfos.length;++d)c.push.apply(c,xd(b.streamSetInfos[d]));b=c}else b=[];for(c=0;c<b.length;++c)d=b[c],d.a.a||d.b&&!be(d.b)||a.push(d.contentType,d);for(var c={},d=!1,e=0;e<b.length;++e){var f=b[e];if(f.a.a&&!a.a.hasOwnProperty(f.contentType)){var g=f.a.a,h=c[g];h||(h=f.a,h={audioCapabilities:void 0,videoCapabilities:void 0,initDataTypes:void 0,distinctiveIdentifier:h.g?"required":"optional",
persistentState:h.i?"required":"optional",sessionTypes:["temporary"]},c[g]=h);if(f.b&&(g=f.contentType+"Capabilities",g in h)){d=!0;h[g]||(h[g]=[]);var l;"audio"==f.contentType?l=f.a.f:"video"==f.contentType&&(l=f.a.u);h[g].push({contentType:f.b,robustness:l})}}}if(!d)if(b.length)this.a=b[0].a;else throw a=Error("No DrmInfo exists!"),a.type="drm",a;if(0==Object.keys(c).length)return ce(this.j,a),this.g.resolve(),Promise.resolve();l=new H;c=ee(c,l);c=c.then(this.v.bind(this,b,a));l.reject(null);return c};
function ee(a,b){for(var c in a)b=b.catch(function(a,b){return navigator.requestMediaKeySystemAccess(a,[b])}.bind(null,c,a[c]));return b}
V.prototype.v=function(a,b,c){if(!this.c)return fe();for(var d=c.keySystem,e=c.getConfiguration(),f=["audio","video"],g=0;g<f.length;++g){var h=f[g];if(!b.a.hasOwnProperty(h)){var l=e[h+"Capabilities"];if(l){for(var l=l[0],n=[],r={},t=0;t<a.length;++t){var B=a[t],ib=l?B.b==l.contentType:B.contentType==h;B.a.a!=d||!ib||B.id in r||(n.push(B),r[B.id]=!0,this.a=this.a?Lb(this.a,B.a):B.a)}b.set(h,n)}}}ce(this.j,b);return c.createMediaKeys().then(function(a){this.h=a}.bind(this))};
function ge(a){return a.c?a.h?a.c.setMediaKeys(a.h).then(I(a,function(){return this.c?this.a.c?this.h.setServerCertificate(this.a.c):Promise.resolve():fe()})).then(I(a,function(){if(!this.c)return fe();for(var a=0;a<this.a.b.length;++a){var c=this.a.b[a];this.s({type:"encrypted",initDataType:c.initDataType,initData:c.initData})}0==this.a.b.length&&E(this.i,this.c,"encrypted",this.s.bind(this))})):Promise.resolve():fe()}
function fe(){var a=Error("EmeManager destroyed");a.type="destroy";return Promise.reject(a)}
V.prototype.s=function(a){for(var b=new Uint8Array(a.initData),c=0;c<this.b.length;++c)if(Jb(b,this.b[c].data))return;try{var d=he(this)}catch(e){b=y(e);this.dispatchEvent(b);this.g.reject(e);return}a=d.generateRequest(a.initDataType,a.initData);this.b.push({data:b,pa:d});a.catch(I(this,function(a){if(this.c){for(var b=0;b<this.b.length;++b)if(this.b[b].pa==d){this.b.splice(b,1);break}b=y(a);this.dispatchEvent(b);this.g.reject(a)}}));this.f.push(d)};
function he(a){var b=null,b=a.h.createSession();E(a.i,b,"message",a.A.bind(a));E(a.i,b,"keystatuseschange",a.w.bind(a));return b}V.prototype.A=function(a){ie(this,a.target,this.a,a.message)};
V.prototype.w=function(a){a=a.target;var b={};a.keyStatuses.forEach(function(a,c){if("string"==typeof a){var f=a;a=c;c=f}if("com.microsoft.playready"==this.a.a&&16==a.byteLength){var f=new DataView(a),g=f.getUint32(0,!0),h=f.getUint16(4,!0),l=f.getUint16(6,!0);f.setUint32(0,g,!1);f.setUint16(4,h,!1);f.setUint16(6,l,!1)}f=Ib(new Uint8Array(a));b[f]=c}.bind(this));if(a.expiration<Date.now()){for(var c=0;c<this.b.length;++c)if(this.b[c].pa==a){this.b.splice(c,1);break}a.close();this.f.splice(this.f.indexOf(a),
1)}je(this.j,b)};function ie(a,b,c,d){d=ke(c,d);ae(new $d(d.url,d.body,d.method,c.j,d.headers)).then(I(a,function(a){c.m&&(a=c.m(a));return b.update(a)})).then(I(a,function(){var a=x({type:"sessionReady",detail:b});this.dispatchEvent(a);this.o++;this.o>=this.f.length&&this.g.resolve()})).catch(I(a,function(a){a.pa=b;a=y(a);this.dispatchEvent(a)}))}
function ke(a,b){var c={url:a.h,body:b.slice(0),method:"POST",headers:{}};if("com.microsoft.playready"===a.a){for(var d=String.fromCharCode.apply(null,new Uint16Array(c.body)),d=(new DOMParser).parseFromString(d,"application/xml"),e=d.getElementsByTagName("name"),f=d.getElementsByTagName("value"),g=0;g<e.length;g++)c.headers[e[g].childNodes[0].nodeValue]=f[g].childNodes[0].nodeValue;c.body=window.atob(d.getElementsByTagName("Challenge")[0].childNodes[0].nodeValue)}if(!a.o)return c;a.o(c);c.url=z(c,
"url");if(null==c.url)throw Error("'url' cannot be null.");if(!(c.body instanceof ArrayBuffer||"string"==typeof c.body||null==c.body))throw new TypeError("'body' must be an ArrayBuffer, a string, or null.");c.method=z(c,"method");if("GET"!=c.method&&"POST"!=c.method)throw Error("'method' must be either 'GET' or 'POST'.");c.headers=A(c,"headers",Object);if(null==c.headers)throw Error("'headers' cannot be null.");return c};function W(a){F.call(this,null);this.a=a;this.b=null;this.f=new D;this.j=this.i=null;this.w=0;this.s=null;this.h=!1;this.g=new Wd;this.c={enableAdaptation:!0,streamBufferSize:15,liveStreamEndTimeout:15,licenseRequestTimeout:0,mpdRequestTimeout:0,segmentRequestTimeout:0,preferredLanguage:"en",restrictions:new ja};this.m=1;this.A=null}p(W,F);m("shaka.player.Player",W);W.version="v1.6.5-hola-2-4-gb56db77-dirty";
W.isBrowserSupported=function(){return!!window.MediaSource&&!!window.MediaKeys&&!!window.navigator&&!!window.navigator.requestMediaKeySystemAccess&&!!window.MediaKeySystemAccess&&!!window.MediaKeySystemAccess.prototype.getConfiguration&&!!window.Promise&&!!Element.prototype.requestFullscreen&&!!document.exitFullscreen&&"fullscreenElement"in document&&!!window.Uint8Array};function be(a){return"text/vtt"==a?!!window.VTTCue:MediaSource.isTypeSupported(a)}W.isTypeSupported=be;
W.setTextStyle=function(a){var b=document.getElementById("ShakaPlayerTextStyle");b||(b=document.createElement("style"),b.id="ShakaPlayerTextStyle",document.head.appendChild(b));for(b=b.sheet;b.cssRules.length;)b.deleteRule(0);b.insertRule("::cue { "+oa(a)+" }",0)};W.prototype.destroy=function(){return this.o().then(I(this,function(){this.f.destroy();this.a=this.f=null})).catch(function(){})};W.prototype.destroy=W.prototype.destroy;
W.prototype.o=function(){if(!this.b)return Promise.resolve();this.h&&le(this);this.a.pause();mb(this.f);me(this);ne(this);this.i&&(this.i.destroy(),this.i=null);this.a.src="";var a=this.a.setMediaKeys(null);this.b&&(this.b.destroy(),this.b=null);this.h=!1;this.g=new Wd;return a};W.prototype.unload=W.prototype.o;W.prototype.K=function(){return this.a};W.prototype.getVideo=W.prototype.K;W.prototype.P=function(){return this.b};W.prototype.getVideoSource=W.prototype.P;
W.prototype.ba=function(a){var b=this.o();this.a.autoplay&&(da("load"),E(this.f,this.a,"timeupdate",this.Qa.bind(this)));a.xa(this.c);a.K=this.A;this.A=null;b=b.then(I(this,function(){return a.Z()}));b.catch(I(this,function(b){a.destroy();return Promise.reject(b)}));return b.then(I(this,function(){if(!this.a)return oe();this.b=a;E(this.f,this.b,"seekrangechanged",this.Za.bind(this));this.i=new V(this,this.a,this.b);return this.i.initialize()})).then(I(this,function(){if(!this.a)return oe();E(this.f,
this.a,"error",this.jb.bind(this));E(this.f,this.a,"playing",this.Xa.bind(this));E(this.f,this.a,"pause",this.Wa.bind(this));var a;a=this.b;var b=this.a;a.v?(a.u=this,a.video=b,a.video.shaka=this,a.w=this.Ga(),E(a.i,a.f,"sourceopen",a.Sa.bind(a)),E(a.i,a.U,"bandwidth",a.kb.bind(a)),b=a.video.mediaKeys,a.video.src=window.URL.createObjectURL(a.f),b=a.video.setMediaKeys(b),a=Promise.all([a.h,b])):(a=Error("Cannot call attach() right now."),a.type="app",a=Promise.reject(a));Za("shaka_message",{id:"attach",
ob:this,video:this.a});return a})).then(I(this,function(){return this.a?ge(this.i):oe()})).then(I(this,function(){if(!this.a)return oe();pe(this)})).catch(I(this,function(a){if(!this.a)return oe();if("destroy"!=a.type){var b=y(a);this.dispatchEvent(b)}return this.o().then(function(){return Promise.reject(a)})}))};W.prototype.load=W.prototype.ba;function oe(){var a=Error("Player destroyed");a.type="destroy";return Promise.reject(a)}k=W.prototype;
k.Qa=function(){ga("load");this.g.playbackLatency=ha("load")/1E3;this.f.aa(this.a,"timeupdate")};k.jb=function(){if(this.a.error){var a=this.a.error.code;a!=MediaError.MEDIA_ERR_ABORTED&&(a=Error(qe[a]||"Unknown playback error."),a.type="playback",a=y(a),this.dispatchEvent(a))}};k.Xa=function(){da("playing");!this.j&&0>this.m&&(this.a.playbackRate=0,this.v(this.a.currentTime,Date.now(),this.m));this.h&&le(this)};
k.Wa=function(){ga("playing");var a=ha("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3}ne(this)};k.Za=function(a){this.w=a.start};k.Ga=function(){if(!this.a.paused){ga("playing");var a=ha("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3;da("playing")}}a=this.g;b=this.a;b.getVideoPlaybackQuality&&(b=b.getVideoPlaybackQuality(),a.decodedFrames=b.totalVideoFrames,a.droppedFrames=b.droppedVideoFrames);return this.g};W.prototype.getStats=W.prototype.Ga;
W.prototype.$=function(){return this.b?this.b.C():[]};W.prototype.getVideoTracks=W.prototype.$;W.prototype.V=function(){return this.b?this.b.T():[]};W.prototype.getAudioTracks=W.prototype.V;W.prototype.Z=function(){return this.b?this.b.ya():[]};W.prototype.getTextTracks=W.prototype.Z;W.prototype.selectVideoTrack=function(a,b){return this.b?this.b.selectVideoTrack(a,void 0==b?!0:b):!1};W.prototype.selectVideoTrack=W.prototype.selectVideoTrack;
W.prototype.ca=function(a,b,c){return this.b?re(this.b,"audio",a,void 0==b?!0:b,c):!1};W.prototype.selectAudioTrack=W.prototype.ca;W.prototype.da=function(a){return this.b?re(this.b,"text",a,!1):!1};W.prototype.selectTextTrack=W.prototype.da;W.prototype.U=function(a){this.b&&se(this.b,a)};W.prototype.enableTextTrack=W.prototype.U;W.prototype.S=function(a){ne(this);0<=a?this.a.playbackRate=a:this.a.paused||(this.a.playbackRate=0,this.v(this.a.currentTime,Date.now(),a));this.m=a};
W.prototype.setPlaybackRate=W.prototype.S;W.prototype.C=function(){return this.m};W.prototype.getPlaybackRate=W.prototype.C;W.prototype.ea=function(a){this.A=a};W.prototype.setPlaybackStartTime=W.prototype.ea;W.prototype.B=function(){var a;this.b?(a=this.b,a=a.a?a.a.a:!1):a=!1;return a};W.prototype.isLive=W.prototype.B;
W.prototype.T=function(a){if(a){var b=fb(a,"enableAdaptation");null!=b&&(this.c.enableAdaptation=b);b=hb(a,"streamBufferSize");null!=b&&(this.c.streamBufferSize=b);b=hb(a,"liveStreamEndTimeout");null!=b&&(this.c.liveStreamEndTimeout=b);b=hb(a,"licenseRequestTimeout");null!=b&&(this.c.licenseRequestTimeout=b);b=hb(a,"mpdRequestTimeout");null!=b&&(this.c.mpdRequestTimeout=b);b=hb(a,"segmentRequestTimeout");null!=b&&(this.c.segmentRequestTimeout=b);b=z(a,"preferredLanguage");null!=b&&(this.c.preferredLanguage=
b);b=A(a,"restrictions",ja);null!=b&&(this.c.restrictions=b.clone());a=fb(a,"disableCacheBustingEvenThoughItMayAffectBandwidthEstimation");null!=a&&(cd=!a);this.b&&this.b.xa(this.c)}};W.prototype.configure=W.prototype.T;W.prototype.Y=function(){return this.c};W.prototype.getConfiguration=W.prototype.Y;function ne(a){a.j&&(window.clearTimeout(a.j),a.j=null)}function pe(a){me(a);a.s=window.setTimeout(a.R.bind(a),100)}function me(a){a.s&&(window.clearTimeout(a.s),a.s=null)}
W.prototype.v=function(a,b,c){this.j=null;var d=(Date.now()-b)/1E3*c;this.a.currentTime<this.w+(this.B()?1:.05)?this.a.pause():(d=Math.max(this.w,a+d),this.a.currentTime=d,this.j=window.setTimeout(this.v.bind(this,a,b,c),250))};function le(a){ga("buffering");var b=a.g;b.bufferingTime+=ha("buffering")/1E3;a.h=!1;a.dispatchEvent(x({type:"bufferingEnd"}))}
W.prototype.R=function(){pe(this);if(!this.a.ended&&!this.a.seeking){var a=this.a.buffered,b=a.length?a.end(a.length-1):0,a=Math.max(b-this.a.currentTime,0),c=this.a.duration,c=isNaN(c)?0:Math.max(c-.05,0),b=b>=c||this.a.currentTime>=c;if(this.h){if(c=Number(this.b.A.initialStreamBufferSize),b||a>c)le(this),this.a.play()}else!this.a.paused&&!b&&.5>a&&(this.h=!0,this.a.pause(),this.g.bufferingHistory.push((Date.now()+Qa)/1E3),da("buffering"),this.dispatchEvent(x({type:"bufferingStart"})))}};
var qe={2:"A network failure occured while loading media content.",3:"The browser failed to decode the media content.",4:"The browser does not support the media content."};function te(a,b){var c=a.bandwidth||Number.MAX_VALUE,d=b.bandwidth||Number.MAX_VALUE;return c<d?-1:c>d?1:0};function X(){this.a=this.b=null;this.f=new D;this.c=Number.POSITIVE_INFINITY;this.i=!0;this.g=!1}m("shaka.media.SimpleAbrManager",X);X.prototype.destroy=function(){this.f.destroy();this.a=this.b=this.f=null};X.prototype.initialize=function(a,b){this.b||this.a||(this.b=a,this.a=b)};
X.prototype.start=function(){this.b&&this.a&&!this.g&&(this.c=Date.now()+4E3,E(this.f,this.b,"bandwidth",this.u.bind(this)),E(this.f,this.a,"adaptation",this.j.bind(this)),E(this.f,this.a,"trackschanged",this.h.bind(this)),this.g=!0)};X.prototype.enable=function(a){this.i=a};X.prototype.getInitialVideoTrackId=function(){if(!this.b||!this.a)return null;var a=ue(this);return a?a.id:null};X.prototype.selectVideoTrack=function(a,b,c){this.g&&this.a.selectVideoTrack(a.id,b,c)};
X.prototype.u=function(){Date.now()<this.c||this.h()};X.prototype.h=function(){if(this.i){var a=ue(this);if(a){if(a.active){this.c=Date.now()+3E3;return}this.selectVideoTrack(a,!1)}this.c=Number.POSITIVE_INFINITY}};X.prototype.j=function(){this.c==Number.POSITIVE_INFINITY&&(this.c=Date.now()+3E4)};
function ue(a){var b=a.a.C();if(0==b.length)return null;b.sort(sa);var c;a:{c=a.a.T();for(var d=0;d<c.length;++d)if(c[d].active){c=c[d];break a}c=null}c=c?c.bandwidth:0;a=a.b.getBandwidth();for(var d=b[0],e=0;e<b.length;++e){var f=b[e],g=e+1<b.length?b[e+1]:{bandwidth:Number.POSITIVE_INFINITY};if(f.bandwidth&&(g=(g.bandwidth+c)/.85,a>=(f.bandwidth+c)/.95&&a<=g&&(d=f,d.active)))break}return d};function Y(a,b,c){F.call(this,null);this.a=a;this.U=b;this.i=new D;this.f=new MediaSource;this.video=null;this.ta=0;this.b=new C;this.m=c;this.m.initialize(b,this);this.v=!1;this.s="en";this.V=!1;this.w=null;this.h=new H;this.g=new ja;this.j=null;this.va=1;this.c={};this.R=new H;this.sa=0;this.P=null;this.ba=this.ea=!1;this.o={};this.K=this.B=this.$=null;this.A={}}p(Y,F);m("shaka.player.StreamVideoSource",Y);
Y.prototype.xa=function(a){null!=a.streamBufferSize&&(this.A.streamBufferSize=a.streamBufferSize);null!=a.segmentRequestTimeout&&(this.A.segmentRequestTimeout=a.segmentRequestTimeout);ve(this);null!=a.enableAdaptation&&this.m.enable(Boolean(a.enableAdaptation));null!=a.mpdRequestTimeout&&(this.ta=Number(a.mpdRequestTimeout));null!=a.preferredLanguage&&(this.s=ab(String(a.preferredLanguage)));null!=a.restrictions&&(this.g=a.restrictions,this.v&&we(this))};
Y.prototype.destroy=function(){this.h.destroy();this.R.destroy();this.R=this.h=null;this.B&&(window.clearTimeout(this.B),this.B=null);this.$&&(window.clearTimeout(this.$),this.$=null);this.o=null;this.i.destroy();this.i=null;eb(this.c).forEach(function(a){a.destroy()});this.b=this.c=null;this.a&&(this.a.destroy(),this.a=null);this.m.destroy();this.f=this.U=this.m=null;this.video&&(delete this.video.shaka,this.video=null);this.u=this.g=this.w=null};
Y.prototype.Z=function(){if(this.v){var a=Error("Cannot call load() right now.");a.type="app";return Promise.reject(a)}if(!this.a||0==this.a.periodInfos.length)return a=Error("The manifest does not specify any content."),a.type="stream",Promise.reject(a);if(this.a.a)return a=Error("Live manifest support not enabled."),a.type="app",Promise.reject(a);for(var a=this.a.periodInfos,b=0;b<a.length;++b)for(var c=a[b],d=0;d<c.streamSetInfos.length;++d){for(var e=c.streamSetInfos[d],f=e,g=0;g<f.streamInfos.length;++g)be(ud(f.streamInfos[g]))||
(f.streamInfos.splice(g,1),--g);0==e.streamInfos.length&&(c.streamSetInfos.splice(d,1),--d)}for(b=0;b<a.length;++b)for(c=a[b],d=0;d<c.streamSetInfos.length;++d)c.streamSetInfos[d].streamInfos.sort(te);if(0==this.a.periodInfos.length||0==this.a.periodInfos[0].streamSetInfos.length)return a=Error("The manifest specifies content that cannot be displayed on this browser/platform."),a.type="stream",Promise.reject(a);this.v=!0;this.A.initialStreamBufferSize=this.a.b;ve(this);we(this);return Promise.resolve()};
Y.prototype.C=function(){if(!this.b.a.hasOwnProperty("video"))return[];for(var a=this.c.video,a=(a=a?a.ga():null)?a.a:0,b=[],c=this.b.get("video"),d=0;d<c.length;++d)for(var e=c[d],f=0;f<e.streamInfos.length;++f){var g=e.streamInfos[f];if(g.F&&g.b){var h=g.a,g=new ra(h,g.bandwidth,g.width,g.height);h==a&&(g.active=!0);b.push(g)}}return b};Y.prototype.getVideoTracks=Y.prototype.C;
Y.prototype.T=function(){if(!this.b.a.hasOwnProperty("audio"))return[];for(var a=this.c.audio,a=(a=a?a.ga():null)?a.a:0,b=[],c=this.b.get("audio"),d=0;d<c.length;++d)for(var e=c[d],f=e.lang,g=0;g<e.streamInfos.length;++g){var h=e.streamInfos[g];if(h.F&&h.b){var l=h.a,h=new ia(l,h.bandwidth,f);l==a&&(h.active=!0);b.push(h)}}return b};Y.prototype.getAudioTracks=Y.prototype.T;
Y.prototype.ya=function(){if(!this.b.a.hasOwnProperty("text"))return[];for(var a=this.c.text,b=a?a.ga():null,b=b?b.a:0,c=[],d=this.b.get("text"),e=0;e<d.length;++e)for(var f=d[e],g=f.lang,h=0;h<f.streamInfos.length;++h){var l=f.streamInfos[h].a,n=new qa(l,g);l==b&&(n.active=!0,n.enabled=a.ma());c.push(n)}return c};Y.prototype.getTextTracks=Y.prototype.ya;
function ce(a,b){if(a.v){for(var c={},d=a.a.periodInfos[0],e=0;e<d.streamSetInfos.length;++e){var f=d.streamSetInfos[e];c[f.a]=f}a.b.a={};d=lb(b);for(e=0;e<d.length;++e){var f=d[e],g=b.get(f);if("video"==f){var h=g[0].id;a.b.push(f,c[h])}else if("audio"==f)for(var h=g[0].b.split(";")[0],l=0;l<g.length;++l){var n=g[l];n.b.split(";")[0]==h&&a.b.push(f,c[n.id])}else for(l=0;l<g.length;++l)h=g[l].id,a.b.push(f,c[h])}a.V=!0;if(c=a.b.get("audio"))xe(a,c),a.b.set("audio",c),c=c[0].lang||a.s,$a(2,a.s,c)&&
(a.V=!1);if(c=a.b.get("text"))xe(a,c),a.b.set("text",c),c=c[0].lang||a.s,$a(2,a.s,c)||(a.V=!1)}}Y.prototype.selectVideoTrack=function(a,b,c){return re(this,"video",a,b,c)};function se(a,b){var c=a.c.text;c&&c.ha(b)}
function we(a){if(a.g){for(var b=!1,c=0;c<a.a.periodInfos.length;++c)for(var d=a.a.periodInfos[c],e=0;e<d.streamSetInfos.length;++e){var f=d.streamSetInfos[e];if("video"==f.contentType)for(var g=0;g<f.streamInfos.length;++g){var h=f.streamInfos[g],l=h.b;h.b=!0;a.g.maxWidth&&h.width>a.g.maxWidth&&(h.b=!1);a.g.maxHeight&&h.height>a.g.maxHeight&&(h.b=!1);a.g.minHeight&&h.height<a.g.minHeight&&(h.b=!1);a.g.maxBandwidth&&h.bandwidth>a.g.maxBandwidth&&(h.b=!1);a.g.minBandwidth&&h.bandwidth<a.g.minBandwidth&&
(h.b=!1);l!=h.b&&(b=!0)}}0!=jb(a.b).length&&b&&(ye(a),0<a.C().length||(b=Error("The application has restricted all video tracks!"),b.type="app",b=y(b),a.dispatchEvent(b)))}}
function je(a,b){for(var c,d=!1,e=new C,f=jb(a.b),g=0;g<f.length;++g)for(var h=f[g],l=0;l<h.streamInfos.length;++l){var n=h.streamInfos[l];n.g.forEach(function(a){e.push(a,n)})}for(c in b)if(f=Wa[b[c]]||null,h=e.get(c))for(g=0;g<h.length;++g)n=h[g],l=n.F,n.F=!f,l!=n.F&&(d=!0);else pb(c);d&&(ye(a),d=a.T(),c=a.C(),d=a.b.a.hasOwnProperty("audio")&&0==d.length,c=a.b.a.hasOwnProperty("video")&&0==c.length,d||c)&&(c=Error("The key system has restricted all "+(d&&c?"audio and video tracks.":d?"audio tracks.":
"video tracks.")),c.type="drm",c=y(c),a.dispatchEvent(c))}function ye(a){var b=x({type:"trackschanged",bubbles:!0});a.dispatchEvent(b)}function re(a,b,c,d,e){if(!a.b.a.hasOwnProperty(b)||!a.c[b])return!1;for(var f=a.b.get(b),g=0;g<f.length;++g)for(var h=f[g],l=0;l<h.streamInfos.length;++l){var n=h.streamInfos[l];if(n.a==c){if(!n.F||!n.b)return!1;if("text"!=b&&!a.ba)return c=a.o[b],a.o[b]={Ja:n,za:null!=c&&c.za||d,Aa:null!=c&&c.Aa||e},!0;Xd(a.w,n);a.c[b].ia(n,d,e);return!0}}return!1}
function xe(a,b){for(var c=0;2>=c;++c)for(var d=0;d<b.length;++d){var e=b[d];if($a(c,a.s,e.lang)){b.splice(d,1);b.splice(0,0,e);return}}for(d=0;d<b.length;++d)if(e=b[d],e.c){b.splice(d,1);b.splice(0,0,e);break}}k=Y.prototype;k.Sa=function(){this.i.aa(this.f,"sourceopen");ze(this).then(I(this,function(){this.h&&this.h.resolve()})).catch(I(this,function(a){this.h&&this.h.reject(a)}))};
function ze(a){for(var b=[],c=["audio","video","text"],d=0;d<c.length;++d){var e=c[d];a.b.a.hasOwnProperty(e)&&b.push(a.b.get(e)[0])}for(var f=Ae(a,b),d=0;d<c.length;++d)if(e=c[d],a.b.a.hasOwnProperty(e)&&!f[e])return a=Error("Unable to select an initial "+e+" stream: all "+e+" streams have been restricted (by the application or by the key system)."),a.type="stream",Promise.reject(a);b=eb(f).map(function(a){return a.segmentIndexSource.create()});return Promise.all(b).then(I(a,function(a){if(!a.every(function(a){return a.length()}))return a=
Error("Some streams are not available."),a.type="stream",Promise.reject(a);a=Be(this,a);if(!a)return a=Error("Some streams are not available."),a.type="stream",Promise.reject(a);if(!Ce(this,f))return a=Error("Failed to create Stream objects."),a.type="stream",Promise.reject(a);this.m.start();De(this,f,a);return Promise.resolve()})).catch(I(a,function(a){if("aborted"!=a.type)return Object.keys(this.c),this.a.a?(Date.now()+Qa<this.a.c?this.nb():this.Oa(0),Promise.resolve()):Promise.reject(a)}))}
function Ae(a,b){for(var c={},d=0;d<b.length;++d){var e=b[d],f=null;if("video"==e.contentType){var g=a.m.getInitialVideoTrackId();if(null==g)continue;f=e.streamInfos.filter(function(a){return a.a==g});if(0==f.length)continue;f=f[0]}else if("audio"==e.contentType){f=e.streamInfos.filter(function(a){return a.F&&a.b});if(0==f.length)continue;f=e.streamInfos[Math.floor(f.length/2)]}else 0<e.streamInfos.length&&(f=e.streamInfos[0]);c[e.contentType]=f}return c}
function Ce(a,b){var c={},d;for(d in b){var e=b[d],e="text"==d?new Kd(a,a.video):Ee(a,e);if(!e)return eb(c).forEach(function(a){a.destroy()}),!1;c[d]=e}a.c=c;return!0}function Ee(a,b){var c=new Bd(a,a.video,a.f,ud(b),a.U);c.A(a.A);return c}
function De(a,b,c){a.va=a.video.playbackRate;a.video.playbackRate=0;Fe(a,c);var d;a.K&&a.K<=c.end&&a.K>=c.start?d=a.K:a.a.a?(d=c.end,a.ea=!0):d=c.start;E(a.i,a.video,"seeking",a.$a.bind(a));a.video.currentTime!=d&&(a.video.currentTime=d,a.j=d);Ge(a,c.start,c.end);c=[];for(var e in a.c){d=a.c[e];c.push(d.Ia(a.R));E(a.i,d,"ended",a.ab.bind(a));var f=b[e];Xd(a.w,f);d.ia(f,!1)}Promise.all(c).then(a.Pa.bind(a)).catch(I(a,function(a){"destroy"!=a.type&&(a=y(a),this.dispatchEvent(a))}));se(a,a.V)}
k.Pa=function(a){ba(a&&a.length==Object.keys(this.c).length);for(var b=Number.POSITIVE_INFINITY,c=Number.NEGATIVE_INFINITY,d=0;d<a.length;++d)var e=a[d],b=Math.min(b,e),c=Math.max(c,e);a=He(this);for(d=0;d<a.length;++d)rd(a[d],c);Ie(this,a,c);d=jb(this.b).map(function(a){return a.streamInfos}).reduce(function(a,b){return a.concat(b)},[]).map(function(a){var b=[a.segmentIndexSource.create()];a.M&&b.push(a.M.create());return Promise.all(b)});Promise.all(d).then(I(this,function(a){for(var b=0;b<a.length;++b)rd(a[b][0],
c);this.ba=!0;for(var d in this.o)a=this.o[d],b=this.c[d],Xd(this.w,a.Ja),b.ia(a.Ja,a.za,a.Aa);this.o={}})).catch(I(this,function(a){"aborted"!=a.type&&(a=y(a),this.dispatchEvent(a))}))};function Ie(a,b,c){if(b=Be(a,b))Fe(a,b),Ge(a,b.start,b.end);0!=c&&(c=a.video.currentTime+c,a.video.currentTime=c,a.j=c);a.ea&&b&&(a.video.currentTime=b.end);a.video.playbackRate=a.va;a.a.a&&null!=a.a.f&&a.Oa(0);Je(a);a.R.resolve()}
function Fe(a,b){if(a.a.a)isNaN(a.f.duration)&&(a.f.duration=b.end+2592E3);else if(isNaN(a.f.duration)||b.end>a.f.duration){a.f.duration=b.end;for(var c=0;c<a.f.sourceBuffers.length;++c)a.f.sourceBuffers[c].appendWindowEnd=b.end}}k.cb=function(){this.B=null;Je(this);var a=Be(this,He(this));a&&(this.a.a&&this.sa!=a.W&&(this.sa=a.W,null!=this.P&&(window.clearTimeout(this.P),this.P=null)),Ge(this,a.start,a.end),this.video.paused||Ke(this,this.video.currentTime,a.start,a.end))};
function Ge(a,b,c){b=x({type:"seekrangechanged",bubbles:!0,start:b,end:c});a.dispatchEvent(b)}k.$a=function(){var a=this.video.currentTime;if(null!=this.j){if(a>=this.j-.01&&a<=this.j+.01){this.j=null;return}this.j=null}var b=Be(this,He(this));if(b){var c=b.end;(b=Ke(this,a,b.start,c))||(a<=c+.01?b=!1:(this.video.currentTime=c,b=!0));if(!b)for(var d in this.c)this.c[d].Ea()}};
function Ke(a,b,c,d){if(b>=c-.01)return!1;b=0;if(a.a.a){b=.5;for(var e in a.c)if(!a.c[e].Fa(c+b)){b=a.a.b;break}}a.video.currentTime=Math.min(c+b,d);return!0}k.ab=function(){if(!this.a.a){for(var a in this.c)if(!this.c[a].Ca())return;this.P=null;this.f.endOfStream()}};k.kb=function(){var a=this.w,b=this.U.getBandwidth();a.estimatedBandwidth=b;a.bandwidthHistory.push(new Zd(b))};function He(a){return eb(a.c).map(function(a){return a.Ba()}).filter(function(a){return null!=a})}
function Be(a,b){for(var c=0,d=Number.POSITIVE_INFINITY,e=Number.POSITIVE_INFINITY,f=0;f<b.length;++f){var g;g=b[f];g=0<g.length()?{start:pd(g).startTime,end:g.W().endTime}:{start:0,end:0};c=Math.max(c,g.start);null!=g.end&&(d=Math.min(d,g.end));b[f].length()&&(e=Math.min(e,b[f].W().endTime))}if(d==Number.POSITIVE_INFINITY)if(d=a.a.periodInfos[0],d.a)d=(d.start||0)+d.a;else return null;a.a.a&&(d=Math.max(d-a.a.b,c));return c>d?null:{start:c,end:d,W:e}}
function Je(a){a.a.a&&(a.B=window.setTimeout(a.cb.bind(a),1E3))}function ve(a){for(var b in a.c)a.c[b].A(a.A)};function Z(a,b,c,d){c||(c=new G);d||(d=new X);Y.call(this,null,c,d);this.ua=a;this.wa=b;this.Y=[];this.ca=[];this.da=[];this.S=null}p(Z,Y);m("shaka.player.DashVideoSource",Z);Z.prototype.La=function(){return this.ua};Z.prototype.getUrl=Z.prototype.La;Z.prototype.Ka=function(){return this.a};Z.prototype.getManifestInfo=Z.prototype.Ka;Z.prototype.Ma=function(a,b,c){this.Y.push(a);this.ca.push(b||"");this.da.push(c||"")};Z.prototype.addExternalCaptions=Z.prototype.Ma;
Z.prototype.Na=function(a){this.S=a};Z.prototype.setNetworkCallback=Z.prototype.Na;Z.prototype.destroy=function(){this.S=this.wa=null;Y.prototype.destroy.call(this)};
Z.prototype.Z=function(){var a=new J(this.S,[new K(this.ua)]);return jd(new id(a,this.ta)).then(I(this,function(a){for(var c=0;c<this.Y.length;c++){var d=a,e=this.Y[c],f=this.ca[c],g=this.da[c];if(0!==d.a.length){var h=new Ac;h.contentType="text";h.lang=f||"en";h.c=!0;f=new Dc;f.bandwidth=0;f.b=g||"text/vtt";f.l=[new K(e)];h.a.push(f);d.a[0].a.push(h);Wc(d.a[0])}}if("dynamic"==a.type)return a=Error("Live manifest support not enabled."),a.type="app",Promise.reject(a);c=new Md(this.wa);d=this.S;e=(Date.now()+
Qa)/1E3;for(g=0;g<a.a.length;++g)for(h=a.a[g],f=0;f<h.a.length;++f){var l=h.a[f];if("text"!=l.contentType)for(var n=0;n<l.a.length;++n){var r=l.a[n],t=0,t=t+(r.c?1:0),t=t+(r.f?1:0),t=t+(r.g?1:0);0==t?(l.a.splice(n,1),--n):1!=t&&(r.c?(r.f=null,r.g=null):r.f&&(r.g=null))}}Nd(a);for(g=0;g<a.a.length;++g)for(h=a.a[g],f=0;f<h.a.length;++f){n=l=h.a[f];r=null;for(t=0;t<n.a.length;++t){var B=n.a[t].b||"";r?B!=r&&(n.a.splice(t,1),--t):r=B}0==l.a.length&&(h.a.splice(f,1),--f)}"dynamic"==a.type&&null==a.c&&
(a.c=e);e=new Ad;"dynamic"==a.type&&(e.a=!0,e.f=a.f,e.g=new J(d,a.j||a.url),e.c=a.c);e.b=a.g||5;for(g=0;g<a.a.length;++g){h=a.a[g];if(null==h.start)break;h=Od(c,h,d);e.periodInfos.push(h)}this.a=e;return Y.prototype.Z.call(this)}))};}.bind(g,this))();
if (typeof(module)!="undefined"&&module.exports)module.exports=g.shaka;
else if (typeof(define)!="undefined" && define.amd)define(function(){return g.shaka});
else this.shaka=g.shaka;
})();

