(function(){var g={};
(function(window){var k,aa=this;function m(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function p(a,b){function c(){}c.prototype=b.prototype;a.ob=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.mb=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};/*

 Copyright 2015 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function ba(){};function ca(a){var b=console[a];b?b.bind||(console[a]=function(){b.apply(console,arguments)}):console[a]=function(){}}ca("error");ca("warn");ca("info");ca("log");ca("debug");function da(a){ea[a]={ea:fa(),end:NaN}}function ga(a){if(a=ea[a])a.end=fa()}function ha(a){return(a=ea[a])&&a.end?a.end-a.ea:NaN}var fa=window.performance&&window.performance.now?window.performance.now.bind(window.performance):Date.now,ea={};function ia(a,b,c){this.id=a;this.bandwidth=b||0;this.lang=c||"unknown";this.active=!1}m("shaka.player.AudioTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0});function ja(){this.minBandwidth=this.maxBandwidth=this.maxWidth=this.minHeight=this.maxHeight=null}ja.prototype.clone=function(){var a=new ja;a.maxHeight=this.maxHeight;a.minHeight=this.minHeight;a.maxWidth=this.maxWidth;a.maxBandwidth=this.maxBandwidth;a.minBandwidth=this.minBandwidth;return a};function q(){this.fontSize="100%";this.fontColor=ka;this.fontOpacity=la;this.backgroundColor=ma;this.backgroundOpacity=la;this.fontEdge=na}m("shaka.player.TextStyle",q);q.prototype.a=function(){var a=window.localStorage.getItem("ShakaPlayerTextStyle");if(a){var b;try{b=JSON.parse(a)}catch(c){return}if(b&&"object"==typeof b){var a=b,d;for(d in a)d in this&&(this[d]=a[d])}}};q.prototype.load=q.prototype.a;q.prototype.b=function(){window.localStorage.setItem("ShakaPlayerTextStyle",JSON.stringify(this))};
q.prototype.store=q.prototype.b;function oa(a){var b=[];b.push("font-size: "+a.fontSize);b.push("color: "+pa(a.fontColor,a.fontOpacity));b.push("background-color: "+pa(a.backgroundColor,a.backgroundOpacity));for(var c=[],d=0;d<a.fontEdge.length;++d){var e=a.fontEdge[d].slice(3,6);c.push(pa(a.fontEdge[d].slice(0,3),a.fontOpacity)+" "+e.join("px ")+"px")}b.push("text-shadow: "+c.join(","));return b.join("; ")}function pa(a,b){return"rgba("+a.concat(b).join(",")+")"}var ka=[255,255,255],ma=[0,0,0];
q.StandardColors={WHITE:ka,BLACK:ma,RED:[255,0,0],GREEN:[0,255,0],BLUE:[0,0,255],YELLOW:[255,255,0],MAGENTA:[255,0,255],CYAN:[0,255,255]};var la=1;q.StandardOpacities={OPAQUE:la,SEMI_HIGH:.75,SEMI_LOW:.25,TRANSPARENT:0};var na=[];
q.EdgeStyles={NONE:na,RAISED:[[34,34,34,1,1,0],[34,34,34,2,2,0],[34,34,34,3,3,0]],DEPRESSED:[[204,204,204,1,1,0],[204,204,204,0,1,0],[34,34,34,-1,-1,0],[34,34,34,0,-1,0]],UNIFORM:[[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4]],DROP:[[34,34,34,2,2,3],[34,34,34,2,2,4],[34,34,34,2,2,5]]};function qa(a,b){this.id=a;this.lang=b||"unknown";this.enabled=this.active=!1}m("shaka.player.TextTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:0});function ra(a,b,c,d){this.id=a;this.bandwidth=b||0;this.width=c||0;this.height=d||0;this.active=!1}function sa(a,b){var c=a.width*a.height,d=b.width*b.height;return c<d?-1:c>d?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0}m("shaka.player.VideoTrack.compare",sa);function ta(){var a="CustomEvent"in window;if(a)try{new CustomEvent("")}catch(b){a=!1}a||(window.CustomEvent=ua)}m("shaka.polyfill.CustomEvent.install",ta);function ua(a,b){var c=document.createEvent("CustomEvent"),d=b||{bubbles:!1,cancelable:!1,detail:null};c.initCustomEvent(a,!!d.bubbles,!!d.cancelable,d.detail);return c};function va(){var a=Element.prototype;a.requestFullscreen=a.requestFullscreen||a.mozRequestFullScreen||a.msRequestFullscreen||a.webkitRequestFullscreen;a=Document.prototype;a.exitFullscreen=a.exitFullscreen||a.mozCancelFullScreen||a.msExitFullscreen||a.webkitExitFullscreen;"fullscreenElement"in document||Object.defineProperty(document,"fullscreenElement",{get:function(){return document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement}});document.addEventListener("webkitfullscreenchange",
wa);document.addEventListener("webkitfullscreenerror",wa);document.addEventListener("mozfullscreenchange",wa);document.addEventListener("mozfullscreenerror",wa);document.addEventListener("MSFullscreenChange",wa);document.addEventListener("MSFullscreenError",wa)}m("shaka.polyfill.Fullscreen.install",va);function wa(a){var b=a.type.replace(/^(webkit|moz|MS)/,"").toLowerCase(),b=new Event(b,a);a.target.dispatchEvent(b)};function xa(){return Promise.reject(Error("The key system specified is not supported."))}function ya(a){return null==a?Promise.resolve():Promise.reject(Error("MediaKeys not supported."))}function za(){throw new TypeError("Illegal constructor.");}za.prototype.createSession=function(){};za.prototype.setServerCertificate=function(){};function Aa(){throw new TypeError("Illegal constructor.");}Aa.prototype.getConfiguration=function(){};Aa.prototype.createMediaKeys=function(){};function u(a){this.c=[];this.b=[];this.O=Ba;if(a)try{a(this.I.bind(this),this.a.bind(this))}catch(b){this.a(b)}}var Ba=0;function Ca(){window.Promise||(window.Promise=u,window.Promise.resolve=Da,window.Promise.reject=Ea,window.Promise.all=Fa,window.Promise.race=Ga,window.setImmediate?(Ha=function(a){return window.setImmediate(a)},Ia=function(a){return window.clearImmediate(a)}):(Ha=function(a){return window.setTimeout(a,0)},Ia=function(a){return window.clearTimeout(a)}))}
m("shaka.polyfill.Promise.install",Ca);function Da(a){var b=new u;b.I(a);return b}function Ea(a){var b=new u;b.a(a);return b}function Fa(a){function b(a,b,c){a.O==Ba&&(e[b]=c,d++,d==e.length&&a.I(e))}var c=new u;if(!a.length)return c.I([]),c;for(var d=0,e=Array(a.length),f=c.a.bind(c),g=0;g<a.length;++g)a[g]&&a[g].then?a[g].then(b.bind(null,c,g),f):b(c,g,a[g]);return c}function Ga(a){for(var b=new u,c=b.I.bind(b),d=b.a.bind(b),e=0;e<a.length;++e)a[e]&&a[e].then?a[e].then(c,d):c(a[e]);return b}
u.prototype.then=function(a,b){var c=new u;switch(this.O){case 1:Ja(this,c,a);break;case 2:Ja(this,c,b);break;case Ba:this.c.push({na:c,ka:a}),this.b.push({na:c,ka:b})}return c};u.prototype.then=u.prototype.then;u.prototype.catch=function(a){return this.then(void 0,a)};u.prototype["catch"]=u.prototype.catch;u.prototype.I=function(a){if(this.O==Ba){this.ia=a;this.O=1;for(a=0;a<this.c.length;++a)Ja(this,this.c[a].na,this.c[a].ka);this.c=[];this.b=[]}};
u.prototype.a=function(a){if(this.O==Ba){this.ia=a;this.O=2;for(a=0;a<this.b.length;++a)Ja(this,this.b[a].na,this.b[a].ka);this.c=[];this.b=[]}};function Ja(a,b,c){Ka.push(function(){if(c&&"function"==typeof c){try{var a=c(this.ia)}catch(e){b.a(e);return}a instanceof u?a==b?b.a(new TypeError("Chaining cycle detected")):a.then(b.I.bind(b),b.a.bind(b)):b.I(a)}else 1==this.O?b.I(this.ia):b.a(this.ia)}.bind(a));null==La&&(La=Ha(Ma))}
function Ma(){for(;Ka.length;){null!=La&&(Ia(La),La=null);var a=Ka;Ka=[];for(var b=0;b<a.length;++b)a[b]()}}function Ha(){return 0}function Ia(){}var La=null,Ka=[];function Na(){var a=HTMLVideoElement.prototype;!a.getVideoPlaybackQuality&&"webkitDroppedFrameCount"in a&&(a.getVideoPlaybackQuality=Oa)}m("shaka.polyfill.VideoPlaybackQuality.install",Na);function Oa(){return{droppedVideoFrames:this.webkitDroppedFrameCount,totalVideoFrames:this.webkitDecodedFrameCount,corruptedVideoFrames:0,creationTime:NaN,totalFrameDelay:0}};function Pa(a,b){for(var c=[],d=0;d<a.length;++d){for(var e=!1,f=0;f<c.length&&!(e=b?b(a[d],c[f]):a[d]===c[f]);++f);e||c.push(a[d])}return c};var Qa=0;function Ra(a){this.b=a;this.c=0==Sa;this.a=0}var Sa=1;function Ta(a){var b=a.b.getUint8(a.a);a.a+=1;return b}function v(a){var b=a.b.getUint32(a.a,a.c);a.a+=4;return b}function Ua(a){var b,c;a.c?(b=a.b.getUint32(a.a,!0),c=a.b.getUint32(a.a+4,!0)):(c=a.b.getUint32(a.a,!1),b=a.b.getUint32(a.a+4,!1));if(2097151<c)throw new RangeError("DataViewReader: Overflow reading 64-bit value.");a.a+=8;return c*Math.pow(2,32)+b}
function Va(a){if(a.a+16>a.b.byteLength)throw new RangeError("DataViewReader: Read past end of DataView.");var b=new Uint8Array(a.b.buffer,a.a,16);a.a+=16;return b}function w(a,b){if(a.a+b>a.b.byteLength)throw new RangeError("DataViewReader: Skip past end of DataView.");a.a+=b};var Wa={"output-restricted":"The required output protection is not available.","output-not-allowed":"The required output protection is not available.",expired:"The decryption key has expired.","internal-error":"The key system has encountered an unspecified error."};function Xa(a){this.c=Math.exp(Math.log(.5)/a);this.a=this.b=0}Xa.prototype.sample=function(a,b){var c=Math.pow(this.c,a);this.b=b*(1-c)+c*this.b;this.a+=a};function Ya(a){return a.b/(1-Math.pow(a.c,a.a))};function x(a){var b=new CustomEvent(a.type,{detail:a.detail,bubbles:!!a.bubbles}),c;for(c in a)c in b||(b[c]=a[c]);return b}function y(a){return new CustomEvent("error",{detail:a,bubbles:!0})};function Za(a,b,c){$a(b);$a(c);return c==b||a>=ab&&c==b.split("-")[0]||a>=bb&&c.split("-")[0]==b.split("-")[0]?!0:!1}var ab=1,bb=2;function $a(a){a=a.toLowerCase().split("-");var b=cb[a[0]];b&&(a[0]=b);return a.join("-")}
var cb={aar:"aa",abk:"ab",afr:"af",aka:"ak",alb:"sq",amh:"am",ara:"ar",arg:"an",arm:"hy",asm:"as",ava:"av",ave:"ae",aym:"ay",aze:"az",bak:"ba",bam:"bm",baq:"eu",bel:"be",ben:"bn",bih:"bh",bis:"bi",bod:"bo",bos:"bs",bre:"br",bul:"bg",bur:"my",cat:"ca",ces:"cs",cha:"ch",che:"ce",chi:"zh",chu:"cu",chv:"cv",cor:"kw",cos:"co",cre:"cr",cym:"cy",cze:"cs",dan:"da",deu:"de",div:"dv",dut:"nl",dzo:"dz",ell:"el",eng:"en",epo:"eo",est:"et",eus:"eu",ewe:"ee",fao:"fo",fas:"fa",fij:"fj",fin:"fi",fra:"fr",fre:"fr",
fry:"fy",ful:"ff",geo:"ka",ger:"de",gla:"gd",gle:"ga",glg:"gl",glv:"gv",gre:"el",grn:"gn",guj:"gu",hat:"ht",hau:"ha",heb:"he",her:"hz",hin:"hi",hmo:"ho",hrv:"hr",hun:"hu",hye:"hy",ibo:"ig",ice:"is",ido:"io",iii:"ii",iku:"iu",ile:"ie",ina:"ia",ind:"id",ipk:"ik",isl:"is",ita:"it",jav:"jv",jpn:"ja",kal:"kl",kan:"kn",kas:"ks",kat:"ka",kau:"kr",kaz:"kk",khm:"km",kik:"ki",kin:"rw",kir:"ky",kom:"kv",kon:"kg",kor:"ko",kua:"kj",kur:"ku",lao:"lo",lat:"la",lav:"lv",lim:"li",lin:"ln",lit:"lt",ltz:"lb",lub:"lu",
lug:"lg",mac:"mk",mah:"mh",mal:"ml",mao:"mi",mar:"mr",may:"ms",mkd:"mk",mlg:"mg",mlt:"mt",mon:"mn",mri:"mi",msa:"ms",mya:"my",nau:"na",nav:"nv",nbl:"nr",nde:"nd",ndo:"ng",nep:"ne",nld:"nl",nno:"nn",nob:"nb",nor:"no",nya:"ny",oci:"oc",oji:"oj",ori:"or",orm:"om",oss:"os",pan:"pa",per:"fa",pli:"pi",pol:"pl",por:"pt",pus:"ps",que:"qu",roh:"rm",ron:"ro",rum:"ro",run:"rn",rus:"ru",sag:"sg",san:"sa",sin:"si",slk:"sk",slo:"sk",slv:"sl",sme:"se",smo:"sm",sna:"sn",snd:"sd",som:"so",sot:"st",spa:"es",sqi:"sq",
srd:"sc",srp:"sr",ssw:"ss",sun:"su",swa:"sw",swe:"sv",tah:"ty",tam:"ta",tat:"tt",tel:"te",tgk:"tg",tgl:"tl",tha:"th",tib:"bo",tir:"ti",ton:"to",tsn:"tn",tso:"ts",tuk:"tk",tur:"tr",twi:"tw",uig:"ug",ukr:"uk",urd:"ur",uzb:"uz",ven:"ve",vie:"vi",vol:"vo",wel:"cy",wln:"wa",wol:"wo",xho:"xh",yid:"yi",yor:"yo",zha:"za",zho:"zh",zul:"zu"};function db(a){return Object.keys(a).map(function(b){return a[b]})}function eb(a,b){return fb(a,b,"boolean")}function gb(a,b){var c=fb(a,b,"number");if(null==c)return null;if(isNaN(c)||c==Number.NEGATIVE_INFINITY||c==Number.POSITIVE_INFINITY)throw new RangeError("'"+b+"' must be finite.");if(0>c)throw new RangeError("'"+b+"' must be >= 0");return c}function z(a,b){return fb(a,b,"string")}
function fb(a,b,c){a=a[b];if(null==a)return null;if(typeof a!=c)throw new TypeError("'"+b+"' must be a "+c+".");return a}function A(a,b,c){a=a[b];if(null==a)return null;if(!(a instanceof c))throw new TypeError("'"+b+"' must be an instance of "+c.name+".");return a};function C(){this.a={}}C.prototype.push=function(a,b){this.a.hasOwnProperty(a)?this.a[a].push(b):this.a[a]=[b]};C.prototype.set=function(a,b){this.a[a]=b};C.prototype.get=function(a){return(a=this.a[a])?a.slice():null};function hb(a){var b=[],c;for(c in a.a)b.push.apply(b,a.a[c]);return b}function jb(a,b,c){if(a=a.a[b])for(b=0;b<a.length;++b)a[b]==c&&(a.splice(b,1),--b)}function kb(a){var b=[],c;for(c in a.a)b.push(c);return b};function D(){this.a=new C}D.prototype.destroy=function(){lb(this);this.a=null};function E(a,b,c,d){b=new mb(b,c,d);a.a.push(c,b)}D.prototype.ba=function(a,b){for(var c=this.a.get(b)||[],d=0;d<c.length;++d){var e=c[d];e.target==a&&(e.ba(),jb(this.a,b,e))}};function lb(a){for(var b=hb(a.a),c=0;c<b.length;++c)b[c].ba();a.a.a={}}function mb(a,b,c){this.target=a;this.type=b;this.a=c;this.target.addEventListener(b,c,!1)}
mb.prototype.ba=function(){this.target&&(this.target.removeEventListener(this.type,this.a,!1),this.a=this.target=null)};function F(a){this.ja=new C;this.v=a}m("shaka.util.FakeEventTarget",F);F.prototype.addEventListener=function(a,b,c){c||this.ja.push(a,b)};F.prototype.removeEventListener=function(a,b,c){c||jb(this.ja,a,b)};
F.prototype.dispatchEvent=function(a){a.hasOwnProperty("srcElement")||(delete a.srcElement,Object.defineProperty(a,"srcElement",{get:function(){return null}}));if(a.hasOwnProperty("target"))a.target=this;else{delete a.target;var b=this;Object.defineProperty(a,"target",{get:function(){return b},set:function(a){b=a}})}if(a.hasOwnProperty("currentTarget"))a.currentTarget=null;else{delete a.currentTarget;var c=null;Object.defineProperty(a,"currentTarget",{get:function(){return c},set:function(a){c=a}})}return nb(this,
a)};function nb(a,b){b.currentTarget=a;for(var c=a.ja.get(b.type)||[],d=0;d<c.length;++d){var e=c[d];try{e.handleEvent?e.handleEvent(b):e.call(a,b)}catch(f){}}a.v&&b.bubbles&&nb(a.v,b);return b.defaultPrevented};function G(){F.call(this,null);this.a=new Xa(3);this.c=new Xa(10);this.b=0}p(G,F);m("shaka.util.EWMABandwidthEstimator",G);G.prototype.sample=function(a,b){if(!(65536>b)){a=Math.max(a,50);var c=8E3*b/a,d=a/1E3;this.a.sample(d,c);this.c.sample(d,c);this.dispatchEvent(x({type:"bandwidth"}));this.b=Date.now()}};G.prototype.getBandwidth=function(){return.5>this.a.a?5E5:Math.min(Ya(this.a),Ya(this.c))};G.prototype.getDataAge=function(){return(Date.now()-this.b)/1E3};G.prototype.supportsCaching=function(){return!1};function H(){var a,b,c=new Promise(function(c,e){a=c;b=e});c.resolve=a;c.reject=b;c.destroy=H.prototype.destroy;return c}H.prototype.destroy=function(){this.catch(function(){});var a=Error("Destroyed!");a.type="destroy";this.reject(a)};function ob(a){a.split("").reduce(function(a,c,d){return a+(d&&0==d%4?" "+c:c)})};function pb(){this.g=new H;this.f=!1;this.a=null;this.b=[];this.c=null}function qb(a,b){if(a.f)throw Error("Cannot append to a running task!");a.b.push(b)}pb.prototype.start=function(){if(this.f)throw Error("Task already started!");this.f=!0;this.b.unshift(function(){});rb(this,void 0)};pb.prototype.end=function(){this.b.splice(1)};
function rb(a,b){var c=a.b[0](b),d;c?(d=c[0],a.c=c[1]):(d=Promise.resolve(),a.c=null);d.then(I(a,function(a){this.a?(this.b=[],this.c=null,sb(this)):(this.b.shift(),this.b.length?rb(this,a):(this.g.resolve(a),this.c=null))})).catch(I(a,function(a){this.b=[];this.c=null;this.a?sb(this):this.g.reject(a)}))}function sb(a){var b=Error("Task aborted.");b.type="aborted";a.g.reject(b);window.setTimeout(function(){this.a.resolve();this.a=null}.bind(a),5)};function I(a,b){return b.bind(a)};function tb(a,b,c){MediaSource.isTypeSupported(b);b=a.addSourceBuffer(b);this.h=a;this.c=b;this.l=c;this.i=new D;this.s=null;this.b=[];this.o=0;this.f=this.a=null;this.v=0;E(this.i,this.c,"updateend",this.u.bind(this))}var ub=1/60;tb.prototype.destroy=function(){vb(this).catch(function(){});this.f&&this.f.destroy();this.b=this.a=this.f=null;this.i.destroy();this.h=this.c=this.i=null};
function wb(a,b){for(var c=a.c.buffered,d=0;d<c.length;++d){var e=c.start(d)-ub,f=c.end(d)+ub;if(b>=e&&b<=f)return c.end(d)-b}return 0}
tb.prototype.fetch=function(a,b,c){if(this.a)return b=Error("Cannot fetch ("+this.j+"): previous operation not complete."),b.type="stream",Promise.reject(b);this.a=new pb;b!=this.c.timestampOffset&&(this.c.timestampOffset=b);c&&qb(this.a,function(){return[xb(this,c),this.g.bind(this)]}.bind(this));qb(this.a,function(){var b=a.endTime?a.endTime-a.startTime:1,c=new yb;c.a=3;c.g=1E3*b;c.c=1E3*this.v;c.h=this.s;return[a.url.fetch(c,this.l),J.prototype.c.bind(a.url)]}.bind(this));qb(this.a,I(this,function(a){this.l.getBandwidth();
return[xb(this,a),this.g.bind(this)]}));var d=0==this.c.buffered.length&&0==this.b.length,e=null;qb(this.a,function(){if(0==this.c.buffered.length){var b=Error("Failed to buffer segment ("+this.j+").");b.type="stream";return[Promise.reject(b)]}d&&(b=a.startTime,e=this.c.buffered.start(0)-b);b=zb(this.b,a.startTime);0<=b?this.b.splice(b+1,0,a):this.b.push(a)}.bind(this));return Ab(this).then(function(){return Promise.resolve(e)}.bind(this))};
function Bb(a){if(a.a)return a=Error("Cannot clear ("+a.j+"): previous operation not complete."),a.type="stream",Promise.reject(a);a.a=new pb;qb(a.a,function(){var a;a:if(0==this.c.buffered.length)a=Promise.resolve();else{try{this.c.remove(0,this.h.duration)}catch(c){a=Promise.reject(c);break a}this.b=[];a=this.f=new H}return[a,this.g.bind(this)]}.bind(a));return Ab(a)}
function Cb(a,b){if(a.a){var c=Error("Cannot clearAfter ("+a.j+"): previous operation not complete.");c.type="stream";return Promise.reject(c)}a.a=new pb;qb(a.a,function(){return[Db(this,b),this.g.bind(this)]}.bind(a));return Ab(a)}function vb(a){a.a?(a=a.a,a.a?a=a.a:a.f?(a.c&&a.c(),a.a=new H,a=a.a):(a.f=!0,a=Promise.resolve())):a=Promise.resolve();return a}function Ab(a){a.a.start();return a.a.g.then(I(a,function(){this.a=null})).catch(I(a,function(a){this.a=null;return Promise.reject(a)}))}
function xb(a,b){try{a.c.appendBuffer(b)}catch(c){return Promise.reject(c)}a.f=new H;return a.f}function Db(a,b){if(0==a.c.buffered.length)return Promise.resolve();var c=zb(a.b,b);if(-1==c||c==a.b.length-1)return Promise.resolve();try{a.c.remove(a.b[c+1].startTime,a.h.duration)}catch(d){return Promise.reject(d)}a.b=a.b.slice(0,c+1);a.f=new H;return a.f}tb.prototype.g=function(){this.f&&"open"==this.h.readyState&&this.c.abort()};tb.prototype.u=function(){this.f&&(this.f.resolve(),this.f=null)};function Eb(a){return String.fromCharCode.apply(null,a)}m("shaka.util.Uint8ArrayUtils.toString",Eb);function Fb(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;++c)b[c]=a.charCodeAt(c);return b}m("shaka.util.Uint8ArrayUtils.fromString",Fb);m("shaka.util.Uint8ArrayUtils.toBase64",function(a,b){var c=void 0==b?!0:b,d=window.btoa(Eb(a)).replace(/\+/g,"-").replace(/\//g,"_");return c?d:d.replace(/=*$/,"")});function Gb(a){return Fb(window.atob(a.replace(/-/g,"+").replace(/_/g,"/")))}
m("shaka.util.Uint8ArrayUtils.fromBase64",Gb);m("shaka.util.Uint8ArrayUtils.fromHex",function(a){for(var b=new Uint8Array(a.length/2),c=0;c<a.length;c+=2)b[c/2]=window.parseInt(a.substr(c,2),16);return b});function Hb(a){for(var b="",c=0;c<a.length;++c){var d=a[c].toString(16);1==d.length&&(d="0"+d);b+=d}return b}m("shaka.util.Uint8ArrayUtils.toHex",Hb);function Ib(a,b){if(!a&&!b)return!0;if(!a||!b||a.length!=b.length)return!1;for(var c=0;c<a.length;++c)if(a[c]!=b[c])return!1;return!0};function Jb(){this.h=this.a="";this.withCredentials=!1;this.v=this.l=null;this.i=this.g=!1;this.j=this.f="";this.c=null;this.b=[]}function Kb(a,b){var c=new Jb;c.a=a.a;c.h=a.h;c.withCredentials=a.withCredentials;c.l=a.l;c.v=a.v;c.g=a.g;c.i=a.i;c.f=a.f;c.j=a.j;c.c=a.c?new Uint8Array(a.c.buffer):null;Lb(c,a.b);Lb(c,b.b);return c}function Lb(a,b){var c=a.b.concat(b.map(function(a){return{initData:new Uint8Array(a.initData.buffer),initDataType:a.initDataType}}));a.b=Pa(c,Mb)}
function Mb(a,b){return a.initDataType==b.initDataType&&Ib(a.initData,b.initData)};function Nb(a,b){try{var c=new Ob(a,b);return Promise.resolve(c)}catch(d){return Promise.reject(d)}}function Pb(a){var b=this.mediaKeys;b&&b!=a&&Qb(b,null);delete this.mediaKeys;(this.mediaKeys=a)&&Qb(a,this);return Promise.resolve()}
function Ob(a,b){this.a=this.keySystem=a;var c=!0;"org.w3.clearkey"==a&&(this.a="webkit-org.w3.clearkey",c=!1);var d=!1,e;e=document.getElementsByTagName("video");e=e.length?e[0]:document.createElement("video");for(var f=0;f<b.length;++f){var g=b[f],h={audioCapabilities:[],videoCapabilities:[],persistentState:"optional",distinctiveIdentifier:"optional",initDataTypes:g.initDataTypes,sessionTypes:["temporary"]},l=!1;if(g.audioCapabilities)for(var n=0;n<g.audioCapabilities.length;++n){var r=g.audioCapabilities[n];
r.contentType&&(l=!0,e.canPlayType(r.contentType.split(";")[0],this.a)&&(h.audioCapabilities.push(r),d=!0))}if(g.videoCapabilities)for(n=0;n<g.videoCapabilities.length;++n)r=g.videoCapabilities[n],r.contentType&&(l=!0,e.canPlayType(r.contentType,this.a)&&(h.videoCapabilities.push(r),d=!0));l||(d=e.canPlayType("video/mp4",this.a)||e.canPlayType("video/webm",this.a));"required"==g.persistentState&&(c?(h.persistentState="required",h.sessionTypes=["persistent-license"]):d=!1);if(d){this.b=h;return}}c=
"Unsupported keySystem";if("org.w3.clearkey"==a||"com.widevine.alpha"==a)c="None of the requested configurations were supported.";c=Error(c);c.name="NotSupportedError";c.code=DOMException.NOT_SUPPORTED_ERR;throw c;}Ob.prototype.createMediaKeys=function(){var a=new Rb(this.a);return Promise.resolve(a)};Ob.prototype.getConfiguration=function(){return this.b};function Rb(a){this.g=a;this.b=null;this.a=new D;this.c=[];this.f={}}
function Qb(a,b){a.b=b;lb(a.a);b&&(E(a.a,b,"webkitneedkey",a.ib.bind(a)),E(a.a,b,"webkitkeymessage",a.hb.bind(a)),E(a.a,b,"webkitkeyadded",a.fb.bind(a)),E(a.a,b,"webkitkeyerror",a.gb.bind(a)))}k=Rb.prototype;k.createSession=function(a){var b=a||"temporary";if("temporary"!=b&&"persistent-license"!=b)throw new TypeError("Session type "+a+" is unsupported on this platform.");a=this.b||document.createElement("video");a.src||(a.src="about:blank");b=new Sb(a,this.g,b);this.c.push(b);return b};
k.setServerCertificate=function(){return Promise.reject(Error("setServerCertificate not supported on this platform."))};k.ib=function(a){a=x({type:"encrypted",initDataType:"webm",initData:a.initData});this.b.dispatchEvent(a)};k.hb=function(a){var b=Tb(this,a.sessionId);b&&(a=x({type:"message",messageType:void 0==b.keyStatuses.ma()?"licenserequest":"licenserenewal",message:a.message}),b.b&&(b.b.resolve(),b.b=null),b.dispatchEvent(a))};
k.fb=function(a){if(a=Tb(this,a.sessionId))Ub(a,"usable"),a.a&&a.a.resolve(),a.a=null};
k.gb=function(a){var b=Tb(this,a.sessionId);if(b){var c=Error("EME v0.1b key error");c.errorCode=a.errorCode;c.errorCode.systemCode=a.systemCode;!a.sessionId&&b.b?(c.method="generateRequest",45==a.systemCode&&(c.message="Unsupported session type."),b.b.reject(c),b.b=null):a.sessionId&&b.a?(c.method="update",b.a.reject(c),b.a=null):(c=a.systemCode,a.errorCode.code==MediaKeyError.MEDIA_KEYERR_OUTPUT?Ub(b,"output-restricted"):1==c?Ub(b,"expired"):Ub(b,"internal-error"))}};
function Tb(a,b){var c=a.f[b];return c?c:(c=a.c.shift())?(c.sessionId=b,a.f[b]=c):null}function Sb(a,b,c){F.call(this,null);this.f=a;this.h=!1;this.a=this.b=null;this.c=b;this.g=c;this.sessionId="";this.expiration=NaN;this.closed=new H;this.keyStatuses=new Vb}p(Sb,F);
function Wb(a,b,c){if(a.h)return Promise.reject(Error("The session is already initialized."));a.h=!0;var d;try{if("persistent-license"==a.g)if(c)d=Fb("LOAD_SESSION|"+c);else{var e=new Uint8Array(b);d=Fb("PERSISTENT|"+Eb(e))}else d=new Uint8Array(b)}catch(f){return Promise.reject(f)}a.b=new H;try{a.f.webkitGenerateKeyRequest(a.c,d)}catch(g){if("InvalidStateError"!=g.name)return a.b=null,Promise.reject(g);setTimeout(function(){try{this.f.webkitGenerateKeyRequest(this.c,d)}catch(a){this.b.reject(a),
this.b=null}}.bind(a),10)}return a.b}k=Sb.prototype;k.qa=function(a,b){if(this.a)this.a.then(this.qa.bind(this,a,b)).catch(this.qa.bind(this,a,b));else{this.a=a;var c,d;"webkit-org.w3.clearkey"==this.c?(c=Eb(new Uint8Array(b)),d=JSON.parse(c),"oct"!=d.keys[0].kty&&(this.a.reject(Error("Response is not a valid JSON Web Key Set.")),this.a=null),c=Gb(d.keys[0].k),d=Gb(d.keys[0].kid)):(c=new Uint8Array(b),d=null);try{this.f.webkitAddKey(this.c,c,d,this.sessionId)}catch(e){this.a.reject(e),this.a=null}}};
function Ub(a,b){a.keyStatuses.pa(b);var c=x({type:"keystatuseschange"});a.dispatchEvent(c)}k.generateRequest=function(a,b){return Wb(this,b,null)};k.load=function(a){return"persistent-license"==this.g?Wb(this,null,a):Promise.reject(Error("Not a persistent session."))};k.update=function(a){var b=new H;this.qa(b,a);return b};
k.close=function(){if("persistent-license"!=this.g){if(!this.sessionId)return this.closed.reject(Error("The session is not callable.")),this.closed;this.f.webkitCancelKeyRequest(this.c,this.sessionId)}this.closed.resolve();return this.closed};k.remove=function(){return"persistent-license"!=this.g?Promise.reject(Error("Not a persistent session.")):this.close()};function Vb(){this.size=0;this.a=void 0}var Xb;k=Vb.prototype;k.pa=function(a){this.size=void 0==a?0:1;this.a=a};k.ma=function(){return this.a};
k.forEach=function(a){this.a&&a(Xb,this.a)};k.get=function(a){if(this.has(a))return this.a};k.has=function(a){var b=Xb;return this.a&&Ib(new Uint8Array(a),new Uint8Array(b))?!0:!1};function Yb(a){this.systemIds=[];this.cencKeyIds=[];this.a=[];a=new Ra(new DataView(a.buffer));try{for(;a.a<a.b.byteLength;){var b=a.a,c=v(a),d=v(a);1==c?c=Ua(a):0==c&&(c=a.b.byteLength-b);if(1886614376!=d)w(a,c-(a.a-b));else{var e=Ta(a);if(1<e)w(a,c-(a.a-b));else{w(a,3);var f=Hb(Va(a)),g=[];if(0<e)for(var h=v(a),l=0;l<h;++l){var n=Hb(Va(a));g.push(n)}var r=v(a);w(a,r);this.cencKeyIds.push.apply(this.cencKeyIds,g);this.systemIds.push(f);this.a.push({start:b,end:a.a-1});a.a!=b+c&&w(a,c-(a.a-b))}}}}catch(t){}}
;function Zb(a,b){try{var c=new $b(a,b);return Promise.resolve(c)}catch(d){return Promise.reject(d)}}
function $b(a,b){this.keySystem=a;for(var c=!1,d=0;d<b.length;++d){var e=b[d],f={audioCapabilities:[],videoCapabilities:[],persistentState:"optional",distinctiveIdentifier:"optional",initDataTypes:e.initDataTypes,sessionTypes:["temporary"]},g=!1;if(e.audioCapabilities)for(var h=0;h<e.audioCapabilities.length;++h){var l=e.audioCapabilities[h];if(l.contentType){var g=!0,n=l.contentType.split(";")[0];MSMediaKeys.isTypeSupported(this.keySystem,n)&&(f.audioCapabilities.push(l),c=!0)}}if(e.videoCapabilities)for(h=
0;h<e.videoCapabilities.length;++h)l=e.videoCapabilities[h],l.contentType&&(g=!0,n=l.contentType.split(";")[0],MSMediaKeys.isTypeSupported(this.keySystem,n)&&(f.videoCapabilities.push(l),c=!0));g||(c=MSMediaKeys.isTypeSupported(this.keySystem,"video/mp4"));"required"==e.persistentState&&(f.persistentState="required",f.sessionTypes=["persistent-license"]);if(c){this.a=f;return}}c=Error("Unsupported keySystem");c.name="NotSupportedError";c.code=DOMException.NOT_SUPPORTED_ERR;throw c;}
$b.prototype.createMediaKeys=function(){var a=new ac(this.keySystem);return Promise.resolve(a)};$b.prototype.getConfiguration=function(){return this.a};function bc(a){var b=this.mediaKeys;b&&b!=a&&cc(b,null);delete this.mediaKeys;return(this.mediaKeys=a)?cc(a,this):Promise.resolve()}function ac(a){this.a=new MSMediaKeys(a);this.b=new D}ac.prototype.createSession=function(a){if("temporary"!=(a||"temporary"))throw new TypeError("Session type "+a+" is unsupported on this platform.");return new dc(this.a)};
ac.prototype.setServerCertificate=function(){return Promise.reject(Error("setServerCertificate not supported on this platform."))};function cc(a,b){function c(){b.msSetMediaKeys(d.a);b.removeEventListener("loadedmetadata",c)}lb(a.b);if(!b)return Promise.resolve();E(a.b,b,"msneedkey",ec);var d=a;try{return 1<=b.readyState?b.msSetMediaKeys(a.a):b.addEventListener("loadedmetadata",c),Promise.resolve()}catch(e){return Promise.reject(e)}}
function dc(a){F.call(this,null);this.c=null;this.g=a;this.b=this.a=null;this.f=new D;this.sessionId="";this.expiration=NaN;this.closed=new H;this.keyStatuses=new fc}p(dc,F);k=dc.prototype;k.generateRequest=function(a,b){this.a=new H;try{this.c=this.g.createSession("video/mp4",new Uint8Array(b),null),E(this.f,this.c,"mskeymessage",this.Va.bind(this)),E(this.f,this.c,"mskeyadded",this.Ta.bind(this)),E(this.f,this.c,"mskeyerror",this.Ua.bind(this)),gc(this,"status-pending")}catch(c){this.a.reject(c)}return this.a};
k.load=function(){return Promise.reject(Error("MediaKeySession.load not yet supported"))};k.update=function(a){this.b=new H;try{this.c.update(new Uint8Array(a))}catch(b){this.b.reject(b)}return this.b};k.close=function(){try{this.c.close(),this.closed.resolve(),lb(this.f)}catch(a){this.closed.reject(a)}return this.closed};k.remove=function(){return Promise.reject(Error("MediaKeySession.remove is only applicable for persistent licenses, which are not supported on this platform"))};
function ec(a){var b=a.initData;if(b){var c=new Yb(b);if(1>=c.a.length)a=b;else{var d=[];for(a=0;a<c.a.length;a++)d.push(b.subarray(c.a[a].start,c.a[a].end+1));b=Pa(d,hc);for(a=c=0;a<b.length;a++)c+=b[a].length;c=new Uint8Array(c);for(a=d=0;a<b.length;a++)c.set(b[a],d),d+=b[a].length;a=c}}else a=b;a=x({type:"encrypted",initDataType:"cenc",initData:a});this.dispatchEvent(a)}function hc(a,b){return Ib(a,b)}
k.Va=function(a){this.a&&(this.a.resolve(),this.a=null);a=x({type:"message",messageType:void 0==this.keyStatuses.ma()?"licenserequest":"licenserenewal",message:a.message.buffer});this.dispatchEvent(a)};k.Ta=function(){this.a?(this.a.resolve(),this.a=null):this.b&&(gc(this,"usable"),this.b.resolve(),this.b=null)};
k.Ua=function(){var a=Error("EME v20140218 key error");a.errorCode=this.c.error;if(null!=this.a)this.a.reject(a),this.a=null;else if(null!=this.b)this.b.reject(a),this.b=null;else switch(this.c.error.code){case MSMediaKeyError.MS_MEDIA_KEYERR_OUTPUT:case MSMediaKeyError.MS_MEDIA_KEYERR_HARDWARECHANGE:gc(this,"output-not-allowed");default:gc(this,"internal-error")}};function gc(a,b){a.keyStatuses.pa(b);var c=x({type:"keystatuseschange"});a.dispatchEvent(c)}function fc(){this.size=0;this.a=void 0}var ic;
k=fc.prototype;k.pa=function(a){this.size=void 0==a?0:1;this.a=a};k.ma=function(){return this.a};k.forEach=function(a){this.a&&a(ic,this.a)};k.get=function(a){if(this.has(a))return this.a};k.has=function(a){var b=ic;return this.a&&Ib(new Uint8Array(a),new Uint8Array(b))?!0:!1};function jc(){Navigator.prototype.requestMediaKeySystemAccess&&MediaKeySystemAccess.prototype.getConfiguration||(HTMLMediaElement.prototype.webkitGenerateKeyRequest?(Xb=(new Uint8Array([0])).buffer,Navigator.prototype.requestMediaKeySystemAccess=Nb,delete HTMLMediaElement.prototype.mediaKeys,HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=Pb,window.MediaKeys=Rb,window.MediaKeySystemAccess=Ob):window.MSMediaKeys?(ic=(new Uint8Array([0])).buffer,delete HTMLMediaElement.prototype.mediaKeys,
HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=bc,window.MediaKeys=ac,window.MediaKeySystemAccess=$b,Navigator.prototype.requestMediaKeySystemAccess=Zb):(Navigator.prototype.requestMediaKeySystemAccess=xa,delete HTMLMediaElement.prototype.mediaKeys,HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=ya,window.MediaKeys=za,window.MediaKeySystemAccess=Aa))}m("shaka.polyfill.MediaKeys.install",jc);m("shaka.polyfill.installAll",function(){ta();va();Na();Ca();jc()});var kc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function K(a){var b;a instanceof K?(lc(this,a.H),this.P=a.P,this.G=a.G,mc(this,a.Y),this.D=a.D,nc(this,a.a.clone()),this.M=a.M):a&&(b=String(a).match(kc))?(lc(this,b[1]||"",!0),this.P=oc(b[2]||""),this.G=oc(b[3]||"",!0),mc(this,b[4]),this.D=oc(b[5]||"",!0),nc(this,b[6]||"",!0),this.M=oc(b[7]||"")):this.a=new L(null)}k=K.prototype;k.H="";k.P="";k.G="";k.Y=null;k.D="";k.M="";
k.toString=function(){var a=[],b=this.H;b&&a.push(pc(b,qc,!0),":");if(b=this.G){a.push("//");var c=this.P;c&&a.push(pc(c,qc,!0),"@");a.push(encodeURIComponent(b).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.Y;null!=b&&a.push(":",String(b))}if(b=this.D)this.G&&"/"!=b.charAt(0)&&a.push("/"),a.push(pc(b,"/"==b.charAt(0)?rc:sc,!0));(b=this.a.toString())&&a.push("?",b);(b=this.M)&&a.push("#",pc(b,tc));return a.join("")};
k.resolve=function(a){var b=this.clone();"data"===b.H&&(b=new K);var c=!!a.H;c?lc(b,a.H):c=!!a.P;c?b.P=a.P:c=!!a.G;c?b.G=a.G:c=null!=a.Y;var d=a.D;if(c)mc(b,a.Y);else if(c=!!a.D){if("/"!=d.charAt(0))if(this.G&&!this.D)d="/"+d;else{var e=b.D.lastIndexOf("/");-1!=e&&(d=b.D.substr(0,e+1)+d)}if(".."==d||"."==d)d="";else if(-1!=d.indexOf("./")||-1!=d.indexOf("/.")){for(var e=0==d.lastIndexOf("/",0),d=d.split("/"),f=[],g=0;g<d.length;){var h=d[g++];"."==h?e&&g==d.length&&f.push(""):".."==h?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),e&&g==d.length&&f.push("")):(f.push(h),e=!0)}d=f.join("/")}}c?b.D=d:c=""!==a.a.toString();c?nc(b,a.a.clone()):c=!!a.M;c&&(b.M=a.M);return b};k.clone=function(){return new K(this)};function lc(a,b,c){a.H=c?oc(b,!0):b;a.H&&(a.H=a.H.replace(/:$/,""))}function mc(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.Y=b}else a.Y=null}function nc(a,b,c){b instanceof L?a.a=b:(c||(b=pc(b,uc)),a.a=new L(b))}
function oc(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}function pc(a,b,c){return"string"==typeof a?(a=encodeURI(a).replace(b,vc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function vc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var qc=/[#\/\?@]/g,sc=/[\#\?:]/g,rc=/[\#\?]/g,uc=/[\#\?@]/g,tc=/#/g;function L(a){this.b=a||null}L.prototype.a=null;L.prototype.c=null;
function wc(a,b,c){if(!a.a&&(a.a={},a.c=0,a.b))for(var d=a.b.split("&"),e=0;e<d.length;e++){var f=d[e].indexOf("="),g=null,h=null;0<=f?(g=d[e].substring(0,f),h=d[e].substring(f+1)):g=d[e];g=decodeURIComponent(g.replace(/\+/g," "));h=h||"";wc(a,g,decodeURIComponent(h.replace(/\+/g," ")))}a.b=null;(d=a.a.hasOwnProperty(b)&&a.a[b])||(a.a[b]=d=[]);d.push(c);a.c++}
L.prototype.toString=function(){if(this.b)return this.b;if(!this.a)return"";var a=[],b;for(b in this.a)for(var c=encodeURIComponent(b),d=this.a[b],e=0;e<d.length;e++){var f=c;""!==d[e]&&(f+="="+encodeURIComponent(d[e]));a.push(f)}return this.b=a.join("&")};L.prototype.clone=function(){var a=new L;a.b=this.b;if(this.a){var b={},c;for(c in this.a)b[c]=this.a[c].concat();a.a=b;a.c=this.c}return a};function xc(){this.id=this.url=null;this.type="static";this.b=this.j=this.m=this.Ea=null;this.g=5;this.i=this.c=this.f=null;this.h=1;this.a=[]}function yc(){this.g=this.f=this.c=this.m=this.b=this.start=this.id=null;this.a=[]}function zc(){this.i=this.b=this.height=this.width=this.contentType=this.lang=this.group=this.id=null;this.c=!1;this.h=this.g=this.f=this.m=null;this.j=[];this.a=[]}function Ac(){this.value=null}function Bc(){this.contentType=this.lang=this.id=null}
function Cc(){this.g=this.f=this.c=this.m=this.h=this.b=this.height=this.width=this.bandwidth=this.lang=this.id=null;this.a=[]}function Dc(){this.b=this.a=this.c=this.f=null}function Ec(){this.parsedPssh=this.psshBox=null}function Fc(){this.url=null}function Gc(){this.url=null}function M(){this.m=null;this.g=1;this.c=this.b=this.a=this.f=null}M.prototype.clone=function(){var a=new M;a.m=N(this.m);a.g=this.g;a.f=this.f;a.a=O(this.a);a.b=O(this.b);a.c=O(this.c);return a};
function Hc(){this.a=this.url=null}Hc.prototype.clone=function(){var a=new Hc;a.url=N(this.url);a.a=O(this.a);return a};function Ic(){this.a=this.url=null}Ic.prototype.clone=function(){var a=new Ic;a.url=N(this.url);a.a=O(this.a);return a};function Jc(){this.m=null;this.b=1;this.g=this.a=null;this.i=1;this.f=null;this.c=[];this.h=null}Jc.prototype.clone=function(){var a=new Jc;a.m=N(this.m);a.b=this.b;a.a=this.a;a.g=this.g;a.i=this.i;a.f=O(this.f);a.c=N(this.c)||[];a.h=O(this.h);return a};
function Kc(){this.a=this.b=null}Kc.prototype.clone=function(){var a=new Kc;a.b=N(this.b);a.a=O(this.a);return a};function Lc(){this.b=1;this.h=this.a=null;this.j=1;this.i=this.f=this.c=this.g=null}Lc.prototype.clone=function(){var a=new Lc;a.b=this.b;a.a=this.a;a.h=this.h;a.j=this.j;a.g=this.g;a.c=this.c;a.f=this.f;a.i=O(this.i);return a};function Mc(){this.a=[]}Mc.prototype.clone=function(){var a=new Mc;a.a=N(this.a)||[];return a};function Nc(){this.b=this.a=this.startTime=null}
Nc.prototype.clone=function(){var a=new Nc;a.startTime=this.startTime;a.a=this.a;a.b=this.b;return a};function Oc(a,b){this.ea=a;this.end=b}Oc.prototype.clone=function(){return new Oc(this.ea,this.end)};xc.TAG_NAME="MPD";yc.TAG_NAME="Period";zc.TAG_NAME="AdaptationSet";Ac.TAG_NAME="Role";Bc.TAG_NAME="ContentComponent";Cc.TAG_NAME="Representation";Dc.TAG_NAME="ContentProtection";Ec.TAG_NAME="cenc:pssh";Fc.TAG_NAME="BaseURL";Gc.TAG_NAME="Location";M.TAG_NAME="SegmentBase";Hc.TAG_NAME="RepresentationIndex";
Ic.TAG_NAME="Initialization";Jc.TAG_NAME="SegmentList";Kc.TAG_NAME="SegmentURL";Lc.TAG_NAME="SegmentTemplate";Mc.TAG_NAME="SegmentTimeline";Nc.TAG_NAME="S";
xc.prototype.parse=function(a,b){this.url=a.Ea;this.id=P(b,"id",Q);this.type=P(b,"type",Q)||"static";this.b=P(b,"mediaPresentationDuration",Pc);this.g=P(b,"minBufferTime",Pc,this.g);this.f=P(b,"minimumUpdatePeriod",Pc,this.f);this.c=P(b,"availabilityStartTime",Qc,this.c);this.i=P(b,"timeShiftBufferDepth",Pc,this.i);this.h=P(b,"suggestedPresentationDelay",Pc,this.h);var c=a.m,d=R(this,b,Fc);this.m=Tc(c,d);if(d=S(this,b,Gc))this.j=Uc(c,d.url);this.a=R(this,b,yc)};
yc.prototype.parse=function(a,b){this.id=P(b,"id",Q);this.start=P(b,"start",Pc);this.b=P(b,"duration",Pc);var c=R(this,b,Fc);this.m=Tc(a.m,c);this.c=S(this,b,M);this.f=S(this,b,Jc);this.g=S(this,b,Lc);this.a=R(this,b,zc);Vc(this)};function Vc(a){for(var b=[],c=0;c<a.a.length;++c){var d=a.a[c];null!=d.group&&(b[d.group]=!0)}for(c=0;c<a.a.length;++c)if(d=a.a[c],null==d.group){for(var e=1;1==b[e];)++e;b[e]=!0;d.group=e}}
zc.prototype.parse=function(a,b){var c=S(this,b,Bc)||{},d=S(this,b,Ac);this.id=P(b,"id",Q);this.group=P(b,"group",T);this.lang=P(b,"lang",Q,c.lang);this.contentType=P(b,"contentType",Q,c.contentType);this.width=P(b,"width",U);this.height=P(b,"height",U);this.b=P(b,"mimeType",Q);this.i=P(b,"codecs",Q);this.c=d&&"main"==d.value;this.lang&&(this.lang=$a(this.lang));c=R(this,b,Fc);this.m=Tc(a.m,c);this.j=R(this,b,Dc);!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]);this.f=a.c?Wc(this,
b,a.c):S(this,b,M);this.g=a.f?Wc(this,b,a.f):S(this,b,Jc);this.h=a.g?Wc(this,b,a.g):S(this,b,Lc);this.a=R(this,b,Cc);!this.b&&this.a.length&&(this.b=this.a[0].b,!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]))};Ac.prototype.parse=function(a,b){this.value=P(b,"value",Q)};Bc.prototype.parse=function(a,b){this.id=P(b,"id",Q);this.lang=P(b,"lang",Q);this.contentType=P(b,"contentType",Q);this.lang&&(this.lang=$a(this.lang))};
Cc.prototype.parse=function(a,b){this.id=P(b,"id",Q);this.bandwidth=P(b,"bandwidth",U);this.width=P(b,"width",U,a.width);this.height=P(b,"height",U,a.height);this.b=P(b,"mimeType",Q,a.b);this.h=P(b,"codecs",Q,a.i);this.lang=a.lang;var c=R(this,b,Fc);this.m=Tc(a.m,c);this.a=R(this,b,Dc);this.c=a.f?Wc(this,b,a.f):S(this,b,M);this.f=a.g?Wc(this,b,a.g):S(this,b,Jc);this.g=a.h?Wc(this,b,a.h):S(this,b,Lc);this.a=this.a.concat(a.j)};
Dc.prototype.parse=function(a,b){this.f=b;this.c=P(b,"schemeIdUri",Q);var c=P(b,"cenc:default_KID",Q);c&&(this.b=c.replace(/[-]/g,""));this.a=S(this,b,Ec)};Ec.prototype.parse=function(a,b){var c=Xc(b);if(c){this.psshBox=Gb(c);try{this.parsedPssh=new Yb(this.psshBox)}catch(d){if(!(d instanceof RangeError))throw d;}}};Fc.prototype.parse=function(a,b){this.url=Xc(b)};Gc.prototype.parse=function(a,b){this.url=Xc(b)};
M.prototype.parse=function(a,b){this.m=a.m||this.m;this.g=P(b,"timescale",U,this.g);this.f=P(b,"presentationTimeOffset",T,this.f);this.a=P(b,"indexRange",Yc,this.a);this.b=S(this,b,Hc)||this.b;this.c=S(this,b,Ic)||this.c};Hc.prototype.parse=function(a,b){var c=P(b,"sourceURL",Q);this.url=Uc(a.m,c);this.a=P(b,"range",Yc,O(a.a))};Ic.prototype.parse=function(a,b){var c=P(b,"sourceURL",Q);this.url=Uc(a.m,c);this.a=P(b,"range",Yc)};
Jc.prototype.parse=function(a,b){this.m=a.m||this.m;this.b=P(b,"timescale",U,this.b);this.a=P(b,"presentationTimeOffset",T,this.a);this.g=P(b,"duration",U,this.g);var c=P(b,"startNumber",U);null!=c&&(this.i=c);this.f=S(this,b,Ic)||this.f;this.c=(c=R(this,b,Kc))&&0<c.length?c:this.c;this.h=S(this,b,Mc)||this.h};Kc.prototype.parse=function(a,b){var c=P(b,"media",Q);this.b=Uc(a.m,c);this.a=P(b,"mediaRange",Yc)};
Lc.prototype.parse=function(a,b){this.b=P(b,"timescale",U,this.b);this.a=P(b,"presentationTimeOffset",T,this.a);this.h=P(b,"duration",U,this.h);var c=P(b,"startNumber",T);null!=c&&(this.j=c);this.g=P(b,"media",Q,this.g);this.c=P(b,"index",Q,this.c);this.f=P(b,"initialization",Q,this.f);this.i=S(this,b,Mc)||this.i};Mc.prototype.parse=function(a,b){this.a=R(this,b,Nc)};Nc.prototype.parse=function(a,b){this.startTime=P(b,"t",T);this.a=P(b,"d",T);this.b=P(b,"r",Zc)};
function Tc(a,b){if(!b||0===b.length)return a;for(var c=[],d=0;d<b.length;d++){var e=b[d].url;null==a||0===a.length?c.push(new K(e)):(e=Uc(a.slice(0,1),e),c.push(e[0]))}return c}function Uc(a,b){if(!b)return a;var c=new K(b);return a?a.map(function(a){return a.resolve(c)}):[c]}function Wc(a,b,c){var d=O(c);(b=$c(b,c.constructor.TAG_NAME))&&d.parse(a,b);return d}function S(a,b,c){var d=null;if(b=$c(b,c.TAG_NAME))d=new c,d.parse(a,b);return d}
function $c(a,b){for(var c=null,d=0;d<a.childNodes.length;d++)if(a.childNodes[d].tagName==b){if(c)return null;c=a.childNodes[d]}return c}function R(a,b,c){for(var d=[],e=0;e<b.childNodes.length;e++)if(b.childNodes[e].tagName==c.TAG_NAME){var f=new c;f.parse.call(f,a,b.childNodes[e]);d.push(f)}return d}function Xc(a){a=a.firstChild;return a.nodeType!=Node.TEXT_NODE?null:a.nodeValue}function N(a){return a?a.map(function(a){return a.clone()}):null}function O(a){return a?a.clone():null}
function P(a,b,c,d){a=c(a.getAttribute(b));return null!=a?a:void 0!==d?d:null}function Qc(a){if(!a)return null;a=Date.parse(a);return isNaN(a)?null:Math.floor(a/1E3)}
function Pc(a){if(!a)return null;var b=/^P(?:([0-9]*)Y)?(?:([0-9]*)M)?(?:([0-9]*)D)?(?:T(?:([0-9]*)H)?(?:([0-9]*)M)?(?:([0-9.]*)S)?)?$/.exec(a);if(!b)return null;a=0;var c=T(b[1]);c&&(a+=31536E3*c);(c=T(b[2]))&&(a+=2592E3*c);(c=T(b[3]))&&(a+=86400*c);(c=T(b[4]))&&(a+=3600*c);(c=T(b[5]))&&(a+=60*c);b=window.parseFloat(b[6]);(b=isNaN(b)?null:b)&&(a+=b);return a}
function Yc(a){var b=/([0-9]+)-([0-9]+)/.exec(a);if(!b)return null;a=T(b[1]);if(null==a)return null;b=T(b[2]);return null==b?null:new Oc(a,b)}function Zc(a){a=window.parseInt(a,10);return isNaN(a)?null:a}function U(a){a=window.parseInt(a,10);return 0<a?a:null}function T(a){a=window.parseInt(a,10);return 0<=a?a:null}function Q(a){return a};function ad(a,b){this.url=a;this.b=b||new yb;this.g=this.i=this.h=0;this.a=null;this.c=new H;this.f=null}function yb(){this.body=null;this.a=1;this.g=1E3;this.c=0;this.method="GET";this.responseType="arraybuffer";this.b={};this.f=this.withCredentials=!1;this.h=null}var bd=!0;function cd(a){dd(a);a.b.body=null;a.c.destroy();a.c=null;a.f=null}function dd(a){a.a&&(a.a.onload=null,a.a.onreadystatechange=null,a.a.onerror=null,a.a.ontimeout=null);a.a=null}k=ad.prototype;
k.send=function(){if(this.a)return this.c;if(0==this.url.lastIndexOf("data:",0)){var a=this.url.split(":")[1].split(";").pop().split(","),b=a.pop(),b="base64"==a.pop()?window.atob(b.replace(/-/g,"+").replace(/_/g,"/")):window.decodeURIComponent(b);"arraybuffer"==this.b.responseType&&(b=Fb(b).buffer);a=JSON.parse(JSON.stringify(new XMLHttpRequest));a.response=b;a.responseText=b.toString();b=this.c;b.resolve(a);cd(this);return b}if(0==this.url.lastIndexOf("idb:",0))return this.j();this.h++;this.i=Date.now();
this.g||(this.g=this.b.g);window.hola_cdn&&window.hola_cdn.api&&window.hola_cdn.api.new_http_request&&(this.a=window.hola_cdn.api.new_http_request({url:this.url}));this.a||(this.a=new XMLHttpRequest);a=this.url;bd&&(this.f&&!this.f.supportsCaching()||this.b.f)&&(a=new K(a),wc(a.a,"_",Date.now()),a=a.toString());this.a.open(this.b.method,a,!0);this.a.responseType=this.b.responseType;this.a.timeout=this.b.c;this.a.withCredentials=this.b.withCredentials;this.a.onload=this.Ra.bind(this);this.b.f&&(this.a.onreadystatechange=
this.Ya.bind(this));this.a.onerror=this.lb.bind(this);this.a.ontimeout=this.bb.bind(this);for(b in this.b.b)this.a.setRequestHeader(b,this.b.b[b]);this.a.send(this.b.body);return this.c};function ed(a,b,c){b=Error(b);b.type=c;b.status=a.a.status;b.url=a.url;b.method=a.b.method;b.body=a.b.body;b.xhr=a.a;return b}
k.Ra=function(a){this.f&&this.f.sample(Date.now()-this.i,a.loaded);200<=this.a.status&&299>=this.a.status?(this.c.resolve(this.a),cd(this)):this.h<this.b.a?fd(this):(a=ed(this,"HTTP error.","net"),this.c.reject(a),cd(this))};k.Ya=function(){if(this.a.readyState==XMLHttpRequest.HEADERS_RECEIVED){var a=Date.parse(this.a.getResponseHeader("Date"));a&&(Qa=a-Date.now())}};k.lb=function(){var a=ed(this,"Network failure.","net");this.c.reject(a);cd(this)};
k.bb=function(){if(this.h<this.b.a)fd(this);else{var a=ed(this,"Request timed out.","net");this.c.reject(a);cd(this)}};function fd(a){dd(a);window.setTimeout(a.send.bind(a),a.g*(1+.5*(2*Math.random()-1)));a.g*=2};function J(a,b,c,d){this.J=b;this.h=c||0;this.g=null!=d?d:null;this.b=this.a=null;this.i=a;this.f=null}J.prototype.fetch=function(a,b){if(this.a)return this.a;var c=a||new yb;if(this.h||this.g)c.b.Range="bytes="+(this.h+"-"+(null!=this.g?this.g:""));return this.a=gd(this,0,c,b)};J.prototype.c=function(){if(this.b){this.a=null;var a=this.b;if(a.a&&a.a.readyState!=XMLHttpRequest.DONE){a.a.abort();var b=ed(a,"Request aborted.","aborted");a.c.reject(b);cd(a)}this.f=this.b=null}};
function gd(a,b,c,d){var e=a.J[b].toString();a.i&&(e=a.i(e,c.b)||e);a.b=new ad(e,c);d&&(a.b.f=d);e=a.b.send().then(I(a,function(a){this.f=this.b=this.a=null;this.f=a.a?new K(a.a):this.J[b];return Promise.resolve(a.response)}));return e=e.catch(I(a,function(a){if(this.a&&b+1<this.J.length)return this.a=gd(this,b+1,c,d);this.a=this.b=null;return Promise.reject(a)}))}J.prototype.clone=function(){return new J(this.i,this.J.map(function(a){return a.clone()}),this.h,this.g)};J.prototype.toString=function(){return this.J[0].toString()};function hd(a,b){this.a=new yb;this.a.responseType="text";this.a.a=3;this.a.c=1E3*(null!=b?b:0);this.a.f=!0;this.b=a}hd.prototype.send=function(){var a=this.b;return a.fetch(this.a).then(function(b){var c;c=a.J;var d=[a.f];c=(b=(new DOMParser).parseFromString(b,"text/xml"))?S({Ea:c,m:d},b,xc):null;if(c)return Promise.resolve(c);c=Error("MPD parse failure.");c.type="dash";return Promise.reject(c)})};function id(a,b){this.a=a;this.b=b||null}id.prototype.destroy=function(){this.a&&(this.a.c(),this.a=null);this.b=null};id.prototype.create=function(){return this.a?this.a.fetch():Promise.resolve(this.b)};function jd(a,b,c){this.startTime=a;this.endTime=b;this.url=c}function zb(a,b){for(var c=a.length-1;0<=c;--c){var d=a[c];if(b>=d.startTime&&(null==d.endTime||b<d.endTime))return c}return-1}function kd(a,b){return a.map(function(a){return new jd(a.startTime+b,null!=a.endTime?a.endTime+b:null,a.url)})};function ld(){}
ld.prototype.parse=function(a,b,c,d){var e=null;try{a:{var f=[],g=new Ra(a),h=v(g);if(1936286840!=v(g))e=null;else{1==h&&(h=Ua(g));var l=Ta(g);w(g,3);w(g,4);var n=v(g);if(0==n)e=null;else{var r,t;0==l?(r=v(g),t=v(g)):(r=Ua(g),t=Ua(g));w(g,2);var B=g.b.getUint16(g.a,g.c);g.a+=2;a=r;b=b+h+t;for(h=0;h<B;h++){var ib=v(g);t=(ib&2147483648)>>>31;var l=ib&2147483647,Rc=v(g);v(g);if(1==t){e=null;break a}var ce=new J(d,c,b,b+l-1);f.push(new jd(a/n,(a+Rc)/n,ce));a+=Rc;b+=l}e=f}}}}catch(Sc){if(!(Sc instanceof RangeError))throw Sc;
}return e};function md(a){this.references=a;this.a=0}md.prototype.destroy=function(){this.references=null};md.prototype.length=function(){return this.references.length};function nd(a){if(0==a.references.length)throw new RangeError("SegmentIndex: There is no first SegmentReference.");return a.references[0]}md.prototype.X=function(){if(0==this.references.length)throw new RangeError("SegmentIndex: There is no last SegmentReference.");return this.references[this.references.length-1]};
md.prototype.get=function(a){if(0>a||a>=this.references.length)throw new RangeError("SegmentIndex: The specified index is out of range.");return this.references[a]};function od(a,b){var c=zb(a.references,b);return 0<=c?a.references[c]:null}function pd(a,b){var c=b-a.a;0!=c&&(a.references=kd(a.references,c),a.a=b)};function qd(){this.a=rd++;this.id=this.N=this.segmentIndexSource=null;this.h=0;this.height=this.width=this.bandwidth=null;this.f=this.c="";this.g=[];this.F=!1;this.b=!0}var rd=0;qd.prototype.destroy=function(){this.segmentIndexSource&&(this.segmentIndexSource.destroy(),this.segmentIndexSource=null);this.N&&(this.N.destroy(),this.N=null)};function sd(a){var b=a.c||"";a.f&&(b+='; codecs="'+a.f+'"');return b}
function td(){this.a=ud++;this.id=null;this.contentType=this.lang="";this.c=!1;this.streamInfos=[];this.b=[]}var ud=0;td.prototype.destroy=function(){for(var a=0;a<this.streamInfos.length;++a)this.streamInfos[a].destroy();this.b=this.streamInfos=null};function vd(a){for(var b=[],c=0;c<a.b.length;++c){var d=new wd;d.id=a.a;d.a=a.b[c];d.contentType=a.contentType;d.b=a.streamInfos.length?sd(a.streamInfos[0]):"";b.push(d)}return b}
function xd(){this.id=null;this.start=0;this.a=null;this.streamSetInfos=[]}xd.prototype.destroy=function(){for(var a=0;a<this.streamSetInfos.length;++a)this.streamSetInfos[a].destroy();this.streamSetInfos=null};function yd(){this.a=!1;this.c=this.g=this.f=null;this.b=0;this.periodInfos=[]}yd.prototype.destroy=function(){for(var a=0;a<this.periodInfos.length;++a)this.periodInfos[a].destroy();this.periodInfos=null};function wd(){this.id=0;this.a=null;this.b=this.contentType=""};function zd(a,b,c,d,e){F.call(this,a);this.c=b;this.a=new tb(c,d,e);this.s=this.segmentIndex_=this.b=null;this.B=!1;this.g=null;this.l=!1;this.i=null;this.o=!1;this.h=new H;this.j=this.f=!1;this.u=0;this.C=15;this.w=!1}p(zd,F);zd.prototype.A=function(a){null!=a.initialStreamBufferSize&&(this.u=Number(a.initialStreamBufferSize));null!=a.streamBufferSize&&(this.C=Number(a.streamBufferSize));null!=a.segmentRequestTimeout&&(this.a.v=Number(a.segmentRequestTimeout))};
zd.prototype.destroy=function(){Ad(this);this.h.destroy();this.b=this.h=null;this.a.destroy();this.v=this.c=this.a=null};k=zd.prototype;k.fa=function(){return this.b};k.Ca=function(){return this.segmentIndex_};k.Ia=function(a){this.f||a.then(function(){this.f=!0;this.g||Bd(this,0)}.bind(this)).catch(function(){});return this.h};k.Da=function(){return this.j};
k.ha=function(a,b,c){if(a!=this.b){var d=[a.segmentIndexSource.create(),a.N.create()];Promise.all(d).then(I(this,function(d){if(this.c){var f=this.b;this.b=a;this.segmentIndex_=d[0];this.s=d[1];this.B=!0;this.l||(f?b&&Cd(this,!0,c):Bd(this,0))}})).catch(I(this,function(a){"aborted"!=a.type&&(this.f?(a=y(a),this.dispatchEvent(a)):this.h.reject(a))}))}};k.Fa=function(){return Cd(this,!1)};
function Cd(a,b,c){a.b&&!a.l&&(a.l=!0,Ad(a),vb(a.a).then(I(a,function(){var a=this.c.currentTime;if(!b&&0<wb(this.a,a)&&0<=zb(this.a.b,a))return Promise.resolve();if(c)return Cb(this.a,this.c.currentTime+c);this.w=!0;return Bb(this.a)})).then(I(a,function(){this.l=!1;Bd(this,0)})).catch(I(a,function(a){this.l=!1;this.f?(a=y(a),this.dispatchEvent(a)):this.h.reject(a)})))}k.Ga=function(a){return 0<wb(this.a,a)&&0<=zb(this.a.b,a)};k.ga=function(){};k.la=function(){return!0};
k.eb=function(){if(this.o&&!this.f)this.g=null;else{var a;if(a=this.f&&!this.j)a=1<this.a.c.buffered.length?!0:!1;if(a)Cd(this,!0);else{this.g=null;a=this.b;var b=this.segmentIndex_,c=this.c.currentTime;wb(this.a,this.o?c:c+(this.i||0))>=(this.o?Math.max(this.u,this.C):this.u)?(Dd(this),Bd(this,1E3/(Math.abs(this.c.playbackRate)||1))):(b=Ed(this,c,b))?(b=this.a.fetch(b,a.h,this.s),this.s=null,this.B&&(this.B=!1,Fd(this,a)),this.j=!1,b.then(I(this,function(a){null==this.i&&(this.i=a);this.w&&0<wb(this.a,
c)&&(this.w=!1,this.c.currentTime+=.001);Bd(this,0)})).catch(I(this,function(a){if("aborted"!=a.type){var b=[0,404,410];"net"==a.type&&-1!=b.indexOf(a.xhr.status)&&this.b&&Bd(this,5E3);a=y(a);this.dispatchEvent(a)}}))):(Dd(this),this.f&&!this.j&&(this.j=!0,Gd(this)),Bd(this,1E3))}}};function Ed(a,b,c){a=a.a;var d=a.b.length;a=0<d?a.b[d-1]:null;return null!=a?null!=a.endTime?od(c,a.endTime):null:od(c,b)||(c.length()?c.X():null)}
function Dd(a){if(!a.o&&null!=a.i){a.o=!0;var b=a.a,c=a.i,d=c-b.o;0!=d&&(b.b=kd(b.b,d),b.o=c);a.h.resolve(a.i)}}function Fd(a,b){var c;c=b.c.split("/")[0];c=x({type:"adaptation",bubbles:!0,contentType:c,size:"video"!=c?null:{width:b.width,height:b.height},bandwidth:b.bandwidth});a.dispatchEvent(c)}function Gd(a){var b=x({type:"ended"});a.dispatchEvent(b)}function Bd(a,b){a.g=window.setTimeout(a.eb.bind(a),b)}function Ad(a){null!=a.g&&(window.clearTimeout(a.g),a.g=null)};function Hd(a){this.a=a;this.segmentIndex_=null}Hd.prototype.destroy=function(){this.segmentIndex_&&(this.segmentIndex_.destroy(),this.segmentIndex_=null)};Hd.prototype.create=function(){if(this.segmentIndex_)return Promise.resolve(this.segmentIndex_);var a=new jd(0,null,this.a);this.segmentIndex_=new md([a]);return Promise.resolve(this.segmentIndex_)};function Id(a,b){F.call(this,a);this.b=b;this.g=!0;this.segmentIndex_=this.f=null;this.c=new H;this.a=null}p(Id,F);Id.prototype.A=function(){};Id.prototype.destroy=function(){this.a&&this.b.removeChild(this.a);this.c.destroy();this.v=this.b=this.f=this.segmentIndex_=this.a=this.c=null};k=Id.prototype;k.fa=function(){return this.f};k.Ca=function(){return this.segmentIndex_};k.Ia=function(){return this.c};k.Da=function(){return!0};
k.ha=function(a){a.segmentIndexSource.create().then(I(this,function(b){if(this.b){if(0==b.length())return Promise.reject(Error("No subtitles URL available."));var c=this.f;this.f=a;this.segmentIndex_=b;b=nd(b).url.J[0].toString();var d=this.la();this.a&&(this.ga(!1),this.b.removeChild(this.a));this.a=document.createElement("track");this.b.appendChild(this.a);this.a.src=b;this.ga(d);b=x({type:"adaptation",bubbles:!0,contentType:"text",size:null,bandwidth:a.bandwidth});this.dispatchEvent(b);c||this.c.resolve(0)}}))};
k.Fa=function(){};k.Ga=function(){return!0};k.ga=function(a){this.g=a;this.a&&(this.a.track.mode=a?"showing":"disabled")};k.la=function(){this.a&&(this.g="showing"==this.a.track.mode);return this.g};function Jd(a,b,c,d,e,f,g){this.f=c;this.a=d;this.c=e;this.b=null;this.g=g}Jd.prototype.destroy=function(){this.g=null;this.a.c();this.a=null;this.c&&(this.c.c(),this.c=null);this.b=null};
Jd.prototype.create=function(){if("webm"==this.f){var a=Error("WebM is not supported in this build configuration.");a.type="app";return Promise.reject(a)}if(this.b)return this.b;a=[this.a.fetch()];"webm"==this.f&&a.push(this.c.fetch());return this.b=Promise.all(a).then(I(this,function(a){a=a[0];var c=null;"mp4"==this.f&&(c=(new ld).parse(new DataView(a),this.a.h,this.a.J,this.g));return c?Promise.resolve(new md(c)):(a=Error("Failed to parse SegmentReferences from "+this.a.toString()+" (or one of its fallbacks)."),
a.type="stream",Promise.reject(a))}))};function Kd(a){this.a=a}
function Ld(a){if(a.a.length){null==a.a[0].start&&(a.a[0].start=0);var b=function(a){return 0==a||!!a};"dynamic"==a.type&&(a.b=null);b(a.b)&&1==a.a.length&&!b(a.a[0].b)&&(a.a[0].b=a.b);for(var c=0,d=!0,e=0;e<a.a.length;++e){var f=a.a[e-1],g=a.a[e],h=a.a[e+1]||{start:a.b};!b(g.start)&&f&&b(f.start)&&b(f.b)&&(g.start=f.start+f.b);!b(g.b)&&b(h.start)&&(g.b=h.start-g.start);null!=g.start&&null!=g.b?c+=g.b:d=!1}b(a.b)||(e=a.a[a.a.length-1],d?a.b=c:b(e.start)&&b(e.b)?a.b=e.start+e.b:"dynamic"!=a.type&&
(a.b=c))}}function Md(a,b,c){var d=new xd;d.id=b.id;d.start=b.start;d.a=b.b;var e=new C;b.a.forEach(function(a){e.push(a.contentType||"",a)});b=kb(e);for(var f=0;f<b.length;++f){var g=new C;e.get(b[f]).forEach(function(a){g.push(a.group,a)});for(var h=kb(g),l=0;l<h.length;++l){var n=new C;g.get(h[l]).forEach(function(a){n.push(a.lang,a)});for(var r=kb(n),t=0;t<r.length;++t){var B=n.get(r[t]),B=Nd(a,B,c);d.streamSetInfos.push(B)}}}return d}
function Nd(a,b,c){ba(b.every(function(a){return a.group==b[0].group&&(a.lang||"")==(b[0].lang||"")&&(a.contentType||"")==(b[0].contentType||"")}));var d=new td,e=b.filter(function(a){return null!=a.id});e.length==b.length&&(d.id=e.map(function(a){return a.id}).sort().reduce(function(a,b){return a+","+b}));d.lang=b[0].lang||"";d.contentType=b[0].contentType||"";d.c=b.some(function(a){return a.c});for(var e={},f=0;f<b.length;++f)for(var g=b[f],h=0;h<g.a.length;++h){var l=g.a[h],n=Od(a,l),r=d.b.slice(0);
Pd(n,r);0==r.length&&0<d.b.length||!(l=Qd(l,c))||(d.streamInfos.push(l),d.b=r,e[l.a]=g)}if(d.b.some(function(a){return""==a.a}))return d.streamInfos.forEach(function(a){a.F=!0}),d;a=Rd(b);for(f=0;f<d.streamInfos.length;++f)l=d.streamInfos[f],g=e[l.a],g==a&&(l.F=!0);return d}function Rd(a){for(var b=null,c=null,d=0;d<a.length;++d)for(var e=a[d],f=0;f<e.a.length;++f){var g=e.a[f],g=(g.width||1)*(g.height||1)*(g.bandwidth||1);if(null==b||g<b)b=g,c=e}return c}
function Pd(a,b){if(0==b.length)Array.prototype.push.apply(b,a);else for(var c=0;c<b.length;++c){for(var d=!1,e=0;e<a.length;++e){var f=b[c],g=a[e];if(f.a==g.a&&f.h==g.h&&f.withCredentials==g.withCredentials&&f.g==g.g&&f.i==g.i&&f.f==g.f&&f.j==g.j&&Ib(f.c,g.c)){d=!0;Lb(b[c],a[e].b);break}}d||(b.splice(c,1),--c)}}function Od(a,b){var c=[];if(0==b.a.length)c.push(new Jb);else if(a.a)for(var d=0;d<b.a.length;++d)c.push.apply(c,Sd(a,b.a[d]));return c}
function Sd(a,b){var c=[];if(2!=a.a.length)return[];var d=a.a(b.c||"",b.f);if(!(d&&d instanceof Array))return[];for(var e=0;e<d.length;++e){var f;var g=d[e];f=new Jb;if(g){var h=z(g,"keySystem");if(null!=h)f.a=h;else throw Error("'keySystem' cannot be null.");var l=z(g,"licenseServerUrl");if(null!=l)f.h=l;else if(h)throw Error("For encrypted streaming content, 'licenseServerUrl' cannot be null or empty.");h=eb(g,"withCredentials");null!=h&&(f.withCredentials=h);h=A(g,"licensePostProcessor",Function);
null!=h&&(f.l=h);h=A(g,"licensePreProcessor",Function);null!=h&&(f.v=h);h=eb(g,"distinctiveIdentifierRequired");null!=h&&(f.g=h);h=eb(g,"persistentStateRequired");null!=h&&(f.i=h);h=z(g,"audioRobustness");null!=h&&(f.f=h);h=z(g,"videoRobustness");null!=h&&(f.j=h);h=A(g,"serverCertificate",Uint8Array);null!=h&&(f.c=h);if(h=A(g,"initData",Object)){g=A(h,"initData",Uint8Array);if(null==g)throw Error("'initData.initData' cannot be null.");h=z(h,"initDataType");if(null==h)throw Error("'initData.initDataType' cannot be null.");
f.b.push({initData:new Uint8Array(g.buffer),initDataType:h})}}0==f.b.length&&b.a&&b.a.psshBox&&Lb(f,[{initData:b.a.psshBox,initDataType:"cenc"}]);c.push(f)}return c}
function Qd(a,b){if(!a.m||0===a.m.length)return null;var c=null,d=1,e=0;a.c?(c=a.b.split("/")[1],"mp4"!=c&&"webm"!=c?c=null:(d=a.c,"webm"!=c||d.c?d.a||d.b&&d.b.a?(e=d.b,e||(e=new Hc,e.url=a.m,e.a=d.a?d.a.clone():null),e=Td(e,b),d=d.c?Td(d.c,b):null,c=new Jd(0,0,c,e,d,0,b),d=new id(d),e=new qd,e.segmentIndexSource=c,e.N=d,c=e):c=null:c=null),d=a.c.g,e=a.c.f):a.f?(c=null,d=a.f.b,e=a.f.a):a.g?(c=null,d=a.g.b,e=a.g.a):"text"==a.b.split("/")[0]&&(c=new qd,c.segmentIndexSource=new Hd(new J(b,a.m)));if(!c)return null;
c.id=a.id;e&&(c.h=-1*e/d);c.bandwidth=a.bandwidth;c.width=a.width;c.height=a.height;c.c=a.b||"";c.f=a.h||"";for(d=0;d<a.a.length;++d)e=a.a[d],e.b&&c.g.push(e.b);return c}function Td(a,b){var c=a.url,d=0,e=null;a.a&&(d=a.a.ea,e=a.a.end);return new J(b,c,d,e)};function Ud(){this.streamStats=null;this.droppedFrames=this.decodedFrames=NaN;this.bufferingTime=this.playTime=this.estimatedBandwidth=0;this.playbackLatency=NaN;this.bufferingHistory=[];this.bandwidthHistory=[];this.streamHistory=[]}function Vd(a,b){var c=new Wd(b);a.streamHistory.push(new Xd(c));if(c.videoHeight||!a.streamStats)a.streamStats=c}function Wd(a){this.videoWidth=a.width;this.videoHeight=a.height;this.videoMimeType=a.c;this.videoBandwidth=a.bandwidth}
function Xd(a){this.timestamp=(Date.now()+Qa)/1E3;this.value=a};function Yd(a,b,c,d,e,f){this.b=new J(null,[new K(a)]);this.a=new yb;this.a.body=b;this.a.method=c;this.a.a=3;this.a.withCredentials=d;this.a.c=1E3*(null!=f?f:0);a=e||{};for(var g in a)this.a.b[g]=a[g]}Yd.prototype.send=function(){return this.b.fetch(this.a).then(function(a){return Promise.resolve(new Uint8Array(a))})};function V(a,b,c){F.call(this,a);this.c=b;this.j=c;this.a=this.h=null;this.i=new D;this.b=[];this.f=[];this.o=0;this.g=new H;this.l=null}p(V,F);V.prototype.destroy=function(){this.v=null;for(var a=0;a<this.f.length;++a)this.f[a].close().catch(function(){});this.f=[];this.b=this.a=this.h=null;this.g.destroy();this.g=null;this.i.destroy();this.i=null;this.l&&(window.clearTimeout(this.l),this.l=null);this.c=this.j=null};
V.prototype.initialize=function(){var a=new C,b;b=this.j;if(b.w){b=b.a.periodInfos[0];for(var c=[],d=0;d<b.streamSetInfos.length;++d)c.push.apply(c,vd(b.streamSetInfos[d]));b=c}else b=[];for(c=0;c<b.length;++c)d=b[c],d.a.a||d.b&&!Zd(d.b)||a.push(d.contentType,d);for(var c={},d=!1,e=0;e<b.length;++e){var f=b[e];if(f.a.a&&!a.a.hasOwnProperty(f.contentType)){var g=f.a.a,h=c[g];h||(h=f.a,h={audioCapabilities:void 0,videoCapabilities:void 0,initDataTypes:void 0,distinctiveIdentifier:h.g?"required":"optional",
persistentState:h.i?"required":"optional",sessionTypes:["temporary"]},c[g]=h);if(f.b&&(g=f.contentType+"Capabilities",g in h)){d=!0;h[g]||(h[g]=[]);var l;"audio"==f.contentType?l=f.a.f:"video"==f.contentType&&(l=f.a.j);h[g].push({contentType:f.b,robustness:l})}}}if(!d)if(b.length)this.a=b[0].a;else throw a=Error("No DrmInfo exists!"),a.type="drm",a;if(0==Object.keys(c).length)return $d(this.j,a),this.g.resolve(),Promise.resolve();l=new H;c=ae(c,l);c=c.then(this.u.bind(this,b,a));l.reject(null);return c};
function ae(a,b){for(var c in a)b=b.catch(function(a,b){return navigator.requestMediaKeySystemAccess(a,[b])}.bind(null,c,a[c]));return b}
V.prototype.u=function(a,b,c){if(!this.c)return be();for(var d=c.keySystem,e=c.getConfiguration(),f=["audio","video"],g=0;g<f.length;++g){var h=f[g];if(!b.a.hasOwnProperty(h)){var l=e[h+"Capabilities"];if(l){for(var l=l[0],n=[],r={},t=0;t<a.length;++t){var B=a[t],ib=l?B.b==l.contentType:B.contentType==h;B.a.a!=d||!ib||B.id in r||(n.push(B),r[B.id]=!0,this.a=this.a?Kb(this.a,B.a):B.a)}b.set(h,n)}}}$d(this.j,b);return c.createMediaKeys().then(function(a){this.h=a}.bind(this))};
function de(a){return a.c?a.h?a.c.setMediaKeys(a.h).then(I(a,function(){return this.c?this.a.c?this.h.setServerCertificate(this.a.c):Promise.resolve():be()})).then(I(a,function(){if(!this.c)return be();for(var a=0;a<this.a.b.length;++a){var c=this.a.b[a];this.s({type:"encrypted",initDataType:c.initDataType,initData:c.initData})}0==this.a.b.length&&E(this.i,this.c,"encrypted",this.s.bind(this))})):Promise.resolve():be()}
function be(){var a=Error("EmeManager destroyed");a.type="destroy";return Promise.reject(a)}
V.prototype.s=function(a){for(var b=new Uint8Array(a.initData),c=0;c<this.b.length;++c)if(Ib(b,this.b[c].data))return;try{var d=ee(this)}catch(e){b=y(e);this.dispatchEvent(b);this.g.reject(e);return}a=d.generateRequest(a.initDataType,a.initData);this.b.push({data:b,oa:d});a.catch(I(this,function(a){if(this.c){for(var b=0;b<this.b.length;++b)if(this.b[b].oa==d){this.b.splice(b,1);break}b=y(a);this.dispatchEvent(b);this.g.reject(a)}}));this.f.push(d)};
function ee(a){var b=null,b=a.h.createSession();E(a.i,b,"message",a.A.bind(a));E(a.i,b,"keystatuseschange",a.w.bind(a));return b}V.prototype.A=function(a){fe(this,a.target,this.a,a.message)};
V.prototype.w=function(a){a=a.target;var b={};a.keyStatuses.forEach(function(a,c){if("string"==typeof a){var f=a;a=c;c=f}if("com.microsoft.playready"==this.a.a&&16==a.byteLength){var f=new DataView(a),g=f.getUint32(0,!0),h=f.getUint16(4,!0),l=f.getUint16(6,!0);f.setUint32(0,g,!1);f.setUint16(4,h,!1);f.setUint16(6,l,!1)}f=Hb(new Uint8Array(a));b[f]=c}.bind(this));if(a.expiration<Date.now()){for(var c=0;c<this.b.length;++c)if(this.b[c].oa==a){this.b.splice(c,1);break}a.close();this.f.splice(this.f.indexOf(a),
1)}ge(this.j,b)};function fe(a,b,c,d){d=he(c,d);(new Yd(d.url,d.body,d.method,c.withCredentials,d.headers,0)).send().then(I(a,function(a){c.l&&(a=c.l(a));return b.update(a)})).then(I(a,function(){var a=x({type:"sessionReady",detail:b});this.dispatchEvent(a);this.o++;this.o>=this.f.length&&this.g.resolve()})).catch(I(a,function(a){a.oa=b;a=y(a);this.dispatchEvent(a)}))}
function he(a,b){var c={url:a.h,body:b.slice(0),method:"POST",headers:{}};if("com.microsoft.playready"===a.a){for(var d=String.fromCharCode.apply(null,new Uint16Array(c.body)),d=(new DOMParser).parseFromString(d,"application/xml"),e=d.getElementsByTagName("name"),f=d.getElementsByTagName("value"),g=0;g<e.length;g++)c.headers[e[g].childNodes[0].nodeValue]=f[g].childNodes[0].nodeValue;c.body=window.atob(d.getElementsByTagName("Challenge")[0].childNodes[0].nodeValue)}if(!a.v)return c;a.v(c);c.url=z(c,
"url");if(null==c.url)throw Error("'url' cannot be null.");if(!(c.body instanceof ArrayBuffer||"string"==typeof c.body||null==c.body))throw new TypeError("'body' must be an ArrayBuffer, a string, or null.");c.method=z(c,"method");if("GET"!=c.method&&"POST"!=c.method)throw Error("'method' must be either 'GET' or 'POST'.");c.headers=A(c,"headers",Object);if(null==c.headers)throw Error("'headers' cannot be null.");return c};function W(a){F.call(this,null);this.a=a;this.b=null;this.f=new D;this.j=this.i=null;this.w=0;this.s=null;this.h=!1;this.g=new Ud;this.c={enableAdaptation:!0,streamBufferSize:15,liveStreamEndTimeout:15,licenseRequestTimeout:0,mpdRequestTimeout:0,segmentRequestTimeout:0,preferredLanguage:"en",restrictions:new ja};this.l=1;this.A=null}p(W,F);m("shaka.player.Player",W);W.version="v1.6.5-hola-1-3-g5904308-dirty";
W.isBrowserSupported=function(){return!!window.MediaSource&&!!window.MediaKeys&&!!window.navigator&&!!window.navigator.requestMediaKeySystemAccess&&!!window.MediaKeySystemAccess&&!!window.MediaKeySystemAccess.prototype.getConfiguration&&!!window.Promise&&!!Element.prototype.requestFullscreen&&!!document.exitFullscreen&&"fullscreenElement"in document&&!!window.Uint8Array};function Zd(a){return"text/vtt"==a?!!window.VTTCue:MediaSource.isTypeSupported(a)}W.isTypeSupported=Zd;
W.setTextStyle=function(a){var b=document.getElementById("ShakaPlayerTextStyle");b||(b=document.createElement("style"),b.id="ShakaPlayerTextStyle",document.head.appendChild(b));for(b=b.sheet;b.cssRules.length;)b.deleteRule(0);b.insertRule("::cue { "+oa(a)+" }",0)};W.prototype.destroy=function(){return this.o().then(I(this,function(){this.f.destroy();this.a=this.f=null})).catch(function(){})};W.prototype.destroy=W.prototype.destroy;
W.prototype.o=function(){if(!this.b)return Promise.resolve();this.h&&ie(this);this.a.pause();lb(this.f);je(this);ke(this);this.i&&(this.i.destroy(),this.i=null);this.a.src="";var a=this.a.setMediaKeys(null);this.b&&(this.b.destroy(),this.b=null);this.h=!1;this.g=new Ud;return a};W.prototype.unload=W.prototype.o;W.prototype.K=function(){return this.b};W.prototype.getVideoSource=W.prototype.K;
W.prototype.$=function(a){var b=this.o();this.a.autoplay&&(da("load"),E(this.f,this.a,"timeupdate",this.Qa.bind(this)));a.za(this.c);a.L=this.A;this.A=null;b=b.then(I(this,function(){return a.$()}));b.catch(I(this,function(b){a.destroy();return Promise.reject(b)}));return b.then(I(this,function(){if(!this.a)return le();this.b=a;E(this.f,this.b,"seekrangechanged",this.Za.bind(this));this.i=new V(this,this.a,this.b);return this.i.initialize()})).then(I(this,function(){if(!this.a)return le();E(this.f,
this.a,"error",this.jb.bind(this));E(this.f,this.a,"playing",this.Xa.bind(this));E(this.f,this.a,"pause",this.Wa.bind(this));var a;a=this.b;var b=this.a;a.w?(a.v=this,a.f=b,a.A=this.Ha(),E(a.j,a.g,"sourceopen",a.Sa.bind(a)),E(a.j,a.V,"bandwidth",a.kb.bind(a)),b=a.f.mediaKeys,a.f.src=window.URL.createObjectURL(a.g),b=a.f.setMediaKeys(b),a=Promise.all([a.i,b])):(a=Error("Cannot call attach() right now."),a.type="app",a=Promise.reject(a));return a})).then(I(this,function(){return this.a?de(this.i):le()})).then(I(this,
function(){if(!this.a)return le();me(this)})).catch(I(this,function(a){if(!this.a)return le();if("destroy"!=a.type){var b=y(a);this.dispatchEvent(b)}return this.o().then(function(){return Promise.reject(a)})}))};W.prototype.load=W.prototype.$;function le(){var a=Error("Player destroyed");a.type="destroy";return Promise.reject(a)}k=W.prototype;k.Qa=function(){ga("load");this.g.playbackLatency=ha("load")/1E3;this.f.ba(this.a,"timeupdate")};
k.jb=function(){if(this.a.error){var a=this.a.error.code;a!=MediaError.MEDIA_ERR_ABORTED&&(a=Error(ne[a]||"Unknown playback error."),a.type="playback",a=y(a),this.dispatchEvent(a))}};k.Xa=function(){da("playing");!this.j&&0>this.l&&(this.a.playbackRate=0,this.u(this.a.currentTime,Date.now(),this.l));this.h&&ie(this)};k.Wa=function(){ga("playing");var a=ha("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3}ke(this)};k.Za=function(a){this.w=a.start};
k.Ha=function(){if(!this.a.paused){ga("playing");var a=ha("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3;da("playing")}}a=this.g;b=this.a;b.getVideoPlaybackQuality&&(b=b.getVideoPlaybackQuality(),a.decodedFrames=b.totalVideoFrames,a.droppedFrames=b.droppedVideoFrames);return this.g};W.prototype.getStats=W.prototype.Ha;W.prototype.Z=function(){return this.b?this.b.K():[]};W.prototype.getVideoTracks=W.prototype.Z;W.prototype.U=function(){return this.b?this.b.U():[]};
W.prototype.getAudioTracks=W.prototype.U;W.prototype.W=function(){return this.b?this.b.ra():[]};W.prototype.getTextTracks=W.prototype.W;W.prototype.selectVideoTrack=function(a,b){return this.b?this.b.selectVideoTrack(a,void 0==b?!0:b):!1};W.prototype.selectVideoTrack=W.prototype.selectVideoTrack;W.prototype.aa=function(a,b,c){return this.b?oe(this.b,"audio",a,void 0==b?!0:b,c):!1};W.prototype.selectAudioTrack=W.prototype.aa;W.prototype.ca=function(a){return this.b?oe(this.b,"text",a,!1):!1};
W.prototype.selectTextTrack=W.prototype.ca;W.prototype.T=function(a){this.b&&pe(this.b,a)};W.prototype.enableTextTrack=W.prototype.T;W.prototype.R=function(a){ke(this);0<=a?this.a.playbackRate=a:this.a.paused||(this.a.playbackRate=0,this.u(this.a.currentTime,Date.now(),a));this.l=a};W.prototype.setPlaybackRate=W.prototype.R;W.prototype.C=function(){return this.l};W.prototype.getPlaybackRate=W.prototype.C;W.prototype.da=function(a){this.A=a};W.prototype.setPlaybackStartTime=W.prototype.da;
W.prototype.B=function(){var a;this.b?(a=this.b,a=a.a?a.a.a:!1):a=!1;return a};W.prototype.isLive=W.prototype.B;
W.prototype.S=function(a){if(a){var b=eb(a,"enableAdaptation");null!=b&&(this.c.enableAdaptation=b);b=gb(a,"streamBufferSize");null!=b&&(this.c.streamBufferSize=b);b=gb(a,"liveStreamEndTimeout");null!=b&&(this.c.liveStreamEndTimeout=b);b=gb(a,"licenseRequestTimeout");null!=b&&(this.c.licenseRequestTimeout=b);b=gb(a,"mpdRequestTimeout");null!=b&&(this.c.mpdRequestTimeout=b);b=gb(a,"segmentRequestTimeout");null!=b&&(this.c.segmentRequestTimeout=b);b=z(a,"preferredLanguage");null!=b&&(this.c.preferredLanguage=
b);b=A(a,"restrictions",ja);null!=b&&(this.c.restrictions=b.clone());a=eb(a,"disableCacheBustingEvenThoughItMayAffectBandwidthEstimation");null!=a&&(bd=!a);this.b&&this.b.za(this.c)}};W.prototype.configure=W.prototype.S;W.prototype.V=function(){return this.c};W.prototype.getConfiguration=W.prototype.V;function ke(a){a.j&&(window.clearTimeout(a.j),a.j=null)}function me(a){je(a);a.s=window.setTimeout(a.L.bind(a),100)}function je(a){a.s&&(window.clearTimeout(a.s),a.s=null)}
W.prototype.u=function(a,b,c){this.j=null;var d=(Date.now()-b)/1E3*c;this.a.currentTime<this.w+(this.B()?1:.05)?this.a.pause():(d=Math.max(this.w,a+d),this.a.currentTime=d,this.j=window.setTimeout(this.u.bind(this,a,b,c),250))};function ie(a){ga("buffering");var b=a.g;b.bufferingTime+=ha("buffering")/1E3;a.h=!1;a.dispatchEvent(x({type:"bufferingEnd"}))}
W.prototype.L=function(){me(this);if(!this.a.ended&&!this.a.seeking){var a=this.a.buffered,b=a.length?a.end(a.length-1):0,a=Math.max(b-this.a.currentTime,0),c=this.a.duration,c=isNaN(c)?0:Math.max(c-.05,0),b=b>=c||this.a.currentTime>=c;if(this.h){if(c=Number(this.b.B.initialStreamBufferSize),b||a>c)ie(this),this.a.play()}else!this.a.paused&&!b&&.5>a&&(this.h=!0,this.a.pause(),this.g.bufferingHistory.push((Date.now()+Qa)/1E3),da("buffering"),this.dispatchEvent(x({type:"bufferingStart"})))}};
var ne={2:"A network failure occured while loading media content.",3:"The browser failed to decode the media content.",4:"The browser does not support the media content."};function qe(a,b){var c=a.bandwidth||Number.MAX_VALUE,d=b.bandwidth||Number.MAX_VALUE;return c<d?-1:c>d?1:0};function X(){this.a=this.b=null;this.f=new D;this.c=Number.POSITIVE_INFINITY;this.i=!0;this.g=!1}m("shaka.media.SimpleAbrManager",X);X.prototype.destroy=function(){this.f.destroy();this.a=this.b=this.f=null};X.prototype.initialize=function(a,b){this.b||this.a||(this.b=a,this.a=b)};
X.prototype.start=function(){this.b&&this.a&&!this.g&&(this.c=Date.now()+4E3,E(this.f,this.b,"bandwidth",this.l.bind(this)),E(this.f,this.a,"adaptation",this.j.bind(this)),E(this.f,this.a,"trackschanged",this.h.bind(this)),this.g=!0)};X.prototype.enable=function(a){this.i=a};X.prototype.getInitialVideoTrackId=function(){if(!this.b||!this.a)return null;var a=re(this);return a?a.id:null};X.prototype.selectVideoTrack=function(a,b,c){this.g&&this.a.selectVideoTrack(a.id,b,c)};
X.prototype.l=function(){Date.now()<this.c||this.h()};X.prototype.h=function(){if(this.i){var a=re(this);if(a){if(a.active){this.c=Date.now()+3E3;return}this.selectVideoTrack(a,!1)}this.c=Number.POSITIVE_INFINITY}};X.prototype.j=function(){this.c==Number.POSITIVE_INFINITY&&(this.c=Date.now()+3E4)};
function re(a){var b=a.a.K();if(0==b.length)return null;b.sort(sa);var c;a:{c=a.a.U();for(var d=0;d<c.length;++d)if(c[d].active){c=c[d];break a}c=null}c=c?c.bandwidth:0;a=a.b.getBandwidth();for(var d=b[0],e=0;e<b.length;++e){var f=b[e],g=e+1<b.length?b[e+1]:{bandwidth:Number.POSITIVE_INFINITY};if(f.bandwidth&&(g=(g.bandwidth+c)/.85,a>=(f.bandwidth+c)/.95&&a<=g&&(d=f,d.active)))break}return d};function Y(a,b,c){F.call(this,null);this.a=a;this.V=b;this.j=new D;this.g=new MediaSource;this.f=null;this.va=0;this.b=new C;this.o=c;this.o.initialize(b,this);this.w=!1;this.u="en";this.W=!1;this.A=null;this.i=new H;this.h=new ja;this.l=null;this.xa=1;this.c={};this.S=new H;this.ua=0;this.R=null;this.ca=this.ta=!1;this.s={};this.L=this.C=this.aa=null;this.B={}}p(Y,F);m("shaka.player.StreamVideoSource",Y);
Y.prototype.za=function(a){null!=a.streamBufferSize&&(this.B.streamBufferSize=a.streamBufferSize);null!=a.segmentRequestTimeout&&(this.B.segmentRequestTimeout=a.segmentRequestTimeout);se(this);null!=a.enableAdaptation&&this.o.enable(Boolean(a.enableAdaptation));null!=a.mpdRequestTimeout&&(this.va=Number(a.mpdRequestTimeout));null!=a.preferredLanguage&&(this.u=$a(String(a.preferredLanguage)));null!=a.restrictions&&(this.h=a.restrictions,this.w&&te(this))};
Y.prototype.destroy=function(){this.i.destroy();this.S.destroy();this.S=this.i=null;this.C&&(window.clearTimeout(this.C),this.C=null);this.aa&&(window.clearTimeout(this.aa),this.aa=null);this.s=null;this.j.destroy();this.j=null;db(this.c).forEach(function(a){a.destroy()});this.b=this.c=null;this.a&&(this.a.destroy(),this.a=null);this.o.destroy();this.v=this.h=this.A=this.f=this.g=this.V=this.o=null};
Y.prototype.$=function(){if(this.w){var a=Error("Cannot call load() right now.");a.type="app";return Promise.reject(a)}if(!this.a||0==this.a.periodInfos.length)return a=Error("The manifest does not specify any content."),a.type="stream",Promise.reject(a);if(this.a.a)return a=Error("Live manifest support not enabled."),a.type="app",Promise.reject(a);for(var a=this.a.periodInfos,b=0;b<a.length;++b)for(var c=a[b],d=0;d<c.streamSetInfos.length;++d){for(var e=c.streamSetInfos[d],f=e,g=0;g<f.streamInfos.length;++g)Zd(sd(f.streamInfos[g]))||
(f.streamInfos.splice(g,1),--g);0==e.streamInfos.length&&(c.streamSetInfos.splice(d,1),--d)}for(b=0;b<a.length;++b)for(c=a[b],d=0;d<c.streamSetInfos.length;++d)c.streamSetInfos[d].streamInfos.sort(qe);if(0==this.a.periodInfos.length||0==this.a.periodInfos[0].streamSetInfos.length)return a=Error("The manifest specifies content that cannot be displayed on this browser/platform."),a.type="stream",Promise.reject(a);this.w=!0;this.B.initialStreamBufferSize=this.a.b;se(this);te(this);return Promise.resolve()};
Y.prototype.K=function(){if(!this.b.a.hasOwnProperty("video"))return[];for(var a=this.c.video,a=(a=a?a.fa():null)?a.a:0,b=[],c=this.b.get("video"),d=0;d<c.length;++d)for(var e=c[d],f=0;f<e.streamInfos.length;++f){var g=e.streamInfos[f];if(g.F&&g.b){var h=g.a,g=new ra(h,g.bandwidth,g.width,g.height);h==a&&(g.active=!0);b.push(g)}}return b};Y.prototype.getVideoTracks=Y.prototype.K;
Y.prototype.U=function(){if(!this.b.a.hasOwnProperty("audio"))return[];for(var a=this.c.audio,a=(a=a?a.fa():null)?a.a:0,b=[],c=this.b.get("audio"),d=0;d<c.length;++d)for(var e=c[d],f=e.lang,g=0;g<e.streamInfos.length;++g){var h=e.streamInfos[g];if(h.F&&h.b){var l=h.a,h=new ia(l,h.bandwidth,f);l==a&&(h.active=!0);b.push(h)}}return b};Y.prototype.getAudioTracks=Y.prototype.U;
Y.prototype.ra=function(){if(!this.b.a.hasOwnProperty("text"))return[];for(var a=this.c.text,b=a?a.fa():null,b=b?b.a:0,c=[],d=this.b.get("text"),e=0;e<d.length;++e)for(var f=d[e],g=f.lang,h=0;h<f.streamInfos.length;++h){var l=f.streamInfos[h].a,n=new qa(l,g);l==b&&(n.active=!0,n.enabled=a.la());c.push(n)}return c};Y.prototype.getTextTracks=Y.prototype.ra;
function $d(a,b){if(a.w){for(var c={},d=a.a.periodInfos[0],e=0;e<d.streamSetInfos.length;++e){var f=d.streamSetInfos[e];c[f.a]=f}a.b.a={};d=kb(b);for(e=0;e<d.length;++e){var f=d[e],g=b.get(f);if("video"==f){var h=g[0].id;a.b.push(f,c[h])}else if("audio"==f)for(var h=g[0].b.split(";")[0],l=0;l<g.length;++l){var n=g[l];n.b.split(";")[0]==h&&a.b.push(f,c[n.id])}else for(l=0;l<g.length;++l)h=g[l].id,a.b.push(f,c[h])}a.W=!0;if(c=a.b.get("audio"))ue(a,c),a.b.set("audio",c),c=c[0].lang||a.u,Za(2,a.u,c)&&
(a.W=!1);if(c=a.b.get("text"))ue(a,c),a.b.set("text",c),c=c[0].lang||a.u,Za(2,a.u,c)||(a.W=!1)}}Y.prototype.selectVideoTrack=function(a,b,c){return oe(this,"video",a,b,c)};function pe(a,b){var c=a.c.text;c&&c.ga(b)}
function te(a){if(a.h){for(var b=!1,c=0;c<a.a.periodInfos.length;++c)for(var d=a.a.periodInfos[c],e=0;e<d.streamSetInfos.length;++e){var f=d.streamSetInfos[e];if("video"==f.contentType)for(var g=0;g<f.streamInfos.length;++g){var h=f.streamInfos[g],l=h.b;h.b=!0;a.h.maxWidth&&h.width>a.h.maxWidth&&(h.b=!1);a.h.maxHeight&&h.height>a.h.maxHeight&&(h.b=!1);a.h.minHeight&&h.height<a.h.minHeight&&(h.b=!1);a.h.maxBandwidth&&h.bandwidth>a.h.maxBandwidth&&(h.b=!1);a.h.minBandwidth&&h.bandwidth<a.h.minBandwidth&&
(h.b=!1);l!=h.b&&(b=!0)}}0!=hb(a.b).length&&b&&(ve(a),0<a.K().length||(b=Error("The application has restricted all video tracks!"),b.type="app",b=y(b),a.dispatchEvent(b)))}}
function ge(a,b){for(var c,d=!1,e=new C,f=hb(a.b),g=0;g<f.length;++g)for(var h=f[g],l=0;l<h.streamInfos.length;++l){var n=h.streamInfos[l];n.g.forEach(function(a){e.push(a,n)})}for(c in b)if(f=Wa[b[c]]||null,h=e.get(c))for(g=0;g<h.length;++g)n=h[g],l=n.F,n.F=!f,l!=n.F&&(d=!0);else ob(c);d&&(ve(a),d=a.U(),c=a.K(),d=a.b.a.hasOwnProperty("audio")&&0==d.length,c=a.b.a.hasOwnProperty("video")&&0==c.length,d||c)&&(c=Error("The key system has restricted all "+(d&&c?"audio and video tracks.":d?"audio tracks.":
"video tracks.")),c.type="drm",c=y(c),a.dispatchEvent(c))}function ve(a){var b=x({type:"trackschanged",bubbles:!0});a.dispatchEvent(b)}function oe(a,b,c,d,e){if(!a.b.a.hasOwnProperty(b)||!a.c[b])return!1;for(var f=a.b.get(b),g=0;g<f.length;++g)for(var h=f[g],l=0;l<h.streamInfos.length;++l){var n=h.streamInfos[l];if(n.a==c){if(!n.F||!n.b)return!1;if("text"!=b&&!a.ca)return c=a.s[b],a.s[b]={Ja:n,Aa:null!=c&&c.Aa||d,Ba:null!=c&&c.Ba||e},!0;Vd(a.A,n);a.c[b].ha(n,d,e);return!0}}return!1}
function ue(a,b){for(var c=0;2>=c;++c)for(var d=0;d<b.length;++d){var e=b[d];if(Za(c,a.u,e.lang)){b.splice(d,1);b.splice(0,0,e);return}}for(d=0;d<b.length;++d)if(e=b[d],e.c){b.splice(d,1);b.splice(0,0,e);break}}k=Y.prototype;k.Sa=function(){this.j.ba(this.g,"sourceopen");we(this).then(I(this,function(){this.i&&this.i.resolve()})).catch(I(this,function(a){this.i&&this.i.reject(a)}))};
function we(a){for(var b=[],c=["audio","video","text"],d=0;d<c.length;++d){var e=c[d];a.b.a.hasOwnProperty(e)&&b.push(a.b.get(e)[0])}for(var f=xe(a,b),d=0;d<c.length;++d)if(e=c[d],a.b.a.hasOwnProperty(e)&&!f[e])return a=Error("Unable to select an initial "+e+" stream: all "+e+" streams have been restricted (by the application or by the key system)."),a.type="stream",Promise.reject(a);b=db(f).map(function(a){return a.segmentIndexSource.create()});return Promise.all(b).then(I(a,function(a){if(!a.every(function(a){return a.length()}))return a=
Error("Some streams are not available."),a.type="stream",Promise.reject(a);a=ye(this,a);if(!a)return a=Error("Some streams are not available."),a.type="stream",Promise.reject(a);if(!ze(this,f))return a=Error("Failed to create Stream objects."),a.type="stream",Promise.reject(a);this.o.start();Ae(this,f,a);return Promise.resolve()})).catch(I(a,function(a){if("aborted"!=a.type)return Object.keys(this.c),this.a.a?(Date.now()+Qa<this.a.c?this.nb():this.Oa(0),Promise.resolve()):Promise.reject(a)}))}
function xe(a,b){for(var c={},d=0;d<b.length;++d){var e=b[d],f=null;if("video"==e.contentType){var g=a.o.getInitialVideoTrackId();if(null==g)continue;f=e.streamInfos.filter(function(a){return a.a==g});if(0==f.length)continue;f=f[0]}else if("audio"==e.contentType){f=e.streamInfos.filter(function(a){return a.F&&a.b});if(0==f.length)continue;f=e.streamInfos[Math.floor(f.length/2)]}else 0<e.streamInfos.length&&(f=e.streamInfos[0]);c[e.contentType]=f}return c}
function ze(a,b){var c={},d;for(d in b){var e=b[d],e="text"==d?new Id(a,a.f):Be(a,e);if(!e)return db(c).forEach(function(a){a.destroy()}),!1;c[d]=e}a.c=c;return!0}function Be(a,b){var c=new zd(a,a.f,a.g,sd(b),a.V);c.A(a.B);return c}
function Ae(a,b,c){a.xa=a.f.playbackRate;a.f.playbackRate=0;Ce(a,c);var d;a.L&&a.L<=c.end&&a.L>=c.start?d=a.L:a.a.a?(d=c.end,a.ta=!0):d=c.start;E(a.j,a.f,"seeking",a.$a.bind(a));a.f.currentTime!=d&&(a.f.currentTime=d,a.l=d);De(a,c.start,c.end);c=[];for(var e in a.c){d=a.c[e];c.push(d.Ia(a.S));E(a.j,d,"ended",a.ab.bind(a));var f=b[e];Vd(a.A,f);d.ha(f,!1)}Promise.all(c).then(a.Pa.bind(a)).catch(I(a,function(a){"destroy"!=a.type&&(a=y(a),this.dispatchEvent(a))}));pe(a,a.W)}
k.Pa=function(a){ba(a&&a.length==Object.keys(this.c).length);for(var b=Number.POSITIVE_INFINITY,c=Number.NEGATIVE_INFINITY,d=0;d<a.length;++d)var e=a[d],b=Math.min(b,e),c=Math.max(c,e);a=Ee(this);for(d=0;d<a.length;++d)pd(a[d],c);Fe(this,a,c);d=hb(this.b).map(function(a){return a.streamInfos}).reduce(function(a,b){return a.concat(b)},[]).map(function(a){var b=[a.segmentIndexSource.create()];a.N&&b.push(a.N.create());return Promise.all(b)});Promise.all(d).then(I(this,function(a){for(var b=0;b<a.length;++b)pd(a[b][0],
c);this.ca=!0;for(var d in this.s)a=this.s[d],b=this.c[d],Vd(this.A,a.Ja),b.ha(a.Ja,a.Aa,a.Ba);this.s={}})).catch(I(this,function(a){"aborted"!=a.type&&(a=y(a),this.dispatchEvent(a))}))};function Fe(a,b,c){if(b=ye(a,b))Ce(a,b),De(a,b.start,b.end);0!=c&&(c=a.f.currentTime+c,a.f.currentTime=c,a.l=c);a.ta&&b&&(a.f.currentTime=b.end);a.f.playbackRate=a.xa;a.a.a&&null!=a.a.f&&a.Oa(0);Ge(a);a.S.resolve()}
function Ce(a,b){if(a.a.a)isNaN(a.g.duration)&&(a.g.duration=b.end+2592E3);else if(isNaN(a.g.duration)||b.end>a.g.duration){a.g.duration=b.end;for(var c=0;c<a.g.sourceBuffers.length;++c)a.g.sourceBuffers[c].appendWindowEnd=b.end}}k.cb=function(){this.C=null;Ge(this);var a=ye(this,Ee(this));a&&(this.a.a&&this.ua!=a.X&&(this.ua=a.X,null!=this.R&&(window.clearTimeout(this.R),this.R=null)),De(this,a.start,a.end),this.f.paused||He(this,this.f.currentTime,a.start,a.end))};
function De(a,b,c){b=x({type:"seekrangechanged",bubbles:!0,start:b,end:c});a.dispatchEvent(b)}k.$a=function(){var a=this.f.currentTime;if(null!=this.l){if(a>=this.l-.01&&a<=this.l+.01){this.l=null;return}this.l=null}var b=ye(this,Ee(this));if(b){var c=b.end;(b=He(this,a,b.start,c))||(a<=c+.01?b=!1:(this.f.currentTime=c,b=!0));if(!b)for(var d in this.c)this.c[d].Fa()}};
function He(a,b,c,d){if(b>=c-.01)return!1;b=0;if(a.a.a){b=.5;for(var e in a.c)if(!a.c[e].Ga(c+b)){b=a.a.b;break}}a.f.currentTime=Math.min(c+b,d);return!0}k.ab=function(){if(!this.a.a){for(var a in this.c)if(!this.c[a].Da())return;this.R=null;this.g.endOfStream()}};k.kb=function(){var a=this.A,b=this.V.getBandwidth();a.estimatedBandwidth=b;a.bandwidthHistory.push(new Xd(b))};function Ee(a){return db(a.c).map(function(a){return a.Ca()}).filter(function(a){return null!=a})}
function ye(a,b){for(var c=0,d=Number.POSITIVE_INFINITY,e=Number.POSITIVE_INFINITY,f=0;f<b.length;++f){var g;g=b[f];g=0<g.length()?{start:nd(g).startTime,end:g.X().endTime}:{start:0,end:0};c=Math.max(c,g.start);null!=g.end&&(d=Math.min(d,g.end));b[f].length()&&(e=Math.min(e,b[f].X().endTime))}if(d==Number.POSITIVE_INFINITY)if(d=a.a.periodInfos[0],d.a)d=(d.start||0)+d.a;else return null;a.a.a&&(d=Math.max(d-a.a.b,c));return c>d?null:{start:c,end:d,X:e}}
function Ge(a){a.a.a&&(a.C=window.setTimeout(a.cb.bind(a),1E3))}function se(a){for(var b in a.c)a.c[b].A(a.B)};function Z(a,b,c,d){c||(c=new G);d||(d=new X);Y.call(this,null,c,d);this.wa=a;this.ya=b;this.Z=[];this.da=[];this.sa=[];this.T=null}p(Z,Y);m("shaka.player.DashVideoSource",Z);Z.prototype.La=function(){return this.wa};Z.prototype.getUrl=Z.prototype.La;Z.prototype.Ka=function(){return this.a};Z.prototype.getManifestInfo=Z.prototype.Ka;Z.prototype.Ma=function(a,b,c){this.Z.push(a);this.da.push(b||"");this.sa.push(c||"")};Z.prototype.addExternalCaptions=Z.prototype.Ma;
Z.prototype.Na=function(a){this.T=a};Z.prototype.setNetworkCallback=Z.prototype.Na;Z.prototype.destroy=function(){this.T=this.ya=null;Y.prototype.destroy.call(this)};
Z.prototype.$=function(){var a=new J(this.T,[new K(this.wa)]);return(new hd(a,this.va)).send().then(I(this,function(a){for(var c=0;c<this.Z.length;c++){var d=a,e=this.Z[c],f=this.da[c],g=this.sa[c];if(0!==d.a.length){var h=new zc;h.contentType="text";h.lang=f||"en";h.c=!0;f=new Cc;f.bandwidth=0;f.b=g||"text/vtt";f.m=[new K(e)];h.a.push(f);d.a[0].a.push(h);Vc(d.a[0])}}if("dynamic"==a.type)return a=Error("Live manifest support not enabled."),a.type="app",Promise.reject(a);c=new Kd(this.ya);d=this.T;
e=(Date.now()+Qa)/1E3;for(g=0;g<a.a.length;++g)for(h=a.a[g],f=0;f<h.a.length;++f){var l=h.a[f];if("text"!=l.contentType)for(var n=0;n<l.a.length;++n){var r=l.a[n],t=0,t=t+(r.c?1:0),t=t+(r.f?1:0),t=t+(r.g?1:0);0==t?(l.a.splice(n,1),--n):1!=t&&(r.c?(r.f=null,r.g=null):r.f&&(r.g=null))}}Ld(a);for(g=0;g<a.a.length;++g)for(h=a.a[g],f=0;f<h.a.length;++f){n=l=h.a[f];r=null;for(t=0;t<n.a.length;++t){var B=n.a[t].b||"";r?B!=r&&(n.a.splice(t,1),--t):r=B}0==l.a.length&&(h.a.splice(f,1),--f)}"dynamic"==a.type&&
null==a.c&&(a.c=e);e=new yd;"dynamic"==a.type&&(e.a=!0,e.f=a.f,e.g=new J(d,a.j||a.url),e.c=a.c);e.b=a.g||5;for(g=0;g<a.a.length;++g){h=a.a[g];if(null==h.start)break;h=Md(c,h,d);e.periodInfos.push(h)}this.a=e;return Y.prototype.$.call(this)}))};}.bind(g,this))();
if (typeof(module)!="undefined"&&module.exports)module.exports=g.shaka;
else if (typeof(define)!="undefined" && define.amd)define(function(){return g.shaka});
else this.shaka=g.shaka;
})();

