(function(){var g={};
(function(window){var l,aa=this;function n(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function p(a,b){function c(){}c.prototype=b.prototype;a.Cb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ab=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};/*

 Copyright 2015 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function ba(){};function ca(a){var b=console[a];b?b.bind||(console[a]=function(){b.apply(console,arguments)}):console[a]=function(){}}ca("error");ca("warn");ca("info");ca("log");ca("debug");function da(a){ea[a]={fa:fa(),end:NaN}}function ga(a){if(a=ea[a])a.end=fa()}function ha(a){return(a=ea[a])&&a.end?a.end-a.fa:NaN}var fa=window.performance&&window.performance.now?window.performance.now.bind(window.performance):Date.now,ea={};function ia(a,b,c){this.id=a;this.bandwidth=b||0;this.lang=c||"unknown";this.active=!1}n("shaka.player.AudioTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0});function ja(){this.minBandwidth=this.maxBandwidth=this.maxWidth=this.minHeight=this.maxHeight=null}ja.prototype.clone=function(){var a=new ja;a.maxHeight=this.maxHeight;a.minHeight=this.minHeight;a.maxWidth=this.maxWidth;a.maxBandwidth=this.maxBandwidth;a.minBandwidth=this.minBandwidth;return a};function r(){this.fontSize="100%";this.fontColor=ka;this.fontOpacity=la;this.backgroundColor=ma;this.backgroundOpacity=la;this.fontEdge=na}n("shaka.player.TextStyle",r);r.prototype.a=function(){var a=window.localStorage.getItem("ShakaPlayerTextStyle");if(a){var b;try{b=JSON.parse(a)}catch(c){return}if(b&&"object"==typeof b){var a=b,d;for(d in a)d in this&&(this[d]=a[d])}}};r.prototype.load=r.prototype.a;r.prototype.b=function(){window.localStorage.setItem("ShakaPlayerTextStyle",JSON.stringify(this))};
r.prototype.store=r.prototype.b;function oa(a){var b=[];b.push("font-size: "+a.fontSize);b.push("color: "+pa(a.fontColor,a.fontOpacity));b.push("background-color: "+pa(a.backgroundColor,a.backgroundOpacity));for(var c=[],d=0;d<a.fontEdge.length;++d){var e=a.fontEdge[d].slice(3,6);c.push(pa(a.fontEdge[d].slice(0,3),a.fontOpacity)+" "+e.join("px ")+"px")}b.push("text-shadow: "+c.join(","));return b.join("; ")}function pa(a,b){return"rgba("+a.concat(b).join(",")+")"}var ka=[255,255,255],ma=[0,0,0];
r.StandardColors={WHITE:ka,BLACK:ma,RED:[255,0,0],GREEN:[0,255,0],BLUE:[0,0,255],YELLOW:[255,255,0],MAGENTA:[255,0,255],CYAN:[0,255,255]};var la=1;r.StandardOpacities={OPAQUE:la,SEMI_HIGH:.75,SEMI_LOW:.25,TRANSPARENT:0};var na=[];
r.EdgeStyles={NONE:na,RAISED:[[34,34,34,1,1,0],[34,34,34,2,2,0],[34,34,34,3,3,0]],DEPRESSED:[[204,204,204,1,1,0],[204,204,204,0,1,0],[34,34,34,-1,-1,0],[34,34,34,0,-1,0]],UNIFORM:[[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4]],DROP:[[34,34,34,2,2,3],[34,34,34,2,2,4],[34,34,34,2,2,5]]};function qa(a,b){this.id=a;this.lang=b||"unknown";this.enabled=this.active=!1}n("shaka.player.TextTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:0});function ra(a,b,c,d){this.id=a;this.bandwidth=b||0;this.width=c||0;this.height=d||0;this.active=!1}function sa(a,b){var c=a.width*a.height,d=b.width*b.height;return c<d?-1:c>d?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0}n("shaka.player.VideoTrack.compare",sa);function ta(){var a="CustomEvent"in window;if(a)try{new CustomEvent("")}catch(b){a=!1}a||(window.CustomEvent=ua)}n("shaka.polyfill.CustomEvent.install",ta);function ua(a,b){var c=document.createEvent("CustomEvent"),d=b||{bubbles:!1,cancelable:!1,detail:null};c.initCustomEvent(a,!!d.bubbles,!!d.cancelable,d.detail);return c};function va(){var a=Element.prototype;a.requestFullscreen=a.requestFullscreen||a.mozRequestFullScreen||a.msRequestFullscreen||a.webkitRequestFullscreen;a=Document.prototype;a.exitFullscreen=a.exitFullscreen||a.mozCancelFullScreen||a.msExitFullscreen||a.webkitExitFullscreen;"fullscreenElement"in document||Object.defineProperty(document,"fullscreenElement",{get:function(){return document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement}});document.addEventListener("webkitfullscreenchange",
wa);document.addEventListener("webkitfullscreenerror",wa);document.addEventListener("mozfullscreenchange",wa);document.addEventListener("mozfullscreenerror",wa);document.addEventListener("MSFullscreenChange",wa);document.addEventListener("MSFullscreenError",wa)}n("shaka.polyfill.Fullscreen.install",va);function wa(a){var b=a.type.replace(/^(webkit|moz|MS)/,"").toLowerCase(),b=new Event(b,a);a.target.dispatchEvent(b)};function xa(){return Promise.reject(Error("The key system specified is not supported."))}function ya(a){return null==a?Promise.resolve():Promise.reject(Error("MediaKeys not supported."))}function za(){throw new TypeError("Illegal constructor.");}za.prototype.createSession=function(){};za.prototype.setServerCertificate=function(){};function Aa(){throw new TypeError("Illegal constructor.");}Aa.prototype.getConfiguration=function(){};Aa.prototype.createMediaKeys=function(){};function t(a){this.c=[];this.b=[];this.S=Ba;if(a)try{a(this.N.bind(this),this.a.bind(this))}catch(b){this.a(b)}}var Ba=0;function Ca(){window.Promise||(window.Promise=t,window.Promise.resolve=Da,window.Promise.reject=Ea,window.Promise.all=Fa,window.Promise.race=Ga,window.setImmediate?(Ha=function(a){return window.setImmediate(a)},Ia=function(a){return window.clearImmediate(a)}):(Ha=function(a){return window.setTimeout(a,0)},Ia=function(a){return window.clearTimeout(a)}))}
n("shaka.polyfill.Promise.install",Ca);function Da(a){var b=new t;b.N(a);return b}function Ea(a){var b=new t;b.a(a);return b}function Fa(a){function b(a,b,c){a.S==Ba&&(e[b]=c,d++,d==e.length&&a.N(e))}var c=new t;if(!a.length)return c.N([]),c;for(var d=0,e=Array(a.length),f=c.a.bind(c),g=0;g<a.length;++g)a[g]&&a[g].then?a[g].then(b.bind(null,c,g),f):b(c,g,a[g]);return c}function Ga(a){for(var b=new t,c=b.N.bind(b),d=b.a.bind(b),e=0;e<a.length;++e)a[e]&&a[e].then?a[e].then(c,d):c(a[e]);return b}
t.prototype.then=function(a,b){var c=new t;switch(this.S){case 1:Ja(this,c,a);break;case 2:Ja(this,c,b);break;case Ba:this.c.push({wa:c,qa:a}),this.b.push({wa:c,qa:b})}return c};t.prototype.then=t.prototype.then;t.prototype.catch=function(a){return this.then(void 0,a)};t.prototype["catch"]=t.prototype.catch;t.prototype.N=function(a){if(this.S==Ba){this.oa=a;this.S=1;for(a=0;a<this.c.length;++a)Ja(this,this.c[a].wa,this.c[a].qa);this.c=[];this.b=[]}};
t.prototype.a=function(a){if(this.S==Ba){this.oa=a;this.S=2;for(a=0;a<this.b.length;++a)Ja(this,this.b[a].wa,this.b[a].qa);this.c=[];this.b=[]}};function Ja(a,b,c){Ka.push(function(){if(c&&"function"==typeof c){try{var a=c(this.oa)}catch(e){b.a(e);return}a instanceof t?a==b?b.a(new TypeError("Chaining cycle detected")):a.then(b.N.bind(b),b.a.bind(b)):b.N(a)}else 1==this.S?b.N(this.oa):b.a(this.oa)}.bind(a));null==La&&(La=Ha(Ma))}
function Ma(){for(;Ka.length;){null!=La&&(Ia(La),La=null);var a=Ka;Ka=[];for(var b=0;b<a.length;++b)a[b]()}}function Ha(){return 0}function Ia(){}var La=null,Ka=[];function Na(){var a=HTMLVideoElement.prototype;!a.getVideoPlaybackQuality&&"webkitDroppedFrameCount"in a&&(a.getVideoPlaybackQuality=Oa)}n("shaka.polyfill.VideoPlaybackQuality.install",Na);function Oa(){return{droppedVideoFrames:this.webkitDroppedFrameCount,totalVideoFrames:this.webkitDecodedFrameCount,corruptedVideoFrames:0,creationTime:NaN,totalFrameDelay:0}};function Pa(a,b){for(var c=[],d=0;d<a.length;++d){for(var e=!1,f=0;f<c.length&&!(e=b?b(a[d],c[f]):a[d]===c[f]);++f);e||c.push(a[d])}return c};function u(){return Date.now()+Qa}var Qa=0;function Ra(a){this.b=a;this.c=0==Sa;this.a=0}var Sa=1;function Ta(a){var b=a.b.getUint32(a.a,a.c);a.a+=4;return b}function Ua(a){if(a.a+16>a.b.byteLength)throw new RangeError("DataViewReader: Read past end of DataView.");var b=new Uint8Array(a.b.buffer,a.a,16);a.a+=16;return b}function Va(a,b){if(a.a+b>a.b.byteLength)throw new RangeError("DataViewReader: Skip past end of DataView.");a.a+=b};var Wa={"output-restricted":"The required output protection is not available.","output-not-allowed":"The required output protection is not available.",expired:"The decryption key has expired.","internal-error":"The key system has encountered an unspecified error."};function Xa(a){this.c=Math.exp(Math.log(.5)/a);this.a=this.b=0}Xa.prototype.sample=function(a,b){var c=Math.pow(this.c,a);this.b=b*(1-c)+c*this.b;this.a+=a};function Ya(a){return a.b/(1-Math.pow(a.c,a.a))};function v(a){var b=new CustomEvent(a.type,{detail:a.detail,bubbles:!!a.bubbles}),c;for(c in a)c in b||(b[c]=a[c]);return b}function x(a){return new CustomEvent("error",{detail:a,bubbles:!0})};function Za(a,b){var c=window.hola_cdn&&window.hola_cdn.api;if(c&&c[a])return c[a].apply(c,Array.prototype.slice.call(arguments,1))};function $a(a,b,c){ab(b);ab(c);return c==b||a>=bb&&c==b.split("-")[0]||a>=cb&&c.split("-")[0]==b.split("-")[0]?!0:!1}var bb=1,cb=2;function ab(a){a=a.toLowerCase().split("-");var b=db[a[0]];b&&(a[0]=b);return a.join("-")}
var db={aar:"aa",abk:"ab",afr:"af",aka:"ak",alb:"sq",amh:"am",ara:"ar",arg:"an",arm:"hy",asm:"as",ava:"av",ave:"ae",aym:"ay",aze:"az",bak:"ba",bam:"bm",baq:"eu",bel:"be",ben:"bn",bih:"bh",bis:"bi",bod:"bo",bos:"bs",bre:"br",bul:"bg",bur:"my",cat:"ca",ces:"cs",cha:"ch",che:"ce",chi:"zh",chu:"cu",chv:"cv",cor:"kw",cos:"co",cre:"cr",cym:"cy",cze:"cs",dan:"da",deu:"de",div:"dv",dut:"nl",dzo:"dz",ell:"el",eng:"en",epo:"eo",est:"et",eus:"eu",ewe:"ee",fao:"fo",fas:"fa",fij:"fj",fin:"fi",fra:"fr",fre:"fr",
fry:"fy",ful:"ff",geo:"ka",ger:"de",gla:"gd",gle:"ga",glg:"gl",glv:"gv",gre:"el",grn:"gn",guj:"gu",hat:"ht",hau:"ha",heb:"he",her:"hz",hin:"hi",hmo:"ho",hrv:"hr",hun:"hu",hye:"hy",ibo:"ig",ice:"is",ido:"io",iii:"ii",iku:"iu",ile:"ie",ina:"ia",ind:"id",ipk:"ik",isl:"is",ita:"it",jav:"jv",jpn:"ja",kal:"kl",kan:"kn",kas:"ks",kat:"ka",kau:"kr",kaz:"kk",khm:"km",kik:"ki",kin:"rw",kir:"ky",kom:"kv",kon:"kg",kor:"ko",kua:"kj",kur:"ku",lao:"lo",lat:"la",lav:"lv",lim:"li",lin:"ln",lit:"lt",ltz:"lb",lub:"lu",
lug:"lg",mac:"mk",mah:"mh",mal:"ml",mao:"mi",mar:"mr",may:"ms",mkd:"mk",mlg:"mg",mlt:"mt",mon:"mn",mri:"mi",msa:"ms",mya:"my",nau:"na",nav:"nv",nbl:"nr",nde:"nd",ndo:"ng",nep:"ne",nld:"nl",nno:"nn",nob:"nb",nor:"no",nya:"ny",oci:"oc",oji:"oj",ori:"or",orm:"om",oss:"os",pan:"pa",per:"fa",pli:"pi",pol:"pl",por:"pt",pus:"ps",que:"qu",roh:"rm",ron:"ro",rum:"ro",run:"rn",rus:"ru",sag:"sg",san:"sa",sin:"si",slk:"sk",slo:"sk",slv:"sl",sme:"se",smo:"sm",sna:"sn",snd:"sd",som:"so",sot:"st",spa:"es",sqi:"sq",
srd:"sc",srp:"sr",ssw:"ss",sun:"su",swa:"sw",swe:"sv",tah:"ty",tam:"ta",tat:"tt",tel:"te",tgk:"tg",tgl:"tl",tha:"th",tib:"bo",tir:"ti",ton:"to",tsn:"tn",tso:"ts",tuk:"tk",tur:"tr",twi:"tw",uig:"ug",ukr:"uk",urd:"ur",uzb:"uz",ven:"ve",vie:"vi",vol:"vo",wel:"cy",wln:"wa",wol:"wo",xho:"xh",yid:"yi",yor:"yo",zha:"za",zho:"zh",zul:"zu"};function eb(a){return Object.keys(a).map(function(b){return a[b]})}function fb(a,b){return gb(a,b,"boolean")}function hb(a,b){var c=gb(a,b,"number");if(null==c)return null;if(isNaN(c)||c==Number.NEGATIVE_INFINITY||c==Number.POSITIVE_INFINITY)throw new RangeError("'"+b+"' must be finite.");if(0>c)throw new RangeError("'"+b+"' must be >= 0");return c}function y(a,b){return gb(a,b,"string")}
function gb(a,b,c){a=a[b];if(null==a)return null;if(typeof a!=c)throw new TypeError("'"+b+"' must be a "+c+".");return a}function ib(a,b,c){a=a[b];if(null==a)return null;if(!(a instanceof c))throw new TypeError("'"+b+"' must be an instance of "+c.name+".");return a};function z(){this.a={}}z.prototype.push=function(a,b){this.a.hasOwnProperty(a)?this.a[a].push(b):this.a[a]=[b]};z.prototype.set=function(a,b){this.a[a]=b};z.prototype.get=function(a){return(a=this.a[a])?a.slice():null};function jb(a){var b=[],c;for(c in a.a)b.push.apply(b,a.a[c]);return b}function kb(a,b,c){if(a=a.a[b])for(b=0;b<a.length;++b)a[b]==c&&(a.splice(b,1),--b)}function A(a){var b=[],c;for(c in a.a)b.push(c);return b};function B(){this.a=new z}B.prototype.destroy=function(){lb(this);this.a=null};function C(a,b,c,d){b=new mb(b,c,d);a.a.push(c,b)}B.prototype.ja=function(a,b){for(var c=this.a.get(b)||[],d=0;d<c.length;++d){var e=c[d];e.target==a&&(e.ja(),kb(this.a,b,e))}};function lb(a){for(var b=jb(a.a),c=0;c<b.length;++c)b[c].ja();a.a.a={}}function mb(a,b,c){this.target=a;this.type=b;this.a=c;this.target.addEventListener(b,c,!1)}
mb.prototype.ja=function(){this.target&&(this.target.removeEventListener(this.type,this.a,!1),this.a=this.target=null)};function E(a){this.pa=new z;this.w=a}n("shaka.util.FakeEventTarget",E);E.prototype.addEventListener=function(a,b,c){c||this.pa.push(a,b)};E.prototype.removeEventListener=function(a,b,c){c||kb(this.pa,a,b)};
E.prototype.dispatchEvent=function(a){a.hasOwnProperty("srcElement")||(delete a.srcElement,Object.defineProperty(a,"srcElement",{get:function(){return null}}));if(a.hasOwnProperty("target"))a.target=this;else{delete a.target;var b=this;Object.defineProperty(a,"target",{get:function(){return b},set:function(a){b=a}})}if(a.hasOwnProperty("currentTarget"))a.currentTarget=null;else{delete a.currentTarget;var c=null;Object.defineProperty(a,"currentTarget",{get:function(){return c},set:function(a){c=a}})}return nb(this,
a)};function nb(a,b){b.currentTarget=a;for(var c=a.pa.get(b.type)||[],d=0;d<c.length;++d){var e=c[d];try{e.handleEvent?e.handleEvent(b):e.call(a,b)}catch(f){}}a.w&&b.bubbles&&nb(a.w,b);return b.defaultPrevented};function ob(){E.call(this,null);this.a=new Xa(3);this.c=new Xa(10);this.b=0}p(ob,E);n("shaka.util.EWMABandwidthEstimator",ob);ob.prototype.sample=function(a,b){if(!(65536>b)){a=Math.max(a,50);var c=8E3*b/a,d=a/1E3;this.a.sample(d,c);this.c.sample(d,c);this.dispatchEvent(v({type:"bandwidth"}));this.b=Date.now()}};ob.prototype.getBandwidth=function(){return.5>this.a.a?5E5:Math.min(Ya(this.a),Ya(this.c))};ob.prototype.getDataAge=function(){return(Date.now()-this.b)/1E3};
ob.prototype.supportsCaching=function(){return!1};function F(){var a,b,c=new Promise(function(c,e){a=c;b=e});c.resolve=a;c.reject=b;c.destroy=F.prototype.destroy;return c}F.prototype.destroy=function(){this.catch(function(){});var a=Error("Destroyed!");a.type="destroy";this.reject(a)};function pb(a){a.split("").reduce(function(a,c,d){return a+(d&&0==d%4?" "+c:c)})};function qb(){this.g=new F;this.f=!1;this.a=null;this.b=[];this.c=null}function rb(a,b){if(a.f)throw Error("Cannot append to a running task!");a.b.push(b)}qb.prototype.start=function(){if(this.f)throw Error("Task already started!");this.f=!0;this.b.unshift(function(){});sb(this,void 0)};qb.prototype.end=function(){this.b.splice(1)};
function sb(a,b){var c=a.b[0](b),d;c?(d=c[0],a.c=c[1]):(d=Promise.resolve(),a.c=null);d.then(G(a,function(a){this.a?(this.b=[],this.c=null,tb(this)):(this.b.shift(),this.b.length?sb(this,a):(this.g.resolve(a),this.c=null))})).catch(G(a,function(a){this.b=[];this.c=null;this.a?tb(this):this.g.reject(a)}))}function tb(a){var b=Error("Task aborted.");b.type="aborted";a.g.reject(b);window.setTimeout(function(){this.a.resolve();this.a=null}.bind(a),5)};function G(a,b){return b.bind(a)};function ub(a,b,c){MediaSource.isTypeSupported(b);b=a.addSourceBuffer(b);this.h=a;this.c=b;this.l=c;this.i=new B;this.s=null;this.b=[];this.w=0;this.f=this.a=null;this.m=0;C(this.i,this.c,"updateend",this.v.bind(this))}var vb=1/60;ub.prototype.destroy=function(){wb(this).catch(function(){});this.f&&this.f.destroy();this.b=this.a=this.f=null;this.i.destroy();this.h=this.c=this.i=null};
function xb(a,b){for(var c=a.c.buffered,d=0;d<c.length;++d){var e=c.start(d)-vb,f=c.end(d)+vb;if(b>=e&&b<=f)return c.end(d)-b}return 0}
ub.prototype.fetch=function(a,b,c){if(this.a)return b=Error("Cannot fetch ("+this.j+"): previous operation not complete."),b.type="stream",Promise.reject(b);this.a=new qb;b!=this.c.timestampOffset&&(this.c.timestampOffset=b);c&&rb(this.a,function(){return[yb(this,c),this.g.bind(this)]}.bind(this));rb(this.a,function(){var b=a.endTime?a.endTime-a.startTime:1,c=new zb;c.a=3;c.h=1E3*b;c.c=1E3*this.m;c.j=this.s;return[a.url.fetch(c,this.l),H.prototype.i.bind(a.url)]}.bind(this));rb(this.a,G(this,function(a){this.l.getBandwidth();
return[yb(this,a),this.g.bind(this)]}));var d=0==this.c.buffered.length&&0==this.b.length,e=null;rb(this.a,function(){if(0==this.c.buffered.length){var b=Error("Failed to buffer segment ("+this.j+").");b.type="stream";return[Promise.reject(b)]}d&&(b=a.startTime,e=this.c.buffered.start(0)-b);b=Ab(this.b,a.startTime);0<=b?this.b.splice(b+1,0,a):this.b.push(a)}.bind(this));return Bb(this).then(function(){return Promise.resolve(e)}.bind(this))};
function Cb(a){if(a.a)return a=Error("Cannot clear ("+a.j+"): previous operation not complete."),a.type="stream",Promise.reject(a);a.a=new qb;rb(a.a,function(){var a;a:if(0==this.c.buffered.length)a=Promise.resolve();else{try{this.c.remove(0,this.h.duration)}catch(c){a=Promise.reject(c);break a}this.b=[];a=this.f=new F}return[a,this.g.bind(this)]}.bind(a));return Bb(a)}
function Db(a,b){if(a.a){var c=Error("Cannot clearAfter ("+a.j+"): previous operation not complete.");c.type="stream";return Promise.reject(c)}a.a=new qb;rb(a.a,function(){return[Eb(this,b),this.g.bind(this)]}.bind(a));return Bb(a)}function wb(a){a.a?(a=a.a,a.a?a=a.a:a.f?(a.c&&a.c(),a.a=new F,a=a.a):(a.f=!0,a=Promise.resolve())):a=Promise.resolve();return a}function Bb(a){a.a.start();return a.a.g.then(G(a,function(){this.a=null})).catch(G(a,function(a){this.a=null;return Promise.reject(a)}))}
function yb(a,b){try{a.c.appendBuffer(b)}catch(c){return Promise.reject(c)}a.f=new F;return a.f}function Eb(a,b){if(0==a.c.buffered.length)return Promise.resolve();var c=Ab(a.b,b);if(-1==c||c==a.b.length-1)return Promise.resolve();try{a.c.remove(a.b[c+1].startTime,a.h.duration)}catch(d){return Promise.reject(d)}a.b=a.b.slice(0,c+1);a.f=new F;return a.f}ub.prototype.g=function(){this.f&&"open"==this.h.readyState&&this.c.abort()};ub.prototype.v=function(){this.f&&(this.f.resolve(),this.f=null)};function Fb(a){return String.fromCharCode.apply(null,a)}n("shaka.util.Uint8ArrayUtils.toString",Fb);function Gb(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;++c)b[c]=a.charCodeAt(c);return b}n("shaka.util.Uint8ArrayUtils.fromString",Gb);n("shaka.util.Uint8ArrayUtils.toBase64",function(a,b){var c=void 0==b?!0:b,d=window.btoa(Fb(a)).replace(/\+/g,"-").replace(/\//g,"_");return c?d:d.replace(/=*$/,"")});function Hb(a){return Gb(window.atob(a.replace(/-/g,"+").replace(/_/g,"/")))}
n("shaka.util.Uint8ArrayUtils.fromBase64",Hb);n("shaka.util.Uint8ArrayUtils.fromHex",function(a){for(var b=new Uint8Array(a.length/2),c=0;c<a.length;c+=2)b[c/2]=window.parseInt(a.substr(c,2),16);return b});function Ib(a){for(var b="",c=0;c<a.length;++c){var d=a[c].toString(16);1==d.length&&(d="0"+d);b+=d}return b}n("shaka.util.Uint8ArrayUtils.toHex",Ib);function Jb(a,b){if(!a&&!b)return!0;if(!a||!b||a.length!=b.length)return!1;for(var c=0;c<a.length;++c)if(a[c]!=b[c])return!1;return!0};function Kb(){this.h=this.a="";this.j=!1;this.w=this.m=null;this.i=this.g=!1;this.l=this.f="";this.c=null;this.b=[]}function Lb(a,b){var c=new Kb;c.a=a.a;c.h=a.h;c.j=a.j;c.m=a.m;c.w=a.w;c.g=a.g;c.i=a.i;c.f=a.f;c.l=a.l;c.c=a.c?new Uint8Array(a.c.buffer):null;Mb(c,a.b);Mb(c,b.b);return c}function Mb(a,b){var c=a.b.concat(b.map(function(a){return{initData:new Uint8Array(a.initData.buffer),initDataType:a.initDataType}}));a.b=Pa(c,Nb)}
function Nb(a,b){return a.initDataType==b.initDataType&&Jb(a.initData,b.initData)};function Ob(a,b){try{var c=new Pb(a,b);return Promise.resolve(c)}catch(d){return Promise.reject(d)}}function Qb(a){var b=this.mediaKeys;b&&b!=a&&Rb(b,null);delete this.mediaKeys;(this.mediaKeys=a)&&Rb(a,this);return Promise.resolve()}
function Pb(a,b){this.a=this.keySystem=a;var c=!0;"org.w3.clearkey"==a&&(this.a="webkit-org.w3.clearkey",c=!1);var d=!1,e;e=document.getElementsByTagName("video");e=e.length?e[0]:document.createElement("video");for(var f=0;f<b.length;++f){var g=b[f],h={audioCapabilities:[],videoCapabilities:[],persistentState:"optional",distinctiveIdentifier:"optional",initDataTypes:g.initDataTypes,sessionTypes:["temporary"]},k=!1;if(g.audioCapabilities)for(var m=0;m<g.audioCapabilities.length;++m){var q=g.audioCapabilities[m];
q.contentType&&(k=!0,e.canPlayType(q.contentType.split(";")[0],this.a)&&(h.audioCapabilities.push(q),d=!0))}if(g.videoCapabilities)for(m=0;m<g.videoCapabilities.length;++m)q=g.videoCapabilities[m],q.contentType&&(k=!0,e.canPlayType(q.contentType,this.a)&&(h.videoCapabilities.push(q),d=!0));k||(d=e.canPlayType("video/mp4",this.a)||e.canPlayType("video/webm",this.a));"required"==g.persistentState&&(c?(h.persistentState="required",h.sessionTypes=["persistent-license"]):d=!1);if(d){this.b=h;return}}c=
"Unsupported keySystem";if("org.w3.clearkey"==a||"com.widevine.alpha"==a)c="None of the requested configurations were supported.";c=Error(c);c.name="NotSupportedError";c.code=DOMException.NOT_SUPPORTED_ERR;throw c;}Pb.prototype.createMediaKeys=function(){var a=new Sb(this.a);return Promise.resolve(a)};Pb.prototype.getConfiguration=function(){return this.b};function Sb(a){this.g=a;this.b=null;this.a=new B;this.c=[];this.f={}}
function Rb(a,b){a.b=b;lb(a.a);b&&(C(a.a,b,"webkitneedkey",a.wb.bind(a)),C(a.a,b,"webkitkeymessage",a.vb.bind(a)),C(a.a,b,"webkitkeyadded",a.tb.bind(a)),C(a.a,b,"webkitkeyerror",a.ub.bind(a)))}l=Sb.prototype;l.createSession=function(a){var b=a||"temporary";if("temporary"!=b&&"persistent-license"!=b)throw new TypeError("Session type "+a+" is unsupported on this platform.");a=this.b||document.createElement("video");a.src||(a.src="about:blank");b=new Tb(a,this.g,b);this.c.push(b);return b};
l.setServerCertificate=function(){return Promise.reject(Error("setServerCertificate not supported on this platform."))};l.wb=function(a){a=v({type:"encrypted",initDataType:"webm",initData:a.initData});this.b.dispatchEvent(a)};l.vb=function(a){var b=Ub(this,a.sessionId);b&&(a=v({type:"message",messageType:void 0==b.keyStatuses.ta()?"licenserequest":"licenserenewal",message:a.message}),b.b&&(b.b.resolve(),b.b=null),b.dispatchEvent(a))};
l.tb=function(a){if(a=Ub(this,a.sessionId))Vb(a,"usable"),a.a&&a.a.resolve(),a.a=null};
l.ub=function(a){var b=Ub(this,a.sessionId);if(b){var c=Error("EME v0.1b key error");c.errorCode=a.errorCode;c.errorCode.systemCode=a.systemCode;!a.sessionId&&b.b?(c.method="generateRequest",45==a.systemCode&&(c.message="Unsupported session type."),b.b.reject(c),b.b=null):a.sessionId&&b.a?(c.method="update",b.a.reject(c),b.a=null):(c=a.systemCode,a.errorCode.code==MediaKeyError.MEDIA_KEYERR_OUTPUT?Vb(b,"output-restricted"):1==c?Vb(b,"expired"):Vb(b,"internal-error"))}};
function Ub(a,b){var c=a.f[b];return c?c:(c=a.c.shift())?(c.sessionId=b,a.f[b]=c):null}function Tb(a,b,c){E.call(this,null);this.f=a;this.h=!1;this.a=this.b=null;this.c=b;this.g=c;this.sessionId="";this.expiration=NaN;this.closed=new F;this.keyStatuses=new Wb}p(Tb,E);
function Xb(a,b,c){if(a.h)return Promise.reject(Error("The session is already initialized."));a.h=!0;var d;try{if("persistent-license"==a.g)if(c)d=Gb("LOAD_SESSION|"+c);else{var e=new Uint8Array(b);d=Gb("PERSISTENT|"+Fb(e))}else d=new Uint8Array(b)}catch(f){return Promise.reject(f)}a.b=new F;try{a.f.webkitGenerateKeyRequest(a.c,d)}catch(g){if("InvalidStateError"!=g.name)return a.b=null,Promise.reject(g);setTimeout(function(){try{this.f.webkitGenerateKeyRequest(this.c,d)}catch(a){this.b.reject(a),
this.b=null}}.bind(a),10)}return a.b}l=Tb.prototype;l.Ba=function(a,b){if(this.a)this.a.then(this.Ba.bind(this,a,b)).catch(this.Ba.bind(this,a,b));else{this.a=a;var c,d;"webkit-org.w3.clearkey"==this.c?(c=Fb(new Uint8Array(b)),d=JSON.parse(c),"oct"!=d.keys[0].kty&&(this.a.reject(Error("Response is not a valid JSON Web Key Set.")),this.a=null),c=Hb(d.keys[0].k),d=Hb(d.keys[0].kid)):(c=new Uint8Array(b),d=null);try{this.f.webkitAddKey(this.c,c,d,this.sessionId)}catch(e){this.a.reject(e),this.a=null}}};
function Vb(a,b){a.keyStatuses.ya(b);var c=v({type:"keystatuseschange"});a.dispatchEvent(c)}l.generateRequest=function(a,b){return Xb(this,b,null)};l.load=function(a){return"persistent-license"==this.g?Xb(this,null,a):Promise.reject(Error("Not a persistent session."))};l.update=function(a){var b=new F;this.Ba(b,a);return b};
l.close=function(){if("persistent-license"!=this.g){if(!this.sessionId)return this.closed.reject(Error("The session is not callable.")),this.closed;this.f.webkitCancelKeyRequest(this.c,this.sessionId)}this.closed.resolve();return this.closed};l.remove=function(){return"persistent-license"!=this.g?Promise.reject(Error("Not a persistent session.")):this.close()};function Wb(){this.size=0;this.a=void 0}var Yb;l=Wb.prototype;l.ya=function(a){this.size=void 0==a?0:1;this.a=a};l.ta=function(){return this.a};
l.forEach=function(a){this.a&&a(Yb,this.a)};l.get=function(a){if(this.has(a))return this.a};l.has=function(a){var b=Yb;return this.a&&Jb(new Uint8Array(a),new Uint8Array(b))?!0:!1};function Zb(a){this.systemIds=[];this.cencKeyIds=[];this.a=[];a=new Ra(new DataView(a.buffer));try{for(;a.a<a.b.byteLength;){var b=a.a,c=Ta(a),d=Ta(a);if(1==c){var e=a,f=void 0,g=void 0;e.c?(f=e.b.getUint32(e.a,!0),g=e.b.getUint32(e.a+4,!0)):(g=e.b.getUint32(e.a,!1),f=e.b.getUint32(e.a+4,!1));if(2097151<g)throw new RangeError("DataViewReader: Overflow reading 64-bit value.");e.a+=8;c=g*Math.pow(2,32)+f}else 0==c&&(c=a.b.byteLength-b);if(1886614376!=d)Va(a,c-(a.a-b));else{var h,e=a,k=e.b.getUint8(e.a);
e.a+=1;h=k;if(1<h)Va(a,c-(a.a-b));else{Va(a,3);var m=Ib(Ua(a)),e=[];if(0<h)for(var q=Ta(a),f=0;f<q;++f){var w=Ib(Ua(a));e.push(w)}var D=Ta(a);Va(a,D);this.cencKeyIds.push.apply(this.cencKeyIds,e);this.systemIds.push(m);this.a.push({start:b,end:a.a-1});a.a!=b+c&&Va(a,c-(a.a-b))}}}}catch(V){}};function $b(a,b){try{var c=new ac(a,b);return Promise.resolve(c)}catch(d){return Promise.reject(d)}}
function ac(a,b){this.keySystem=a;for(var c=!1,d=0;d<b.length;++d){var e=b[d],f={audioCapabilities:[],videoCapabilities:[],persistentState:"optional",distinctiveIdentifier:"optional",initDataTypes:e.initDataTypes,sessionTypes:["temporary"]},g=!1;if(e.audioCapabilities)for(var h=0;h<e.audioCapabilities.length;++h){var k=e.audioCapabilities[h];if(k.contentType){var g=!0,m=k.contentType.split(";")[0];MSMediaKeys.isTypeSupported(this.keySystem,m)&&(f.audioCapabilities.push(k),c=!0)}}if(e.videoCapabilities)for(h=
0;h<e.videoCapabilities.length;++h)k=e.videoCapabilities[h],k.contentType&&(g=!0,m=k.contentType.split(";")[0],MSMediaKeys.isTypeSupported(this.keySystem,m)&&(f.videoCapabilities.push(k),c=!0));g||(c=MSMediaKeys.isTypeSupported(this.keySystem,"video/mp4"));"required"==e.persistentState&&(f.persistentState="required",f.sessionTypes=["persistent-license"]);if(c){this.a=f;return}}c=Error("Unsupported keySystem");c.name="NotSupportedError";c.code=DOMException.NOT_SUPPORTED_ERR;throw c;}
ac.prototype.createMediaKeys=function(){var a=new bc(this.keySystem);return Promise.resolve(a)};ac.prototype.getConfiguration=function(){return this.a};function cc(a){var b=this.mediaKeys;b&&b!=a&&dc(b,null);delete this.mediaKeys;return(this.mediaKeys=a)?dc(a,this):Promise.resolve()}function bc(a){this.a=new MSMediaKeys(a);this.b=new B}bc.prototype.createSession=function(a){if("temporary"!=(a||"temporary"))throw new TypeError("Session type "+a+" is unsupported on this platform.");return new ec(this.a)};
bc.prototype.setServerCertificate=function(){return Promise.reject(Error("setServerCertificate not supported on this platform."))};function dc(a,b){function c(){b.msSetMediaKeys(d.a);b.removeEventListener("loadedmetadata",c)}lb(a.b);if(!b)return Promise.resolve();C(a.b,b,"msneedkey",fc);var d=a;try{return 1<=b.readyState?b.msSetMediaKeys(a.a):b.addEventListener("loadedmetadata",c),Promise.resolve()}catch(e){return Promise.reject(e)}}
function ec(a){E.call(this,null);this.c=null;this.g=a;this.b=this.a=null;this.f=new B;this.sessionId="";this.expiration=NaN;this.closed=new F;this.keyStatuses=new gc}p(ec,E);l=ec.prototype;l.generateRequest=function(a,b){this.a=new F;try{this.c=this.g.createSession("video/mp4",new Uint8Array(b),null),C(this.f,this.c,"mskeymessage",this.jb.bind(this)),C(this.f,this.c,"mskeyadded",this.hb.bind(this)),C(this.f,this.c,"mskeyerror",this.ib.bind(this)),hc(this,"status-pending")}catch(c){this.a.reject(c)}return this.a};
l.load=function(){return Promise.reject(Error("MediaKeySession.load not yet supported"))};l.update=function(a){this.b=new F;try{this.c.update(new Uint8Array(a))}catch(b){this.b.reject(b)}return this.b};l.close=function(){try{this.c.close(),this.closed.resolve(),lb(this.f)}catch(a){this.closed.reject(a)}return this.closed};l.remove=function(){return Promise.reject(Error("MediaKeySession.remove is only applicable for persistent licenses, which are not supported on this platform"))};
function fc(a){var b=a.initData;if(b){var c=new Zb(b);if(1>=c.a.length)a=b;else{var d=[];for(a=0;a<c.a.length;a++)d.push(b.subarray(c.a[a].start,c.a[a].end+1));b=Pa(d,ic);for(a=c=0;a<b.length;a++)c+=b[a].length;c=new Uint8Array(c);for(a=d=0;a<b.length;a++)c.set(b[a],d),d+=b[a].length;a=c}}else a=b;a=v({type:"encrypted",initDataType:"cenc",initData:a});this.dispatchEvent(a)}function ic(a,b){return Jb(a,b)}
l.jb=function(a){this.a&&(this.a.resolve(),this.a=null);a=v({type:"message",messageType:void 0==this.keyStatuses.ta()?"licenserequest":"licenserenewal",message:a.message.buffer});this.dispatchEvent(a)};l.hb=function(){this.a?(this.a.resolve(),this.a=null):this.b&&(hc(this,"usable"),this.b.resolve(),this.b=null)};
l.ib=function(){var a=Error("EME v20140218 key error");a.errorCode=this.c.error;if(null!=this.a)this.a.reject(a),this.a=null;else if(null!=this.b)this.b.reject(a),this.b=null;else switch(this.c.error.code){case MSMediaKeyError.MS_MEDIA_KEYERR_OUTPUT:case MSMediaKeyError.MS_MEDIA_KEYERR_HARDWARECHANGE:hc(this,"output-not-allowed");default:hc(this,"internal-error")}};function hc(a,b){a.keyStatuses.ya(b);var c=v({type:"keystatuseschange"});a.dispatchEvent(c)}function gc(){this.size=0;this.a=void 0}var lc;
l=gc.prototype;l.ya=function(a){this.size=void 0==a?0:1;this.a=a};l.ta=function(){return this.a};l.forEach=function(a){this.a&&a(lc,this.a)};l.get=function(a){if(this.has(a))return this.a};l.has=function(a){var b=lc;return this.a&&Jb(new Uint8Array(a),new Uint8Array(b))?!0:!1};function mc(){Navigator.prototype.requestMediaKeySystemAccess&&MediaKeySystemAccess.prototype.getConfiguration||(HTMLMediaElement.prototype.webkitGenerateKeyRequest?(Yb=(new Uint8Array([0])).buffer,Navigator.prototype.requestMediaKeySystemAccess=Ob,delete HTMLMediaElement.prototype.mediaKeys,HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=Qb,window.MediaKeys=Sb,window.MediaKeySystemAccess=Pb):window.MSMediaKeys?(lc=(new Uint8Array([0])).buffer,delete HTMLMediaElement.prototype.mediaKeys,
HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=cc,window.MediaKeys=bc,window.MediaKeySystemAccess=ac,Navigator.prototype.requestMediaKeySystemAccess=$b):(Navigator.prototype.requestMediaKeySystemAccess=xa,delete HTMLMediaElement.prototype.mediaKeys,HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=ya,window.MediaKeys=za,window.MediaKeySystemAccess=Aa))}n("shaka.polyfill.MediaKeys.install",mc);n("shaka.polyfill.installAll",function(){ta();va();Na();Ca();mc()});var nc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function I(a){var b;a instanceof I?(oc(this,a.L),this.U=a.U,this.K=a.K,pc(this,a.aa),this.J=a.J,qc(this,a.a.clone()),this.R=a.R):a&&(b=String(a).match(nc))?(oc(this,b[1]||"",!0),this.U=rc(b[2]||""),this.K=rc(b[3]||"",!0),pc(this,b[4]),this.J=rc(b[5]||"",!0),qc(this,b[6]||"",!0),this.R=rc(b[7]||"")):this.a=new J(null)}l=I.prototype;l.L="";l.U="";l.K="";l.aa=null;l.J="";l.R="";
l.toString=function(){var a=[],b=this.L;b&&a.push(sc(b,tc,!0),":");if(b=this.K){a.push("//");var c=this.U;c&&a.push(sc(c,tc,!0),"@");a.push(encodeURIComponent(b).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.aa;null!=b&&a.push(":",String(b))}if(b=this.J)this.K&&"/"!=b.charAt(0)&&a.push("/"),a.push(sc(b,"/"==b.charAt(0)?uc:vc,!0));(b=this.a.toString())&&a.push("?",b);(b=this.R)&&a.push("#",sc(b,wc));return a.join("")};
l.resolve=function(a){var b=this.clone();"data"===b.L&&(b=new I);var c=!!a.L;c?oc(b,a.L):c=!!a.U;c?b.U=a.U:c=!!a.K;c?b.K=a.K:c=null!=a.aa;var d=a.J;if(c)pc(b,a.aa);else if(c=!!a.J){if("/"!=d.charAt(0))if(this.K&&!this.J)d="/"+d;else{var e=b.J.lastIndexOf("/");-1!=e&&(d=b.J.substr(0,e+1)+d)}if(".."==d||"."==d)d="";else if(-1!=d.indexOf("./")||-1!=d.indexOf("/.")){for(var e=0==d.lastIndexOf("/",0),d=d.split("/"),f=[],g=0;g<d.length;){var h=d[g++];"."==h?e&&g==d.length&&f.push(""):".."==h?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),e&&g==d.length&&f.push("")):(f.push(h),e=!0)}d=f.join("/")}}c?b.J=d:c=""!==a.a.toString();c?qc(b,a.a.clone()):c=!!a.R;c&&(b.R=a.R);return b};l.clone=function(){return new I(this)};function oc(a,b,c){a.L=c?rc(b,!0):b;a.L&&(a.L=a.L.replace(/:$/,""))}function pc(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.aa=b}else a.aa=null}function qc(a,b,c){b instanceof J?a.a=b:(c||(b=sc(b,xc)),a.a=new J(b))}
function rc(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}function sc(a,b,c){return"string"==typeof a?(a=encodeURI(a).replace(b,yc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function yc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var tc=/[#\/\?@]/g,vc=/[\#\?:]/g,uc=/[\#\?]/g,xc=/[\#\?@]/g,wc=/#/g;function J(a){this.b=a||null}J.prototype.a=null;J.prototype.c=null;
function zc(a,b,c){if(!a.a&&(a.a={},a.c=0,a.b))for(var d=a.b.split("&"),e=0;e<d.length;e++){var f=d[e].indexOf("="),g=null,h=null;0<=f?(g=d[e].substring(0,f),h=d[e].substring(f+1)):g=d[e];g=decodeURIComponent(g.replace(/\+/g," "));h=h||"";zc(a,g,decodeURIComponent(h.replace(/\+/g," ")))}a.b=null;(d=a.a.hasOwnProperty(b)&&a.a[b])||(a.a[b]=d=[]);d.push(c);a.c++}
J.prototype.toString=function(){if(this.b)return this.b;if(!this.a)return"";var a=[],b;for(b in this.a)for(var c=encodeURIComponent(b),d=this.a[b],e=0;e<d.length;e++){var f=c;""!==d[e]&&(f+="="+encodeURIComponent(d[e]));a.push(f)}return this.b=a.join("&")};J.prototype.clone=function(){var a=new J;a.b=this.b;if(this.a){var b={},c;for(c in this.a)b[c]=this.a[c].concat();a.a=b;a.c=this.c}return a};function Ac(){this.id=this.url=null;this.type="static";this.b=this.j=this.o=this.Ra=null;this.h=5;this.f=this.c=this.g=null;this.i=1;this.a=[]}function Bc(){this.g=this.f=this.c=this.o=this.a=this.start=this.id=null;this.b=[]}function Cc(){this.i=this.b=this.height=this.width=this.contentType=this.lang=this.group=this.id=null;this.c=!1;this.h=this.g=this.f=this.o=null;this.j=[];this.a=[]}function Dc(){this.value=null}function Ec(){this.contentType=this.lang=this.id=null}
function Fc(){this.a=this.b=this.g=this.o=this.h=this.f=this.height=this.width=this.bandwidth=this.lang=this.id=null;this.c=[]}function Gc(){this.b=this.a=this.c=this.f=null}function Hc(){this.parsedPssh=this.psshBox=null}function Ic(){this.url=null}function Jc(){this.url=null}function Kc(){this.o=null;this.c=1;this.g=this.f=this.a=this.b=null}Kc.prototype.clone=function(){var a=new Kc;a.o=Lc(this.o);a.c=this.c;a.b=this.b;a.a=K(this.a);a.f=K(this.f);a.g=K(this.g);return a};
function Mc(){this.a=this.url=null}Mc.prototype.clone=function(){var a=new Mc;a.url=Lc(this.url);a.a=K(this.a);return a};function Nc(){this.a=this.url=null}Nc.prototype.clone=function(){var a=new Nc;a.url=Lc(this.url);a.a=K(this.a);return a};function Oc(){this.o=null;this.f=1;this.b=this.g=null;this.i=1;this.h=null;this.a=[];this.c=null}Oc.prototype.clone=function(){var a=new Oc;a.o=Lc(this.o);a.f=this.f;a.g=this.g;a.b=this.b;a.i=this.i;a.h=K(this.h);a.a=Lc(this.a)||[];a.c=K(this.c);return a};
function Pc(){this.a=this.b=null}Pc.prototype.clone=function(){var a=new Pc;a.b=Lc(this.b);a.a=K(this.a);return a};function Qc(){this.a=1;this.b=this.i=null;this.j=1;this.c=this.g=this.f=this.h=null}Qc.prototype.clone=function(){var a=new Qc;a.a=this.a;a.i=this.i;a.b=this.b;a.j=this.j;a.h=this.h;a.f=this.f;a.g=this.g;a.c=K(this.c);return a};function Rc(){this.a=[]}Rc.prototype.clone=function(){var a=new Rc;a.a=Lc(this.a)||[];return a};function Sc(){this.b=this.a=this.startTime=null}
Sc.prototype.clone=function(){var a=new Sc;a.startTime=this.startTime;a.a=this.a;a.b=this.b;return a};function Tc(a,b){this.fa=a;this.end=b}Tc.prototype.clone=function(){return new Tc(this.fa,this.end)};Ac.TAG_NAME="MPD";Bc.TAG_NAME="Period";Cc.TAG_NAME="AdaptationSet";Dc.TAG_NAME="Role";Ec.TAG_NAME="ContentComponent";Fc.TAG_NAME="Representation";Gc.TAG_NAME="ContentProtection";Hc.TAG_NAME="cenc:pssh";Ic.TAG_NAME="BaseURL";Jc.TAG_NAME="Location";Kc.TAG_NAME="SegmentBase";Mc.TAG_NAME="RepresentationIndex";
Nc.TAG_NAME="Initialization";Oc.TAG_NAME="SegmentList";Pc.TAG_NAME="SegmentURL";Qc.TAG_NAME="SegmentTemplate";Rc.TAG_NAME="SegmentTimeline";Sc.TAG_NAME="S";
Ac.prototype.parse=function(a,b){this.url=a.Ra;this.id=L(b,"id",M);this.type=L(b,"type",M)||"static";this.b=L(b,"mediaPresentationDuration",Uc);this.h=L(b,"minBufferTime",Uc,this.h);this.g=L(b,"minimumUpdatePeriod",Uc,this.g);this.c=L(b,"availabilityStartTime",Vc,this.c);this.f=L(b,"timeShiftBufferDepth",Uc,this.f);this.i=L(b,"suggestedPresentationDelay",Uc,this.i);var c=a.o,d=N(this,b,Ic);this.o=Wc(c,d);if(d=O(this,b,Jc))this.j=Xc(c,d.url);this.a=N(this,b,Bc)};
Bc.prototype.parse=function(a,b){this.id=L(b,"id",M);this.start=L(b,"start",Uc);this.a=L(b,"duration",Uc);var c=N(this,b,Ic);this.o=Wc(a.o,c);this.c=O(this,b,Kc);this.f=O(this,b,Oc);this.g=O(this,b,Qc);this.b=N(this,b,Cc);Yc(this)};function Yc(a){for(var b=[],c=0;c<a.b.length;++c){var d=a.b[c];null!=d.group&&(b[d.group]=!0)}for(c=0;c<a.b.length;++c)if(d=a.b[c],null==d.group){for(var e=1;1==b[e];)++e;b[e]=!0;d.group=e}}
Cc.prototype.parse=function(a,b){var c=O(this,b,Ec)||{},d=O(this,b,Dc);this.id=L(b,"id",M);this.group=L(b,"group",P);this.lang=L(b,"lang",M,c.lang);this.contentType=L(b,"contentType",M,c.contentType);this.width=L(b,"width",Q);this.height=L(b,"height",Q);this.b=L(b,"mimeType",M);this.i=L(b,"codecs",M);this.c=d&&"main"==d.value;this.lang&&(this.lang=ab(this.lang));c=N(this,b,Ic);this.o=Wc(a.o,c);this.j=N(this,b,Gc);!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]);this.f=a.c?Zc(this,
b,a.c):O(this,b,Kc);this.g=a.f?Zc(this,b,a.f):O(this,b,Oc);this.h=a.g?Zc(this,b,a.g):O(this,b,Qc);this.a=N(this,b,Fc);!this.b&&this.a.length&&(this.b=this.a[0].f,!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]))};Dc.prototype.parse=function(a,b){this.value=L(b,"value",M)};Ec.prototype.parse=function(a,b){this.id=L(b,"id",M);this.lang=L(b,"lang",M);this.contentType=L(b,"contentType",M);this.lang&&(this.lang=ab(this.lang))};
Fc.prototype.parse=function(a,b){this.id=L(b,"id",M);this.bandwidth=L(b,"bandwidth",Q);this.width=L(b,"width",Q,a.width);this.height=L(b,"height",Q,a.height);this.f=L(b,"mimeType",M,a.b);this.h=L(b,"codecs",M,a.i);this.lang=a.lang;var c=N(this,b,Ic);this.o=Wc(a.o,c);this.c=N(this,b,Gc);this.g=a.f?Zc(this,b,a.f):O(this,b,Kc);this.b=a.g?Zc(this,b,a.g):O(this,b,Oc);this.a=a.h?Zc(this,b,a.h):O(this,b,Qc);this.c=this.c.concat(a.j)};
Gc.prototype.parse=function(a,b){this.f=b;this.c=L(b,"schemeIdUri",M);var c=L(b,"cenc:default_KID",M);c&&(this.b=c.replace(/[-]/g,""));this.a=O(this,b,Hc)};Hc.prototype.parse=function(a,b){var c=$c(b);if(c){this.psshBox=Hb(c);try{this.parsedPssh=new Zb(this.psshBox)}catch(d){if(!(d instanceof RangeError))throw d;}}};Ic.prototype.parse=function(a,b){this.url=$c(b)};Jc.prototype.parse=function(a,b){this.url=$c(b)};
Kc.prototype.parse=function(a,b){this.o=a.o||this.o;this.c=L(b,"timescale",Q,this.c);this.b=L(b,"presentationTimeOffset",P,this.b);this.a=L(b,"indexRange",ad,this.a);this.f=O(this,b,Mc)||this.f;this.g=O(this,b,Nc)||this.g};Mc.prototype.parse=function(a,b){var c=L(b,"sourceURL",M);this.url=Xc(a.o,c);this.a=L(b,"range",ad,K(a.a))};Nc.prototype.parse=function(a,b){var c=L(b,"sourceURL",M);this.url=Xc(a.o,c);this.a=L(b,"range",ad)};
Oc.prototype.parse=function(a,b){this.o=a.o||this.o;this.f=L(b,"timescale",Q,this.f);this.g=L(b,"presentationTimeOffset",P,this.g);this.b=L(b,"duration",Q,this.b);var c=L(b,"startNumber",Q);null!=c&&(this.i=c);this.h=O(this,b,Nc)||this.h;this.a=(c=N(this,b,Pc))&&0<c.length?c:this.a;this.c=O(this,b,Rc)||this.c};Pc.prototype.parse=function(a,b){var c=L(b,"media",M);this.b=Xc(a.o,c);this.a=L(b,"mediaRange",ad)};
Qc.prototype.parse=function(a,b){this.a=L(b,"timescale",Q,this.a);this.i=L(b,"presentationTimeOffset",P,this.i);this.b=L(b,"duration",Q,this.b);var c=L(b,"startNumber",P);null!=c&&(this.j=c);this.h=L(b,"media",M,this.h);this.f=L(b,"index",M,this.f);this.g=L(b,"initialization",M,this.g);this.c=O(this,b,Rc)||this.c};Rc.prototype.parse=function(a,b){this.a=N(this,b,Sc)};Sc.prototype.parse=function(a,b){this.startTime=L(b,"t",P);this.a=L(b,"d",P);this.b=L(b,"r",bd)};
function Wc(a,b){if(!b||0===b.length)return a;for(var c=[],d=0;d<b.length;d++){var e=b[d].url;null==a||0===a.length?c.push(new I(e)):(e=Xc(a.slice(0,1),e),c.push(e[0]))}return c}function Xc(a,b){if(!b)return a;var c=new I(b);return a?a.map(function(a){return a.resolve(c)}):[c]}function Zc(a,b,c){var d=K(c);(b=cd(b,c.constructor.TAG_NAME))&&d.parse(a,b);return d}function O(a,b,c){var d=null;if(b=cd(b,c.TAG_NAME))d=new c,d.parse(a,b);return d}
function cd(a,b){for(var c=null,d=0;d<a.childNodes.length;d++)if(a.childNodes[d].tagName==b){if(c)return null;c=a.childNodes[d]}return c}function N(a,b,c){for(var d=[],e=0;e<b.childNodes.length;e++)if(b.childNodes[e].tagName==c.TAG_NAME){var f=new c;f.parse.call(f,a,b.childNodes[e]);d.push(f)}return d}function $c(a){a=a.firstChild;return a.nodeType!=Node.TEXT_NODE?null:a.nodeValue}function Lc(a){return a?a.map(function(a){return a.clone()}):null}function K(a){return a?a.clone():null}
function L(a,b,c,d){a=c(a.getAttribute(b));return null!=a?a:void 0!==d?d:null}function Vc(a){if(!a)return null;a=Date.parse(a);return isNaN(a)?null:Math.floor(a/1E3)}
function Uc(a){if(!a)return null;var b=/^P(?:([0-9]*)Y)?(?:([0-9]*)M)?(?:([0-9]*)D)?(?:T(?:([0-9]*)H)?(?:([0-9]*)M)?(?:([0-9.]*)S)?)?$/.exec(a);if(!b)return null;a=0;var c=P(b[1]);c&&(a+=31536E3*c);(c=P(b[2]))&&(a+=2592E3*c);(c=P(b[3]))&&(a+=86400*c);(c=P(b[4]))&&(a+=3600*c);(c=P(b[5]))&&(a+=60*c);b=window.parseFloat(b[6]);(b=isNaN(b)?null:b)&&(a+=b);return a}
function ad(a){var b=/([0-9]+)-([0-9]+)/.exec(a);if(!b)return null;a=P(b[1]);if(null==a)return null;b=P(b[2]);return null==b?null:new Tc(a,b)}function bd(a){a=window.parseInt(a,10);return isNaN(a)?null:a}function Q(a){a=window.parseInt(a,10);return 0<a?a:null}function P(a){a=window.parseInt(a,10);return 0<=a?a:null}function M(a){return a};function dd(a,b){this.url=a;this.b=b||new zb;this.g=this.i=this.h=0;this.a=null;this.c=new F;this.f=null}function zb(){this.body=null;this.a=1;this.h=1E3;this.c=0;this.method="GET";this.f="arraybuffer";this.b={};this.g=this.i=!1;this.j=null}var ed=!0;function fd(a){gd(a);a.b.body=null;a.c.destroy();a.c=null;a.f=null}function gd(a){a.a&&(a.a.onload=null,a.a.onreadystatechange=null,a.a.onerror=null,a.a.ontimeout=null);a.a=null}l=dd.prototype;
l.Va=function(){if(this.a)return this.c;if(0==this.url.lastIndexOf("data:",0)){var a=this.url.split(":")[1].split(";").pop().split(","),b=a.pop(),b="base64"==a.pop()?window.atob(b.replace(/-/g,"+").replace(/_/g,"/")):window.decodeURIComponent(b);"arraybuffer"==this.b.f&&(b=Gb(b).buffer);a=JSON.parse(JSON.stringify(new XMLHttpRequest));a.response=b;a.responseText=b.toString();b=this.c;b.resolve(a);fd(this);return b}if(0==this.url.lastIndexOf("idb:",0))return this.j();this.h++;this.i=Date.now();this.g||
(this.g=this.b.h);this.a=Za("new_http_request",{url:this.url});this.a||(this.a=new XMLHttpRequest);a=this.url;ed&&(this.f&&!this.f.supportsCaching()||this.b.g)&&(a=new I(a),zc(a.a,"_",Date.now()),a=a.toString());this.a.open(this.b.method,a,!0);this.a.responseType=this.b.f;this.a.timeout=this.b.c;this.a.withCredentials=this.b.i;this.a.onload=this.fb.bind(this);this.b.g&&(this.a.onreadystatechange=this.mb.bind(this));this.a.onerror=this.zb.bind(this);this.a.ontimeout=this.qb.bind(this);for(b in this.b.b)this.a.setRequestHeader(b,
this.b.b[b]);this.a.send(this.b.body);return this.c};function hd(a,b,c){b=Error(b);b.type=c;b.status=a.a.status;b.url=a.url;b.method=a.b.method;b.body=a.b.body;b.xhr=a.a;return b}l.fb=function(a){this.f&&this.f.sample(Date.now()-this.i,a.loaded);200<=this.a.status&&299>=this.a.status?(this.c.resolve(this.a),fd(this)):this.h<this.b.a?id(this):(a=hd(this,"HTTP error.","net"),this.c.reject(a),fd(this))};
l.mb=function(){if(this.a.readyState==XMLHttpRequest.HEADERS_RECEIVED){var a=Date.parse(this.a.getResponseHeader("Date"));a&&(Qa=a-Date.now())}};l.zb=function(){var a=hd(this,"Network failure.","net");this.c.reject(a);fd(this)};l.qb=function(){if(this.h<this.b.a)id(this);else{var a=hd(this,"Request timed out.","net");this.c.reject(a);fd(this)}};function id(a){gd(a);window.setTimeout(a.Va.bind(a),a.g*(1+.5*(2*Math.random()-1)));a.g*=2};function H(a,b,c,d){this.T=b;this.h=c||0;this.f=null!=d?d:null;this.b=this.a=null;this.g=a;this.c=null}function jd(a,b){return a&&0!==a.length?a.map(function(a){return a.resolve(b)}):[b]}H.prototype.fetch=function(a,b){if(this.a)return this.a;var c=a||new zb;if(this.h||this.f)c.b.Range="bytes="+(this.h+"-"+(null!=this.f?this.f:""));return this.a=kd(this,0,c,b)};
H.prototype.i=function(){if(this.b){this.a=null;var a=this.b;if(a.a&&a.a.readyState!=XMLHttpRequest.DONE){a.a.abort();var b=hd(a,"Request aborted.","aborted");a.c.reject(b);fd(a)}this.c=this.b=null}};
function kd(a,b,c,d){var e=a.T[b].toString();a.g&&(e=a.g(e,c.b)||e);a.b=new dd(e,c);d&&(a.b.f=d);e=a.b.Va().then(G(a,function(a){this.c=this.b=this.a=null;this.c=a.a?new I(a.a):this.T[b];return Promise.resolve(a.response)}));return e=e.catch(G(a,function(a){if(this.a&&b+1<this.T.length)return this.a=kd(this,b+1,c,d);this.a=this.b=null;return Promise.reject(a)}))}H.prototype.clone=function(){return new H(this.g,this.T.map(function(a){return a.clone()}),this.h,this.f)};H.prototype.toString=function(){return this.T[0].toString()};function ld(a,b){this.a=new zb;this.a.f="text";this.a.a=3;this.a.c=1E3*(null!=b?b:0);this.a.g=!0;this.b=a}function md(a){var b=a.b;return b.fetch(a.a).then(function(a){var d;d=b.T;var e=[b.c];d=(a=(new DOMParser).parseFromString(a,"text/xml"))?O({Ra:d,o:e},a,Ac):null;if(d)return Promise.resolve(d);d=Error("MPD parse failure.");d.type="dash";return Promise.reject(d)})};function nd(a,b,c,d){for(var e=b.a,f=[],g=0;g<d;++g){var h=g+c,k=(h-1)*e.b,m=k/e.a,q=(k+e.b)/e.a,h=od(a,b,e.j+h-1,k);if(!h)return null;f.push(new pd(m,q,h))}return f}function od(a,b,c,d){if(!b.a)return null;var e=b.a.h;if(!e)return b.o?new H(a,b.o,0,null):null;c=qd(e,b.id,c,b.bandwidth,d);if(!c)return null;b=jd(b.o,c);return new H(a,b,0,null)}
function qd(a,b,c,d,e){var f={RepresentationID:b,Number:c,Bandwidth:d,Time:e};a=a.replace(/\$(RepresentationID|Number|Bandwidth|Time)?(?:%0([0-9]+)d)?\$/g,function(a,b,c){if("$$"==a)return"$";var d=f[b];if(null==d)return a;"RepresentationID"==b&&c&&(c=void 0);a=d.toString();c=window.parseInt(c,10)||1;c=Math.max(0,c-a.length);return Array(c+1).join("0")+a});try{return new I(a)}catch(g){if(g instanceof URIError)return null;throw g;}}
function rd(a,b,c){var d=0;b*=c;a=a.a;c=[];for(var e=0;e<a.length&&a[e].a;++e){var f=a[e].startTime,f=null!=f?f:d,g=a[e].b||0;0>g&&(g=a[e].a,g=e+1===a.length?Math.ceil((a[0].startTime+b-f)/g)-1:Math.ceil((a[e+1].startTime-f)/g)-1);0<c.length&&f!=d&&(c[c.length-1].end=f);for(var h=0;h<=g;++h)d=f+a[e].a,c.push({start:f,end:d}),f=d}return c};function sd(a,b){this.a=a;this.b=b||null}sd.prototype.destroy=function(){this.a&&(this.a.i(),this.a=null);this.b=null};sd.prototype.create=function(){return this.a?this.a.fetch():Promise.resolve(this.b)};function pd(a,b,c){this.startTime=a;this.endTime=b;this.url=c}function td(a,b,c){return new pd(b,c,a.url)}function Ab(a,b){for(var c=a.length-1;0<=c;--c){var d=a[c];if(b>=d.startTime&&(null==d.endTime||b<d.endTime))return c}return-1}function ud(a,b){return a.map(function(a){return td(a,a.startTime+b,null!=a.endTime?a.endTime+b:null)})};function R(a){this.references=a;this.i=0}R.prototype.destroy=function(){this.references=null};l=R.prototype;l.length=function(){return this.references.length};function S(a){if(0==a.references.length)throw new RangeError("SegmentIndex: There is no first SegmentReference.");return a.references[0]}l.u=function(){if(0==this.references.length)throw new RangeError("SegmentIndex: There is no last SegmentReference.");return this.references[this.references.length-1]};
l.get=function(a){if(0>a||a>=this.references.length)throw new RangeError("SegmentIndex: The specified index is out of range.");return this.references[a]};l.ca=function(a){a=Ab(this.references,a);return 0<=a?this.references[a]:null};l.va=function(a){vd(this,a);return!0};
function vd(a,b){a.i!=b.i&&(b=new R(ud(b.references,a.i-b.i)));if(0==a.length())a.references=b.references.slice(0);else if(0!=b.length()&&null!=a.u().endTime&&!(null!=b.u().endTime&&b.u().endTime<a.u().endTime)){if(a.u().endTime<=S(b).startTime)var c=td(a.u(),a.u().startTime,S(b).startTime),c=a.references.slice(0,-1).concat([c]);else{var d;for(d=0;d<a.references.length&&!(a.references[d].endTime>=S(b).startTime);++d);a.references[d].startTime<S(b).startTime?(c=td(a.references[d],a.references[d].startTime,
S(b).startTime),c=a.references.slice(0,d).concat([c])):(S(a).startTime>S(b).startTime||S(b),c=a.references.slice(0,d))}a.references=c.concat(b.references)}}l.ba=function(a){var b=a-this.i;if(0==b)return 0;this.references=ud(this.references,b);this.i=a;return b};l.sa=function(){return 0<this.length()?{start:S(this).startTime,end:this.u().endTime}:{start:0,end:0}};function T(a,b,c,d){R.call(this,a);this.g=b;this.s=c;this.f=d;this.h=this.g.b||this.g.a.reduce(function(a,b){return null==b.a?NaN:a+b.a},0)||0;this.a=this.m=this.c=null;wd(this)}p(T,R);T.prototype.destroy=function(){this.s=this.g=null;R.prototype.destroy.call(this)};T.prototype.ca=function(a){xd(this,u()/1E3);return R.prototype.ca.call(this,a)};T.prototype.va=function(a){if(!(a instanceof T))return!1;vd(this,a);this.h=Math.max(this.h,a.h);null==this.c?(this.f=a.f,wd(this)):yd(this);return!0};
function wd(a){yd(a);if(0!=a.length()){a.length();var b=null!=a.u().endTime?a.u().endTime:a.u().startTime;if(a.g.c>a.f)a.c=b;else{var c=a.f-(a.g.c+a.s.start);0>c?a.c=b:c<Math.max(a.u().startTime,a.u().endTime||0)?(a.u(),a.c=b):a.c=c}a.m=a.u().startTime;a.a=S(a).startTime}}
T.prototype.ba=function(a){a=R.prototype.ba.call(this,a);Math.min.apply(null,this.references.filter(function(a){return null!=a.endTime}).map(function(a){return a.endTime-a.startTime}));null!=this.c&&(this.m+=a,this.a+=a,this.c+=a);return a};T.prototype.sa=function(){return zd(this,u()/1E3)};
function zd(a,b){xd(a,b);if(null==a.c||null==a.m||null==a.a)return{start:0,end:0};var c=Number.POSITIVE_INFINITY;a.h&&(c=a.h);var d=b-a.f,e=a.c+d;null!=a.g.f&&(e=e-a.a-a.g.f,0<e&&(a.a+=e));a.a=Math.min(a.a,c);d=a.m+d;if(d<a.a)return{start:a.a,end:a.a};d=0<a.length()?null!=a.u().endTime?Math.min(d,a.u().endTime):d:a.a;d=Math.max(d,a.a);d=Math.min(d,c);return{start:a.a,end:d}}
function xd(a,b){yd(a);if(null!=a.g.f)if(null==a.c)a.length();else{for(var c=a.c+(b-a.f),d=0,e=0;e<a.references.length;++e){var f=null;e<a.references.length-1?f=a.references[e+1].endTime:(f=a.references[e],f=null!=f.endTime?f.endTime+(f.endTime-f.startTime):null);if(null!=f&&f<c-a.g.f)++d;else break}0<d&&a.references.splice(0,d)}}function yd(a){if(a.h){for(var b=0,c=a.references.length-1;0<=c;--c)if(a.references[c].startTime>a.h)++b;else break;0<b&&a.references.splice(-b)}};function U(a,b,c,d,e){var f=1,g=0,h;if(a.c>d)h=null;else{var k=a.i||0,m=a.f||0;h=c.a;h=h.b/h.a;var q=d-(a.c+b.start);0>q?h=null:(m=q-2*h-m,0>m&&(m=0),m=Math.ceil(m/h)*h,q-=h,0>q?h=null:(k=Math.floor(q/h)*h-k,0>k&&(k=0),k=Math.floor(k/h)*h,h={La:m/h+1,current:(k>=m?k:m)/h+1}))}h&&(f=h.La,g=h.current-h.La+1);f=nd(e,c,f,g);if(null==f)throw a=Error("Failed to generate SegmentReferences."),a.type="stream",a;T.call(this,f,a,b,d);this.w=c;this.l=this.b=0<this.length()?a.c+b.start+this.u().endTime:null;this.j=
h?h.current+1:null;this.v=e}p(U,T);U.prototype.destroy=function(){this.v=this.w=null;T.prototype.destroy.call(this)};U.prototype.ca=function(a){var b=u()/1E3;Ad(this,b);xd(this,b);return R.prototype.ca.call(this,a)};U.prototype.va=function(a){if(null!=this.b||!(a instanceof U)||null==a.b)return!1;this.b=a.b;this.l=a.l;this.j=a.j;this.f=a.f;this.h=a.h;vd(this,a);Ad(this,u()/1E3);wd(this);return!0};U.prototype.ba=function(a){a=T.prototype.ba.call(this,a);null!=this.b&&(this.b+=a,this.l+=a);return a};
U.prototype.sa=function(){var a=u()/1E3;Ad(this,a);return zd(this,a)};function Ad(a,b){if(null!=a.b&&null!=a.l&&null!=a.j){var c=a.w.a,c=c.b/c.a,d=Math.floor((a.l+(b-a.f)-a.b)/c);if(0!=d){var e=nd(a.v,a.w,a.j,d);Array.prototype.push.apply(a.references,ud(e,a.i));a.b+=d*c;a.j+=d}}};function Bd(a,b,c,d,e){this.c=a;this.a=b;this.b=c;this.g=d;this.segmentIndex_=null;this.f=e}Bd.prototype.destroy=function(){this.f=this.b=this.a=this.c=null;this.segmentIndex_&&(this.segmentIndex_.destroy(),this.segmentIndex_=null)};
Bd.prototype.create=function(){if(this.segmentIndex_)return Promise.resolve(this.segmentIndex_);if("dynamic"==this.c.type)try{this.segmentIndex_=new U(this.c,this.a,this.b,this.g,this.f)}catch(a){return Promise.reject(a)}else{var b;b=this.b.a;if(b=nd(this.f,this.b,1,Math.ceil(this.a.a/(b.b/b.a)))){if(0<b.length){var c=b[b.length-1];b[b.length-1]=td(c,c.startTime,this.a.a)}b=new R(b)}else b=null;this.segmentIndex_=b;if(!this.segmentIndex_)return b=Error("Failed to generate SegmentReferences"),b.type=
"stream",Promise.reject(b)}return Promise.resolve(this.segmentIndex_)};function Cd(a,b,c,d,e){this.b=a;this.a=b;this.f=c;this.segmentIndex_=null;this.g=d;this.c=e}Cd.prototype.destroy=function(){this.c=this.f=this.a=this.b=null;this.segmentIndex_&&(this.segmentIndex_.destroy(),this.segmentIndex_=null)};
Cd.prototype.create=function(){if(this.segmentIndex_)return Promise.resolve(this.segmentIndex_);var a=this.f.b,b=[];a.c&&(b=rd(a.c,a.f||1,this.a.a||0));var c=0;a.b&&a.i?c=(a.i-1)*a.b:0<b.length&&(c=b[0].start-(a.g||0));var d=a.a.length;0<b.length&&b.length!=a.a.length&&(d=Math.min(b.length,a.a.length));for(var e=[],f=0;f<d;++f){var g=a.a[f],h=c/a.f,k=null,m=null;a.b?(k=c+a.b,m=k/a.f):0<b.length?(k=b[f].end-(a.g||0),m=k/a.f):(m=h+this.a.a,k=m*a.f);var c=k,k=0,q=null;g.a&&(k=g.a.fa,q=g.a.end);e.push(new pd(h,
m,new H(this.c,g.b,k,q)))}this.segmentIndex_="dynamic"==this.b.type?new T(e,this.b,this.a,this.g):new R(e);return Promise.resolve(this.segmentIndex_)};function Dd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.g=d;this.segmentIndex_=null;this.f=e}Dd.prototype.destroy=function(){this.f=this.c=this.b=this.a=null;this.segmentIndex_&&(this.segmentIndex_.destroy(),this.segmentIndex_=null)};
Dd.prototype.create=function(){if(this.segmentIndex_)return Promise.resolve(this.segmentIndex_);for(var a=this.c.a,b=rd(a.c,a.a||1,this.b.a||0),c=[],d=0;d<b.length;++d){var e=b[d].start,f=e/a.a,g=b[d].end/a.a,e=od(this.f,this.c,d+a.j,e);if(!e)return a=Error("Failed to generate media URL."),a.type="dash",Promise.reject(a);var h=(a.i||0)/a.a;c.push(new pd(f-h,g-h,e))}this.segmentIndex_="dynamic"==this.a.type?new T(c,this.a,this.b,this.g):new R(c);return Promise.resolve(this.segmentIndex_)};function Ed(){this.A=Fd++;this.id=this.H=this.segmentIndexSource=null;this.b=0;this.height=this.width=this.bandwidth=null;this.c=this.a="";this.f=[];this.I=!1;this.F=!0}var Fd=0;Ed.prototype.destroy=function(){this.segmentIndexSource&&(this.segmentIndexSource.destroy(),this.segmentIndexSource=null);this.H&&(this.H.destroy(),this.H=null)};function Gd(a){var b=a.a||"";a.c&&(b+='; codecs="'+a.c+'"');return b}
function Hd(){this.A=Id++;this.id=null;this.contentType=this.lang="";this.b=!1;this.streamInfos=[];this.a=[]}var Id=0;Hd.prototype.destroy=function(){for(var a=0;a<this.streamInfos.length;++a)this.streamInfos[a].destroy();this.a=this.streamInfos=null};function Jd(a){for(var b=[],c=0;c<a.a.length;++c){var d=new Kd;d.id=a.A;d.a=a.a[c];d.contentType=a.contentType;d.b=a.streamInfos.length?Gd(a.streamInfos[0]):"";b.push(d)}return b}
function Ld(){this.id=null;this.start=0;this.a=null;this.streamSetInfos=[]}Ld.prototype.destroy=function(){for(var a=0;a<this.streamSetInfos.length;++a)this.streamSetInfos[a].destroy();this.streamSetInfos=null};function Md(){this.a=!1;this.g=this.f=this.c=null;this.b=0;this.periodInfos=[]}Md.prototype.destroy=function(){for(var a=0;a<this.periodInfos.length;++a)this.periodInfos[a].destroy();this.periodInfos=null};function Kd(){this.id=0;this.a=null;this.b=this.contentType=""};function Nd(a,b,c,d,e){E.call(this,a);this.c=b;this.a=new ub(c,d,e);this.s=this.segmentIndex_=this.b=null;this.D=!1;this.g=null;this.l=!1;this.i=null;this.m=!1;this.h=new F;this.j=this.f=!1;this.v=0;this.G=15;this.B=!1}p(Nd,E);Nd.prototype.C=function(a){null!=a.initialStreamBufferSize&&(this.v=Number(a.initialStreamBufferSize));null!=a.streamBufferSize&&(this.G=Number(a.streamBufferSize));null!=a.segmentRequestTimeout&&(this.a.m=Number(a.segmentRequestTimeout))};
Nd.prototype.destroy=function(){Od(this);this.h.destroy();this.b=this.h=null;this.a.destroy();this.w=this.c=this.a=null};l=Nd.prototype;l.ga=function(){return this.b};l.Na=function(){return this.segmentIndex_};l.Wa=function(a){this.f||a.then(function(){this.f=!0;this.g||Pd(this,0)}.bind(this)).catch(function(){});return this.h};l.ua=function(){return this.j};
l.ia=function(a,b,c){if(a!=this.b){var d=[a.segmentIndexSource.create(),a.H.create()];Promise.all(d).then(G(this,function(d){if(this.c){var f=this.b;this.b=a;this.segmentIndex_=d[0];this.s=d[1];this.D=!0;this.l||(f?b&&Qd(this,!0,c):Pd(this,0))}})).catch(G(this,function(a){"aborted"!=a.type&&(this.f?(a=x(a),this.dispatchEvent(a)):this.h.reject(a))}))}};l.Sa=function(){return Qd(this,!1)};
function Qd(a,b,c){a.b&&!a.l&&(a.l=!0,Od(a),wb(a.a).then(G(a,function(){var a=this.c.currentTime;if(!b&&0<xb(this.a,a)&&0<=Ab(this.a.b,a))return Promise.resolve();if(c)return Db(this.a,this.c.currentTime+c);this.B=!0;return Cb(this.a)})).then(G(a,function(){this.l=!1;Pd(this,0)})).catch(G(a,function(a){this.l=!1;this.f?(a=x(a),this.dispatchEvent(a)):this.h.reject(a)})))}l.Ta=function(a){return 0<xb(this.a,a)&&0<=Ab(this.a.b,a)};l.na=function(){};l.ra=function(){return!0};
l.sb=function(){if(this.m&&!this.f)this.g=null;else{var a;if(a=this.f&&!this.j)a=1<this.a.c.buffered.length?!0:!1;if(a)Qd(this,!0);else{this.g=null;a=this.b;var b=this.segmentIndex_,c=this.c.currentTime;xb(this.a,this.m?c:c+(this.i||0))>=(this.m?Math.max(this.v,this.G):this.v)?(Rd(this),Pd(this,1E3/(Math.abs(this.c.playbackRate)||1))):(b=Sd(this,c,b))?(b=this.a.fetch(b,a.b,this.s),this.s=null,this.D&&(this.D=!1,Td(this,a)),this.j=!1,b.then(G(this,function(a){null==this.i&&(this.i=a);this.B&&0<xb(this.a,
c)&&(this.B=!1,this.c.currentTime+=.001);Pd(this,0)})).catch(G(this,function(a){if("aborted"!=a.type){var b=[0,404,410];"net"==a.type&&-1!=b.indexOf(a.xhr.status)&&this.b&&Pd(this,5E3);a=x(a);this.dispatchEvent(a)}}))):(Rd(this),this.f&&!this.j&&(this.j=!0,Ud(this)),Pd(this,1E3))}}};function Sd(a,b,c){a=a.a;var d=a.b.length;a=0<d?a.b[d-1]:null;return null!=a?null!=a.endTime?c.ca(a.endTime):null:c.ca(b)||(c.length()?c.u():null)}
function Rd(a){if(!a.m&&null!=a.i){a.m=!0;var b=a.a,c=a.i,d=c-b.w;0!=d&&(b.b=ud(b.b,d),b.w=c);a.h.resolve(a.i)}}function Td(a,b){var c;c=b.a.split("/")[0];c=v({type:"adaptation",bubbles:!0,contentType:c,size:"video"!=c?null:{width:b.width,height:b.height},bandwidth:b.bandwidth});a.dispatchEvent(c)}function Ud(a){var b=v({type:"ended"});a.dispatchEvent(b)}function Pd(a,b){a.g=window.setTimeout(a.sb.bind(a),b)}function Od(a){null!=a.g&&(window.clearTimeout(a.g),a.g=null)};function Vd(a){this.a=a;this.segmentIndex_=null}Vd.prototype.destroy=function(){this.segmentIndex_&&(this.segmentIndex_.destroy(),this.segmentIndex_=null)};Vd.prototype.create=function(){if(this.segmentIndex_)return Promise.resolve(this.segmentIndex_);var a=new pd(0,null,this.a);this.segmentIndex_=new R([a]);return Promise.resolve(this.segmentIndex_)};function Wd(a,b){E.call(this,a);this.b=b;this.g=!0;this.segmentIndex_=this.f=null;this.c=new F;this.a=null}p(Wd,E);Wd.prototype.C=function(){};Wd.prototype.destroy=function(){this.a&&this.b.removeChild(this.a);this.c.destroy();this.w=this.b=this.f=this.segmentIndex_=this.a=this.c=null};l=Wd.prototype;l.ga=function(){return this.f};l.Na=function(){return this.segmentIndex_};l.Wa=function(){return this.c};l.ua=function(){return!0};
l.ia=function(a){a.segmentIndexSource.create().then(G(this,function(b){if(this.b){if(0==b.length())return Promise.reject(Error("No subtitles URL available."));var c=this.f;this.f=a;this.segmentIndex_=b;b=S(b).url.T[0].toString();var d=this.ra();this.a&&(this.na(!1),this.b.removeChild(this.a));this.a=document.createElement("track");this.b.appendChild(this.a);this.a.src=b;this.na(d);b=v({type:"adaptation",bubbles:!0,contentType:"text",size:null,bandwidth:a.bandwidth});this.dispatchEvent(b);c||this.c.resolve(0)}}))};
l.Sa=function(){};l.Ta=function(){return!0};l.na=function(a){this.g=a;this.a&&(this.a.track.mode=a?"showing":"disabled")};l.ra=function(){this.a&&(this.g="showing"==this.a.track.mode);return this.g};function Xd(a){this.a=a}
function Yd(a,b,c){for(var d=u()/1E3,e=0;e<b.a.length;++e)for(var f=b.a[e],g=0;g<f.b.length;++g){var h=f.b[g];if("text"!=h.contentType)for(var k=0;k<h.a.length;++k){var m=h.a[k],q=0,q=q+(m.g?1:0),q=q+(m.b?1:0),q=q+(m.a?1:0);0==q?(h.a.splice(k,1),--k):1!=q&&(m.g?(m.b=null,m.a=null):m.b&&(m.a=null))}}Zd(b);for(e=0;e<b.a.length;++e)for(f=b.a[e],g=0;g<f.b.length;++g){k=h=f.b[g];m=null;for(q=0;q<k.a.length;++q){var w=k.a[q].f||"";m?w!=m&&(k.a.splice(q,1),--q):m=w}0==h.a.length&&(f.b.splice(g,1),--g)}"dynamic"==
b.type&&null==b.c&&(b.c=d);e=new Md;"dynamic"==b.type&&(e.a=!0,e.c=b.g,e.f=new H(c,b.j||b.url),e.g=b.c);e.b=b.h||5;for(f=0;f<b.a.length;++f){g=b.a[f];if(null==g.start)break;g=$d(a,b,g,d,c);e.periodInfos.push(g)}return e}
function Zd(a){if(a.a.length){null==a.a[0].start&&(a.a[0].start=0);var b=function(a){return 0==a||!!a};"dynamic"==a.type&&(a.b=null);b(a.b)&&1==a.a.length&&!b(a.a[0].a)&&(a.a[0].a=a.b);for(var c=0,d=!0,e=0;e<a.a.length;++e){var f=a.a[e-1],g=a.a[e],h=a.a[e+1]||{start:a.b};!b(g.start)&&f&&b(f.start)&&b(f.a)&&(g.start=f.start+f.a);!b(g.a)&&b(h.start)&&(g.a=h.start-g.start);null!=g.start&&null!=g.a?c+=g.a:d=!1}b(a.b)||(e=a.a[a.a.length-1],d?a.b=c:b(e.start)&&b(e.a)?a.b=e.start+e.a:"dynamic"!=a.type&&
(a.b=c))}}function $d(a,b,c,d,e){var f=new Ld;f.id=c.id;f.start=c.start;f.a=c.a;var g=new z;c.b.forEach(function(a){g.push(a.contentType||"",a)});for(var h=A(g),k=0;k<h.length;++k){var m=new z;g.get(h[k]).forEach(function(a){m.push(a.group,a)});for(var q=A(m),w=0;w<q.length;++w){var D=new z;m.get(q[w]).forEach(function(a){D.push(a.lang,a)});for(var V=A(D),jc=0;jc<V.length;++jc){var kc=D.get(V[jc]),kc=ae(a,b,c,kc,d,e);f.streamSetInfos.push(kc)}}}return f}
function ae(a,b,c,d,e,f){ba(d.every(function(a){return a.group==d[0].group&&(a.lang||"")==(d[0].lang||"")&&(a.contentType||"")==(d[0].contentType||"")}));var g=new Hd,h=d.filter(function(a){return null!=a.id});h.length==d.length&&(g.id=h.map(function(a){return a.id}).sort().reduce(function(a,b){return a+","+b}));g.lang=d[0].lang||"";g.contentType=d[0].contentType||"";g.b=d.some(function(a){return a.c});for(var h={},k=0;k<d.length;++k)for(var m=d[k],q=0;q<m.a.length;++q){var w=m.a[q],D=be(a,w),V=g.a.slice(0);
ce(D,V);0==V.length&&0<g.a.length||!(w=de(b,c,w,e,f))||(g.streamInfos.push(w),g.a=V,h[w.A]=m)}if(g.a.some(function(a){return""==a.a}))return g.streamInfos.forEach(function(a){a.I=!0}),g;a=ee(d);for(k=0;k<g.streamInfos.length;++k)w=g.streamInfos[k],m=h[w.A],m==a&&(w.I=!0);return g}function ee(a){for(var b=null,c=null,d=0;d<a.length;++d)for(var e=a[d],f=0;f<e.a.length;++f){var g=e.a[f],g=(g.width||1)*(g.height||1)*(g.bandwidth||1);if(null==b||g<b)b=g,c=e}return c}
function ce(a,b){if(0==b.length)Array.prototype.push.apply(b,a);else for(var c=0;c<b.length;++c){for(var d=!1,e=0;e<a.length;++e){var f=b[c],g=a[e];if(f.a==g.a&&f.h==g.h&&f.j==g.j&&f.g==g.g&&f.i==g.i&&f.f==g.f&&f.l==g.l&&Jb(f.c,g.c)){d=!0;Mb(b[c],a[e].b);break}}d||(b.splice(c,1),--c)}}function be(a,b){var c=[];if(0==b.c.length)c.push(new Kb);else if(a.a)for(var d=0;d<b.c.length;++d)c.push.apply(c,fe(a,b.c[d]));return c}
function fe(a,b){var c=[];if(2!=a.a.length)return[];var d=a.a(b.c||"",b.f);if(!(d&&d instanceof Array))return[];for(var e=0;e<d.length;++e){var f;var g=d[e];f=new Kb;if(g){var h=y(g,"keySystem");if(null!=h)f.a=h;else throw Error("'keySystem' cannot be null.");var k=y(g,"licenseServerUrl");if(null!=k)f.h=k;else if(h)throw Error("For encrypted streaming content, 'licenseServerUrl' cannot be null or empty.");h=fb(g,"withCredentials");null!=h&&(f.j=h);h=ib(g,"licensePostProcessor",Function);null!=h&&
(f.m=h);h=ib(g,"licensePreProcessor",Function);null!=h&&(f.w=h);h=fb(g,"distinctiveIdentifierRequired");null!=h&&(f.g=h);h=fb(g,"persistentStateRequired");null!=h&&(f.i=h);h=y(g,"audioRobustness");null!=h&&(f.f=h);h=y(g,"videoRobustness");null!=h&&(f.l=h);h=ib(g,"serverCertificate",Uint8Array);null!=h&&(f.c=h);if(h=ib(g,"initData",Object)){g=ib(h,"initData",Uint8Array);if(null==g)throw Error("'initData.initData' cannot be null.");h=y(h,"initDataType");if(null==h)throw Error("'initData.initDataType' cannot be null.");
f.b.push({initData:new Uint8Array(g.buffer),initDataType:h})}}0==f.b.length&&b.a&&b.a.psshBox&&Mb(f,[{initData:b.a.psshBox,initDataType:"cenc"}]);c.push(f)}return c}
function de(a,b,c,d,e){if(!c.o||0===c.o.length)return null;var f=null,g=1,h=0;if(c.g)f=null,g=c.g.c,h=c.g.b;else if(c.b)f=c.b,!f.b&&!f.c&&1<f.a.length?f=null:f.b||b.a||f.c||1!=f.a.length?f.c&&0===f.c.a.length?f=null:(f=f.h?ge(f.h,e):null,a=new Cd(a,b,c,d,e),b=new sd(f),d=new Ed,d.segmentIndexSource=a,d.H=b,f=d):f=null,g=c.b.f,h=c.b.g;else if(c.a){a:if(f=c.a,g=0+(f.f?1:0),g+=f.c?1:0,g+=f.b?1:0,0==g?g=!1:(1!=g&&(f.f?(f.c=null,f.b=null):f.c&&(f.b=null)),g=!0),g){g=null;if(f.g&&((f=c.a.g)?(f=qd(f,c.id,
null,c.bandwidth,null))?(g=new Nc,g.url=jd(c.o,f),f=g):f=null:f=null,g=f,!g)){f=null;break a}f=g?ge(g,e):null;g=c.a;a=g.f?null:g.h?g.c?new Dd(a,b,c,d,e):g.b?"dynamic"!=a.type&&null==b.a?null:new Bd(a,b,c,d,e):null:null;a?(b=new sd(f),d=new Ed,d.segmentIndexSource=a,d.H=b,f=d):f=null}else f=null;g=c.a.a;h=c.a.i}else"text"==c.f.split("/")[0]&&(f=new Ed,f.segmentIndexSource=new Vd(new H(e,c.o)));if(!f)return null;f.id=c.id;h&&(f.b=-1*h/g);f.bandwidth=c.bandwidth;f.width=c.width;f.height=c.height;f.a=
c.f||"";f.c=c.h||"";for(a=0;a<c.c.length;++a)b=c.c[a],b.b&&f.f.push(b.b);return f}function ge(a,b){var c=a.url,d=0,e=null;a.a&&(d=a.a.fa,e=a.a.end);return new H(b,c,d,e)};function he(){this.streamStats=null;this.droppedFrames=this.decodedFrames=NaN;this.bufferingTime=this.playTime=this.estimatedBandwidth=0;this.playbackLatency=NaN;this.bufferingHistory=[];this.bandwidthHistory=[];this.streamHistory=[]}function ie(a,b){var c=new je(b);a.streamHistory.push(new ke(c));if(c.videoHeight||!a.streamStats)a.streamStats=c}function je(a){this.videoWidth=a.width;this.videoHeight=a.height;this.videoMimeType=a.a;this.videoBandwidth=a.bandwidth}
function ke(a){this.timestamp=u()/1E3;this.value=a};function le(a,b,c,d,e){this.b=new H(null,[new I(a)]);this.a=new zb;this.a.body=b;this.a.method=c;this.a.a=3;this.a.i=d;this.a.c=0;a=e||{};for(var f in a)this.a.b[f]=a[f]}function me(a){return a.b.fetch(a.a).then(function(a){return Promise.resolve(new Uint8Array(a))})};function ne(a,b,c){E.call(this,a);this.c=b;this.j=c;this.a=this.h=null;this.i=new B;this.b=[];this.f=[];this.m=0;this.g=new F;this.l=null}p(ne,E);ne.prototype.destroy=function(){this.w=null;for(var a=0;a<this.f.length;++a)this.f[a].close().catch(function(){});this.f=[];this.b=this.a=this.h=null;this.g.destroy();this.g=null;this.i.destroy();this.i=null;this.l&&(window.clearTimeout(this.l),this.l=null);this.c=this.j=null};
ne.prototype.initialize=function(){var a=new z,b;b=this.j;if(b.C){b=b.a.periodInfos[0];for(var c=[],d=0;d<b.streamSetInfos.length;++d)c.push.apply(c,Jd(b.streamSetInfos[d]));b=c}else b=[];for(c=0;c<b.length;++c)d=b[c],d.a.a||d.b&&!oe(d.b)||a.push(d.contentType,d);for(var c={},d=!1,e=0;e<b.length;++e){var f=b[e];if(f.a.a&&!a.a.hasOwnProperty(f.contentType)){var g=f.a.a,h=c[g];h||(h=f.a,h={audioCapabilities:void 0,videoCapabilities:void 0,initDataTypes:void 0,distinctiveIdentifier:h.g?"required":"optional",
persistentState:h.i?"required":"optional",sessionTypes:["temporary"]},c[g]=h);if(f.b&&(g=f.contentType+"Capabilities",g in h)){d=!0;h[g]||(h[g]=[]);var k;"audio"==f.contentType?k=f.a.f:"video"==f.contentType&&(k=f.a.l);h[g].push({contentType:f.b,robustness:k})}}}if(!d)if(b.length)this.a=b[0].a;else throw a=Error("No DrmInfo exists!"),a.type="drm",a;if(0==Object.keys(c).length)return pe(this.j,a),this.g.resolve(),Promise.resolve();k=new F;c=qe(c,k);c=c.then(this.v.bind(this,b,a));k.reject(null);return c};
function qe(a,b){for(var c in a)b=b.catch(function(a,b){return navigator.requestMediaKeySystemAccess(a,[b])}.bind(null,c,a[c]));return b}
ne.prototype.v=function(a,b,c){if(!this.c)return re();for(var d=c.keySystem,e=c.getConfiguration(),f=["audio","video"],g=0;g<f.length;++g){var h=f[g];if(!b.a.hasOwnProperty(h)){var k=e[h+"Capabilities"];if(k){for(var k=k[0],m=[],q={},w=0;w<a.length;++w){var D=a[w],V=k?D.b==k.contentType:D.contentType==h;D.a.a!=d||!V||D.id in q||(m.push(D),q[D.id]=!0,this.a=this.a?Lb(this.a,D.a):D.a)}b.set(h,m)}}}pe(this.j,b);return c.createMediaKeys().then(function(a){this.h=a}.bind(this))};
function se(a){return a.c?a.h?a.c.setMediaKeys(a.h).then(G(a,function(){return this.c?this.a.c?this.h.setServerCertificate(this.a.c):Promise.resolve():re()})).then(G(a,function(){if(!this.c)return re();for(var a=0;a<this.a.b.length;++a){var c=this.a.b[a];this.s({type:"encrypted",initDataType:c.initDataType,initData:c.initData})}0==this.a.b.length&&C(this.i,this.c,"encrypted",this.s.bind(this))})):Promise.resolve():re()}
function re(){var a=Error("EmeManager destroyed");a.type="destroy";return Promise.reject(a)}
ne.prototype.s=function(a){for(var b=new Uint8Array(a.initData),c=0;c<this.b.length;++c)if(Jb(b,this.b[c].data))return;try{var d=te(this)}catch(e){b=x(e);this.dispatchEvent(b);this.g.reject(e);return}a=d.generateRequest(a.initDataType,a.initData);this.b.push({data:b,xa:d});a.catch(G(this,function(a){if(this.c){for(var b=0;b<this.b.length;++b)if(this.b[b].xa==d){this.b.splice(b,1);break}b=x(a);this.dispatchEvent(b);this.g.reject(a)}}));this.f.push(d)};
function te(a){var b=null,b=a.h.createSession();C(a.i,b,"message",a.C.bind(a));C(a.i,b,"keystatuseschange",a.B.bind(a));return b}ne.prototype.C=function(a){ue(this,a.target,this.a,a.message)};
ne.prototype.B=function(a){a=a.target;var b={};a.keyStatuses.forEach(function(a,c){if("string"==typeof a){var f=a;a=c;c=f}if("com.microsoft.playready"==this.a.a&&16==a.byteLength){var f=new DataView(a),g=f.getUint32(0,!0),h=f.getUint16(4,!0),k=f.getUint16(6,!0);f.setUint32(0,g,!1);f.setUint16(4,h,!1);f.setUint16(6,k,!1)}f=Ib(new Uint8Array(a));b[f]=c}.bind(this));if(a.expiration<Date.now()){for(var c=0;c<this.b.length;++c)if(this.b[c].xa==a){this.b.splice(c,1);break}a.close();this.f.splice(this.f.indexOf(a),
1)}ve(this.j,b)};function ue(a,b,c,d){d=we(c,d);me(new le(d.url,d.body,d.method,c.j,d.headers)).then(G(a,function(a){c.m&&(a=c.m(a));return b.update(a)})).then(G(a,function(){var a=v({type:"sessionReady",detail:b});this.dispatchEvent(a);this.m++;this.m>=this.f.length&&this.g.resolve()})).catch(G(a,function(a){a.xa=b;a=x(a);this.dispatchEvent(a)}))}
function we(a,b){var c={url:a.h,body:b.slice(0),method:"POST",headers:{}};if("com.microsoft.playready"===a.a){for(var d=String.fromCharCode.apply(null,new Uint16Array(c.body)),d=(new DOMParser).parseFromString(d,"application/xml"),e=d.getElementsByTagName("name"),f=d.getElementsByTagName("value"),g=0;g<e.length;g++)c.headers[e[g].childNodes[0].nodeValue]=f[g].childNodes[0].nodeValue;c.body=window.atob(d.getElementsByTagName("Challenge")[0].childNodes[0].nodeValue)}if(!a.w)return c;a.w(c);c.url=y(c,
"url");if(null==c.url)throw Error("'url' cannot be null.");if(!(c.body instanceof ArrayBuffer||"string"==typeof c.body||null==c.body))throw new TypeError("'body' must be an ArrayBuffer, a string, or null.");c.method=y(c,"method");if("GET"!=c.method&&"POST"!=c.method)throw Error("'method' must be either 'GET' or 'POST'.");c.headers=ib(c,"headers",Object);if(null==c.headers)throw Error("'headers' cannot be null.");return c};function W(a){E.call(this,null);this.a=a;this.b=null;this.f=new B;this.j=this.i=null;this.B=0;this.s=null;this.h=!1;this.g=new he;this.c={enableAdaptation:!0,streamBufferSize:15,liveStreamEndTimeout:15,licenseRequestTimeout:0,mpdRequestTimeout:0,segmentRequestTimeout:0,preferredLanguage:"en",restrictions:new ja};this.l=1;this.C=null}p(W,E);n("shaka.player.Player",W);W.version="v1.6.5-hola-2-4-gb56db77-dirty";
W.isBrowserSupported=function(){return!!window.MediaSource&&!!window.MediaKeys&&!!window.navigator&&!!window.navigator.requestMediaKeySystemAccess&&!!window.MediaKeySystemAccess&&!!window.MediaKeySystemAccess.prototype.getConfiguration&&!!window.Promise&&!!Element.prototype.requestFullscreen&&!!document.exitFullscreen&&"fullscreenElement"in document&&!!window.Uint8Array};function oe(a){return"text/vtt"==a?!!window.VTTCue:MediaSource.isTypeSupported(a)}W.isTypeSupported=oe;
W.setTextStyle=function(a){var b=document.getElementById("ShakaPlayerTextStyle");b||(b=document.createElement("style"),b.id="ShakaPlayerTextStyle",document.head.appendChild(b));for(b=b.sheet;b.cssRules.length;)b.deleteRule(0);b.insertRule("::cue { "+oa(a)+" }",0)};W.prototype.destroy=function(){return this.m().then(G(this,function(){this.f.destroy();this.a=this.f=null})).catch(function(){})};W.prototype.destroy=W.prototype.destroy;
W.prototype.m=function(){if(!this.b)return Promise.resolve();this.h&&xe(this);this.a.pause();lb(this.f);ye(this);ze(this);this.i&&(this.i.destroy(),this.i=null);this.a.src="";var a=this.a.setMediaKeys(null);this.b&&(this.b.destroy(),this.b=null);this.h=!1;this.g=new he;return a};W.prototype.unload=W.prototype.m;W.prototype.M=function(){return this.a};W.prototype.getVideo=W.prototype.M;W.prototype.O=function(){return this.b};W.prototype.getVideoSource=W.prototype.O;
W.prototype.ea=function(a){var b=this.m();this.a.autoplay&&(da("load"),C(this.f,this.a,"timeupdate",this.eb.bind(this)));a.Ha(this.c);a.P=this.C;this.C=null;b=b.then(G(this,function(){return a.za()}));b.catch(G(this,function(b){a.destroy();return Promise.reject(b)}));return b.then(G(this,function(){if(!this.a)return Ae();this.b=a;C(this.f,this.b,"seekrangechanged",this.nb.bind(this));this.i=new ne(this,this.a,this.b);return this.i.initialize()})).then(G(this,function(){if(!this.a)return Ae();C(this.f,
this.a,"error",this.xb.bind(this));C(this.f,this.a,"playing",this.lb.bind(this));C(this.f,this.a,"pause",this.kb.bind(this));var a;a=this.b;var b=this.a;a.C?(a.w=this,a.video=b,a.video.shaka=this,a.G=this.Ua(),C(a.h,a.f,"sourceopen",a.gb.bind(a)),C(a.h,a.Z,"bandwidth",a.yb.bind(a)),a.a.a&&(C(a.h,this,"bufferingStart",a.cb.bind(a)),C(a.h,this,"bufferingEnd",a.bb.bind(a))),b=a.video.mediaKeys,a.video.src=window.URL.createObjectURL(a.f),b=a.video.setMediaKeys(b),a=Promise.all([a.l,b])):(a=Error("Cannot call attach() right now."),
a.type="app",a=Promise.reject(a));Za("shaka_message",{id:"attach",Bb:this,video:this.a});return a})).then(G(this,function(){return this.a?se(this.i):Ae()})).then(G(this,function(){if(!this.a)return Ae();Be(this)})).catch(G(this,function(a){if(!this.a)return Ae();if("destroy"!=a.type){var b=x(a);this.dispatchEvent(b)}return this.m().then(function(){return Promise.reject(a)})}))};W.prototype.load=W.prototype.ea;
function Ae(){var a=Error("Player destroyed");a.type="destroy";return Promise.reject(a)}l=W.prototype;l.eb=function(){ga("load");this.g.playbackLatency=ha("load")/1E3;this.f.ja(this.a,"timeupdate")};l.xb=function(){if(this.a.error){var a=this.a.error.code;a!=MediaError.MEDIA_ERR_ABORTED&&(a=Error(Ce[a]||"Unknown playback error."),a.type="playback",a=x(a),this.dispatchEvent(a))}};
l.lb=function(){da("playing");!this.j&&0>this.l&&(this.a.playbackRate=0,this.v(this.a.currentTime,Date.now(),this.l));this.h&&xe(this)};l.kb=function(){ga("playing");var a=ha("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3}ze(this)};l.nb=function(a){this.B=a.start};
l.Ua=function(){if(!this.a.paused){ga("playing");var a=ha("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3;da("playing")}}a=this.g;b=this.a;b.getVideoPlaybackQuality&&(b=b.getVideoPlaybackQuality(),a.decodedFrames=b.totalVideoFrames,a.droppedFrames=b.droppedVideoFrames);return this.g};W.prototype.getStats=W.prototype.Ua;W.prototype.da=function(){return this.b?this.b.ha():[]};W.prototype.getVideoTracks=W.prototype.da;W.prototype.Y=function(){return this.b?this.b.Y():[]};
W.prototype.getAudioTracks=W.prototype.Y;W.prototype.$=function(){return this.b?this.b.Ia():[]};W.prototype.getTextTracks=W.prototype.$;W.prototype.selectVideoTrack=function(a,b){return this.b?this.b.selectVideoTrack(a,void 0==b?!0:b):!1};W.prototype.selectVideoTrack=W.prototype.selectVideoTrack;W.prototype.ka=function(a,b,c){return this.b?De(this.b,"audio",a,void 0==b?!0:b,c):!1};W.prototype.selectAudioTrack=W.prototype.ka;W.prototype.la=function(a){return this.b?De(this.b,"text",a,!1):!1};
W.prototype.selectTextTrack=W.prototype.la;W.prototype.X=function(a){this.b&&Ee(this.b,a)};W.prototype.enableTextTrack=W.prototype.X;W.prototype.V=function(a){ze(this);0<=a?this.a.playbackRate=a:this.a.paused||(this.a.playbackRate=0,this.v(this.a.currentTime,Date.now(),a));this.l=a};W.prototype.setPlaybackRate=W.prototype.V;W.prototype.G=function(){return this.l};W.prototype.getPlaybackRate=W.prototype.G;W.prototype.ma=function(a){this.C=a};W.prototype.setPlaybackStartTime=W.prototype.ma;
W.prototype.D=function(){var a;this.b?(a=this.b,a=a.a?a.a.a:!1):a=!1;return a};W.prototype.isLive=W.prototype.D;
W.prototype.W=function(a){if(a){var b=fb(a,"enableAdaptation");null!=b&&(this.c.enableAdaptation=b);b=hb(a,"streamBufferSize");null!=b&&(this.c.streamBufferSize=b);b=hb(a,"liveStreamEndTimeout");null!=b&&(this.c.liveStreamEndTimeout=b);b=hb(a,"licenseRequestTimeout");null!=b&&(this.c.licenseRequestTimeout=b);b=hb(a,"mpdRequestTimeout");null!=b&&(this.c.mpdRequestTimeout=b);b=hb(a,"segmentRequestTimeout");null!=b&&(this.c.segmentRequestTimeout=b);b=y(a,"preferredLanguage");null!=b&&(this.c.preferredLanguage=
b);b=ib(a,"restrictions",ja);null!=b&&(this.c.restrictions=b.clone());a=fb(a,"disableCacheBustingEvenThoughItMayAffectBandwidthEstimation");null!=a&&(ed=!a);this.b&&this.b.Ha(this.c)}};W.prototype.configure=W.prototype.W;W.prototype.Z=function(){return this.c};W.prototype.getConfiguration=W.prototype.Z;function ze(a){a.j&&(window.clearTimeout(a.j),a.j=null)}function Be(a){ye(a);a.s=window.setTimeout(a.P.bind(a),100)}function ye(a){a.s&&(window.clearTimeout(a.s),a.s=null)}
W.prototype.v=function(a,b,c){this.j=null;var d=(Date.now()-b)/1E3*c;this.a.currentTime<this.B+(this.D()?1:.05)?this.a.pause():(d=Math.max(this.B,a+d),this.a.currentTime=d,this.j=window.setTimeout(this.v.bind(this,a,b,c),250))};function xe(a){ga("buffering");var b=a.g;b.bufferingTime+=ha("buffering")/1E3;a.h=!1;a.dispatchEvent(v({type:"bufferingEnd"}))}
W.prototype.P=function(){Be(this);if(!this.a.ended&&!this.a.seeking){var a=this.a.buffered,b=a.length?a.end(a.length-1):0,a=Math.max(b-this.a.currentTime,0),c=this.a.duration,c=isNaN(c)?0:Math.max(c-.05,0),b=b>=c||this.a.currentTime>=c;if(this.h){if(c=Number(this.b.s.initialStreamBufferSize),b||a>c)xe(this),this.a.play()}else!this.a.paused&&!b&&.5>a&&(this.h=!0,this.a.pause(),this.g.bufferingHistory.push(u()/1E3),da("buffering"),this.dispatchEvent(v({type:"bufferingStart"})))}};
var Ce={2:"A network failure occured while loading media content.",3:"The browser failed to decode the media content.",4:"The browser does not support the media content."};function Fe(a){for(var b=0;b<a.length;++b)for(var c=a[b],d=0;d<c.streamSetInfos.length;++d){for(var e=c.streamSetInfos[d],f=e,g=0;g<f.streamInfos.length;++g)oe(Gd(f.streamInfos[g]))||(f.streamInfos.splice(g,1),--g);0==e.streamInfos.length&&(c.streamSetInfos.splice(d,1),--d)}}function Ge(a){for(var b=0;b<a.length;++b)for(var c=a[b],d=0;d<c.streamSetInfos.length;++d)c.streamSetInfos[d].streamInfos.sort(He)}
function He(a,b){var c=a.bandwidth||Number.MAX_VALUE,d=b.bandwidth||Number.MAX_VALUE;return c<d?-1:c>d?1:0};function Ie(a){this.a=a}Ie.prototype.destroy=function(){this.a.destroy();this.a=null};Ie.prototype.update=function(a){var b=Je(a),c=Je(this.a);return Promise.all([b,c]).then(G(this,function(b){var c=b[0];b=b[1];var f=this.a.periodInfos;Fe(f);Ge(f);a.c=this.a.c;a.f=this.a.f?this.a.f.clone():null;a.b=this.a.b;f=[];Ke(a,this.a,c,b,f);c=a.periodInfos;Fe(c);Ge(c);return Promise.resolve(f)}))};
function Je(a){function b(a,b){return a.concat(b)}var c=a.periodInfos.map(function(a){return a.streamSetInfos}).reduce(b,[]).map(function(a){return a.streamInfos}).reduce(b,[]);a=c.map(function(a){return a.segmentIndexSource.create()});return Promise.all(a).then(function(a){for(var b={},f=0;f<c.length;++f)b[c[f].A]=a[f];return Promise.resolve(b)})}
function Ke(a,b,c,d,e){var f=new z;a.periodInfos.forEach(function(a,b){f.push(a.id||""+b,a)});var g=new z;b.periodInfos.forEach(function(a,b){g.push(a.id||""+b,a)});a=A(f);for(b=0;b<a.length;++b){var h=a[b],k=f.get(h);1<k.length||(h=g.get(h))&&0!=h.length&&1==h.length&&(Le(k[0],h[0],c,d,e),k[0].a=h[0].a)}}
function Le(a,b,c,d,e){var f=new z;a.streamSetInfos.forEach(function(a,b){f.push(a.id||""+b,a)});var g=new z;b.streamSetInfos.forEach(function(a,b){g.push(a.id||""+b,a)});a=A(f);for(b=0;b<a.length;++b){var h=a[b],k=f.get(h);1<k.length||(h=g.get(h))&&0!=h.length&&1==h.length&&Me(k[0],h[0],c,d,e)}}
function Me(a,b,c,d,e){var f=new z;a.streamInfos.forEach(function(a,b){f.push(a.id||""+b,a)});var g=new z;b.streamInfos.forEach(function(a,b){g.push(a.id||""+b,a)});b={};for(var h=A(f),k=0;k<h.length;++k){var m=h[k];b[m]=m;var q=f.get(m);1<q.length||((m=g.get(m))&&0!=m.length?1==m.length&&(Ne(q[0],m[0],c,d),q[0].H=m[0].H,m[0].H=null,q[0].b=m[0].b):(e.push(q[0]),a.streamInfos.splice(a.streamInfos.indexOf(q[0]),1)))}h=A(g);for(k=0;k<h.length;++k)m=h[k],b[m]||(b[m]=m,m=g.get(m),a.streamInfos.push(m[0]))}
function Ne(a,b,c,d){a=c[a.A];b=d[b.A];a.length();a.va(b)&&a.length()};function X(){this.a=this.b=null;this.f=new B;this.c=Number.POSITIVE_INFINITY;this.i=!0;this.g=!1}n("shaka.media.SimpleAbrManager",X);X.prototype.destroy=function(){this.f.destroy();this.a=this.b=this.f=null};X.prototype.initialize=function(a,b){this.b||this.a||(this.b=a,this.a=b)};
X.prototype.start=function(){this.b&&this.a&&!this.g&&(this.c=Date.now()+4E3,C(this.f,this.b,"bandwidth",this.l.bind(this)),C(this.f,this.a,"adaptation",this.j.bind(this)),C(this.f,this.a,"trackschanged",this.h.bind(this)),this.g=!0)};X.prototype.enable=function(a){this.i=a};X.prototype.getInitialVideoTrackId=function(){if(!this.b||!this.a)return null;var a=Oe(this);return a?a.id:null};X.prototype.selectVideoTrack=function(a,b,c){this.g&&this.a.selectVideoTrack(a.id,b,c)};
X.prototype.l=function(){Date.now()<this.c||this.h()};X.prototype.h=function(){if(this.i){var a=Oe(this);if(a){if(a.active){this.c=Date.now()+3E3;return}this.selectVideoTrack(a,!1)}this.c=Number.POSITIVE_INFINITY}};X.prototype.j=function(){this.c==Number.POSITIVE_INFINITY&&(this.c=Date.now()+3E4)};
function Oe(a){var b=a.a.ha();if(0==b.length)return null;b.sort(sa);var c;a:{c=a.a.Y();for(var d=0;d<c.length;++d)if(c[d].active){c=c[d];break a}c=null}c=c?c.bandwidth:0;a=a.b.getBandwidth();for(var d=b[0],e=0;e<b.length;++e){var f=b[e],g=e+1<b.length?b[e+1]:{bandwidth:Number.POSITIVE_INFINITY};if(f.bandwidth&&(g=(g.bandwidth+c)/.85,a>=(f.bandwidth+c)/.95&&a<=g&&(d=f,d.active)))break}return d};function Y(a,b,c){E.call(this,null);this.a=a;this.Z=b;this.h=new B;this.f=new MediaSource;this.video=null;this.ea=0;this.b=new z;this.v=c;this.v.initialize(b,this);this.C=!1;this.B="en";this.$=!1;this.G=null;this.l=new F;this.g=new ja;this.m=null;this.Ga=1;this.c={};this.W=new F;this.Da=0;this.Ea=15;this.j=null;this.ka=this.Ca=!1;this.i={};this.P=this.O=this.M=null;this.s={}}p(Y,E);n("shaka.player.StreamVideoSource",Y);
Y.prototype.Ha=function(a){null!=a.streamBufferSize&&(this.s.streamBufferSize=a.streamBufferSize);null!=a.segmentRequestTimeout&&(this.s.segmentRequestTimeout=a.segmentRequestTimeout);Pe(this);null!=a.enableAdaptation&&this.v.enable(Boolean(a.enableAdaptation));null!=a.mpdRequestTimeout&&(this.ea=Number(a.mpdRequestTimeout));null!=a.liveStreamEndTimeout&&(this.Ea=Number(a.liveStreamEndTimeout));null!=a.preferredLanguage&&(this.B=ab(String(a.preferredLanguage)));null!=a.restrictions&&(this.g=a.restrictions,
this.C&&Qe(this))};Y.prototype.destroy=function(){this.l.destroy();this.W.destroy();this.W=this.l=null;this.O&&(window.clearTimeout(this.O),this.O=null);this.M&&(window.clearTimeout(this.M),this.M=null);this.i=null;this.h.destroy();this.h=null;eb(this.c).forEach(function(a){a.destroy()});this.b=this.c=null;this.a&&(this.a.destroy(),this.a=null);this.v.destroy();this.f=this.Z=this.v=null;this.video&&(delete this.video.shaka,this.video=null);this.w=this.g=this.G=null};l=Y.prototype;
l.za=function(){if(this.C){var a=Error("Cannot call load() right now.");a.type="app";return Promise.reject(a)}if(!this.a||0==this.a.periodInfos.length)return a=Error("The manifest does not specify any content."),a.type="stream",Promise.reject(a);a=this.a.periodInfos;Fe(a);Ge(a);if(0==this.a.periodInfos.length||0==this.a.periodInfos[0].streamSetInfos.length)return a=Error("The manifest specifies content that cannot be displayed on this browser/platform."),a.type="stream",Promise.reject(a);this.C=!0;
this.s.initialStreamBufferSize=this.a.b;Pe(this);Qe(this);return Promise.resolve()};
l.Qa=function(a){var b=Date.now(),c=this.M=null,d=this.a.f;(a?this.Oa():this.Pa(d)).then(G(this,function(a){c=new Ie(a);return c.update(this.a)})).then(G(this,function(a){c.destroy();c=null;for(var d=0;d<a.length;++d)Re(this,a[d]);this.s.initialStreamBufferSize=this.a.b;Pe(this);Qe(this);0==Object.keys(this.c).length?Se(this):Te(this,(Date.now()-b)/1E3)})).catch(G(this,function(a){c&&(c.destroy(),c=null);"aborted"!=a.type&&(a=x(a),this.dispatchEvent(a),this.a&&Te(this,0))}))};l.Pa=function(){return Promise.reject("Cannot update manifest with this VideoSource implementation.")};
l.Oa=function(){return Promise.reject("Cannot update manifest with this VideoSource implementation.")};function Te(a,b){if(null!=a.a.c){var c=Math.max(a.a.c,3),c=Math.max(c-b,0);a.M=window.setTimeout(a.Qa.bind(a,!1),1E3*c)}}
function Re(a,b){var c=b.a.split("/")[0],d=a.c[c];if(d&&d.ga()==b){var e=a.b.get(b.a.split("/")[0]).map(function(a){return a.streamInfos}).reduce(function(a,b){return a.concat(b)},[]).filter(function(a){return a.I&&a.F});if(0==e.length){c=Error("All usable streams have been removed from the manifest.");c.type="app";c=x(c);a.dispatchEvent(c);return}a.i[c].Aa==b&&delete a.i[c];d.ia(e[0],!0);b.destroy()}b.destroy()}
l.ha=function(){if(!this.b.a.hasOwnProperty("video"))return[];for(var a=this.c.video,a=(a=a?a.ga():null)?a.A:0,b=[],c=this.b.get("video"),d=0;d<c.length;++d)for(var e=c[d],f=0;f<e.streamInfos.length;++f){var g=e.streamInfos[f];if(g.I&&g.F){var h=g.A,g=new ra(h,g.bandwidth,g.width,g.height);h==a&&(g.active=!0);b.push(g)}}return b};Y.prototype.getVideoTracks=Y.prototype.ha;
Y.prototype.Y=function(){if(!this.b.a.hasOwnProperty("audio"))return[];for(var a=this.c.audio,a=(a=a?a.ga():null)?a.A:0,b=[],c=this.b.get("audio"),d=0;d<c.length;++d)for(var e=c[d],f=e.lang,g=0;g<e.streamInfos.length;++g){var h=e.streamInfos[g];if(h.I&&h.F){var k=h.A,h=new ia(k,h.bandwidth,f);k==a&&(h.active=!0);b.push(h)}}return b};Y.prototype.getAudioTracks=Y.prototype.Y;
Y.prototype.Ia=function(){if(!this.b.a.hasOwnProperty("text"))return[];for(var a=this.c.text,b=a?a.ga():null,b=b?b.A:0,c=[],d=this.b.get("text"),e=0;e<d.length;++e)for(var f=d[e],g=f.lang,h=0;h<f.streamInfos.length;++h){var k=f.streamInfos[h].A,m=new qa(k,g);k==b&&(m.active=!0,m.enabled=a.ra());c.push(m)}return c};Y.prototype.getTextTracks=Y.prototype.Ia;
function pe(a,b){if(a.C){for(var c={},d=a.a.periodInfos[0],e=0;e<d.streamSetInfos.length;++e){var f=d.streamSetInfos[e];c[f.A]=f}a.b.a={};d=A(b);for(e=0;e<d.length;++e){var f=d[e],g=b.get(f);if("video"==f){var h=g[0].id;a.b.push(f,c[h])}else if("audio"==f)for(var h=g[0].b.split(";")[0],k=0;k<g.length;++k){var m=g[k];m.b.split(";")[0]==h&&a.b.push(f,c[m.id])}else for(k=0;k<g.length;++k)h=g[k].id,a.b.push(f,c[h])}a.$=!0;if(c=a.b.get("audio"))Ue(a,c),a.b.set("audio",c),c=c[0].lang||a.B,$a(2,a.B,c)&&
(a.$=!1);if(c=a.b.get("text"))Ue(a,c),a.b.set("text",c),c=c[0].lang||a.B,$a(2,a.B,c)||(a.$=!1)}}Y.prototype.selectVideoTrack=function(a,b,c){return De(this,"video",a,b,c)};function Ee(a,b){var c=a.c.text;c&&c.na(b)}
function Qe(a){if(a.g){for(var b=!1,c=0;c<a.a.periodInfos.length;++c)for(var d=a.a.periodInfos[c],e=0;e<d.streamSetInfos.length;++e){var f=d.streamSetInfos[e];if("video"==f.contentType)for(var g=0;g<f.streamInfos.length;++g){var h=f.streamInfos[g],k=h.F;h.F=!0;a.g.maxWidth&&h.width>a.g.maxWidth&&(h.F=!1);a.g.maxHeight&&h.height>a.g.maxHeight&&(h.F=!1);a.g.minHeight&&h.height<a.g.minHeight&&(h.F=!1);a.g.maxBandwidth&&h.bandwidth>a.g.maxBandwidth&&(h.F=!1);a.g.minBandwidth&&h.bandwidth<a.g.minBandwidth&&
(h.F=!1);k!=h.F&&(b=!0)}}0!=jb(a.b).length&&b&&(Ve(a),0<a.ha().length||(b=Error("The application has restricted all video tracks!"),b.type="app",b=x(b),a.dispatchEvent(b)))}}
function ve(a,b){for(var c,d=!1,e=new z,f=jb(a.b),g=0;g<f.length;++g)for(var h=f[g],k=0;k<h.streamInfos.length;++k){var m=h.streamInfos[k];m.f.forEach(function(a){e.push(a,m)})}for(c in b)if(f=Wa[b[c]]||null,h=e.get(c))for(g=0;g<h.length;++g)m=h[g],k=m.I,m.I=!f,k!=m.I&&(d=!0);else pb(c);d&&(Ve(a),d=a.Y(),c=a.ha(),d=a.b.a.hasOwnProperty("audio")&&0==d.length,c=a.b.a.hasOwnProperty("video")&&0==c.length,d||c)&&(c=Error("The key system has restricted all "+(d&&c?"audio and video tracks.":d?"audio tracks.":
"video tracks.")),c.type="drm",c=x(c),a.dispatchEvent(c))}function Ve(a){var b=v({type:"trackschanged",bubbles:!0});a.dispatchEvent(b)}function De(a,b,c,d,e){if(!a.b.a.hasOwnProperty(b)||!a.c[b])return!1;for(var f=a.b.get(b),g=0;g<f.length;++g)for(var h=f[g],k=0;k<h.streamInfos.length;++k){var m=h.streamInfos[k];if(m.A==c){if(!m.I||!m.F)return!1;if("text"!=b&&!a.ka)return c=a.i[b],a.i[b]={Aa:m,Ja:null!=c&&c.Ja||d,Ka:null!=c&&c.Ka||e},!0;ie(a.G,m);a.c[b].ia(m,d,e);return!0}}return!1}
function Ue(a,b){for(var c=0;2>=c;++c)for(var d=0;d<b.length;++d){var e=b[d];if($a(c,a.B,e.lang)){b.splice(d,1);b.splice(0,0,e);return}}for(d=0;d<b.length;++d)if(e=b[d],e.b){b.splice(d,1);b.splice(0,0,e);break}}l=Y.prototype;l.gb=function(){this.h.ja(this.f,"sourceopen");Se(this).then(G(this,function(){this.l&&this.l.resolve()})).catch(G(this,function(a){this.l&&this.l.reject(a)}))};
function Se(a){for(var b=[],c=["audio","video","text"],d=0;d<c.length;++d){var e=c[d];a.b.a.hasOwnProperty(e)&&b.push(a.b.get(e)[0])}for(var f=We(a,b),d=0;d<c.length;++d)if(e=c[d],a.b.a.hasOwnProperty(e)&&!f[e])return a=Error("Unable to select an initial "+e+" stream: all "+e+" streams have been restricted (by the application or by the key system)."),a.type="stream",Promise.reject(a);b=eb(f).map(function(a){return a.segmentIndexSource.create()});return Promise.all(b).then(G(a,function(a){if(!a.every(function(a){return a.length()}))return a=
Error("Some streams are not available."),a.type="stream",Promise.reject(a);a=Xe(this,a);if(!a)return a=Error("Some streams are not available."),a.type="stream",Promise.reject(a);if(!Ye(this,f))return a=Error("Failed to create Stream objects."),a.type="stream",Promise.reject(a);this.v.start();Ze(this,f,a);return Promise.resolve()})).catch(G(a,function(a){if("aborted"!=a.type)return Object.keys(this.c),this.a.a?(u()<this.a.g?(a=Math.max(this.a.g-Date.now()/1E3,3),this.M=window.setTimeout(this.Qa.bind(this,
!0),1E3*a)):Te(this,0),Promise.resolve()):Promise.reject(a)}))}
function We(a,b){for(var c={},d=0;d<b.length;++d){var e=b[d],f=null;if("video"==e.contentType){var g=a.v.getInitialVideoTrackId();if(null==g)continue;f=e.streamInfos.filter(function(a){return a.A==g});if(0==f.length)continue;f=f[0]}else if("audio"==e.contentType){f=e.streamInfos.filter(function(a){return a.I&&a.F});if(0==f.length)continue;f=e.streamInfos[Math.floor(f.length/2)]}else 0<e.streamInfos.length&&(f=e.streamInfos[0]);c[e.contentType]=f}return c}
function Ye(a,b){var c={},d;for(d in b){var e=b[d],e="text"==d?new Wd(a,a.video):$e(a,e);if(!e)return eb(c).forEach(function(a){a.destroy()}),!1;c[d]=e}a.c=c;return!0}function $e(a,b){var c=new Nd(a,a.video,a.f,Gd(b),a.Z);c.C(a.s);return c}
function Ze(a,b,c){a.Ga=a.video.playbackRate;a.video.playbackRate=0;af(a,c);var d;a.P&&a.P<=c.end&&a.P>=c.start?d=a.P:a.a.a?(d=c.end,a.Ca=!0):d=c.start;C(a.h,a.video,"seeking",a.ob.bind(a));a.video.currentTime!=d&&(a.video.currentTime=d,a.m=d);bf(a,c.start,c.end);c=[];for(var e in a.c){d=a.c[e];c.push(d.Wa(a.W));C(a.h,d,"ended",a.pb.bind(a));var f=b[e];ie(a.G,f);d.ia(f,!1)}Promise.all(c).then(a.ab.bind(a)).catch(G(a,function(a){"destroy"!=a.type&&(a=x(a),this.dispatchEvent(a))}));Ee(a,a.$)}
l.ab=function(a){ba(a&&a.length==Object.keys(this.c).length);for(var b=Number.POSITIVE_INFINITY,c=Number.NEGATIVE_INFINITY,d=0;d<a.length;++d)var e=a[d],b=Math.min(b,e),c=Math.max(c,e);a=cf(this);for(d=0;d<a.length;++d)a[d].ba(c);df(this,a,c);d=jb(this.b).map(function(a){return a.streamInfos}).reduce(function(a,b){return a.concat(b)},[]).map(function(a){var b=[a.segmentIndexSource.create()];a.H&&b.push(a.H.create());return Promise.all(b)});Promise.all(d).then(G(this,function(a){for(var b=0;b<a.length;++b)a[b][0].ba(c);
this.ka=!0;for(var d in this.i)a=this.i[d],b=this.c[d],ie(this.G,a.Aa),b.ia(a.Aa,a.Ja,a.Ka);this.i={}})).catch(G(this,function(a){"aborted"!=a.type&&(a=x(a),this.dispatchEvent(a))}))};function df(a,b,c){if(b=Xe(a,b))af(a,b),bf(a,b.start,b.end);0!=c&&(c=a.video.currentTime+c,a.video.currentTime=c,a.m=c);a.Ca&&b&&(a.video.currentTime=b.end);a.video.playbackRate=a.Ga;a.a.a&&null!=a.a.c&&Te(a,0);ef(a);a.W.resolve()}
function af(a,b){if(a.a.a)isNaN(a.f.duration)&&(a.f.duration=b.end+2592E3);else if(isNaN(a.f.duration)||b.end>a.f.duration){a.f.duration=b.end;for(var c=0;c<a.f.sourceBuffers.length;++c)a.f.sourceBuffers[c].appendWindowEnd=b.end}}l.rb=function(){this.O=null;ef(this);var a=Xe(this,cf(this));a&&(this.a.a&&this.Da!=a.u&&(this.Da=a.u,null!=this.j&&(window.clearTimeout(this.j),this.j=null)),bf(this,a.start,a.end),this.video.paused||ff(this,this.video.currentTime,a.start,a.end))};
function bf(a,b,c){b=v({type:"seekrangechanged",bubbles:!0,start:b,end:c});a.dispatchEvent(b)}l.ob=function(){var a=this.video.currentTime;if(null!=this.m){if(a>=this.m-.01&&a<=this.m+.01){this.m=null;return}this.m=null}var b=Xe(this,cf(this));if(b){var c=b.end;(b=ff(this,a,b.start,c))||(a<=c+.01?b=!1:(this.video.currentTime=c,b=!0));if(!b)for(var d in this.c)this.c[d].Sa()}};
function ff(a,b,c,d){if(b>=c-.01)return!1;b=0;if(a.a.a){b=.5;for(var e in a.c)if(!a.c[e].Ta(c+b)){b=a.a.b;break}}a.video.currentTime=Math.min(c+b,d);return!0}l.pb=function(){if(!this.a.a){for(var a in this.c)if(!this.c[a].ua())return;this.Ma()}};l.cb=function(){eb(this.c).every(function(a){return a.ua()})&&(this.j=window.setTimeout(this.Ma.bind(this),1E3*this.Ea))};l.bb=function(){null!=this.j&&(window.clearTimeout(this.j),this.j=null)};
l.yb=function(){var a=this.G,b=this.Z.getBandwidth();a.estimatedBandwidth=b;a.bandwidthHistory.push(new ke(b))};l.Ma=function(){this.j=null;this.f.endOfStream()};function cf(a){return eb(a.c).map(function(a){return a.Na()}).filter(function(a){return null!=a})}
function Xe(a,b){for(var c=0,d=Number.POSITIVE_INFINITY,e=Number.POSITIVE_INFINITY,f=0;f<b.length;++f){var g=b[f].sa(),c=Math.max(c,g.start);null!=g.end&&(d=Math.min(d,g.end));b[f].length()&&(e=Math.min(e,b[f].u().endTime))}if(d==Number.POSITIVE_INFINITY)if(d=a.a.periodInfos[0],d.a)d=(d.start||0)+d.a;else return null;a.a.a&&(d=Math.max(d-a.a.b,c));return c>d?null:{start:c,end:d,u:e}}function ef(a){a.a.a&&(a.O=window.setTimeout(a.rb.bind(a),1E3))}function Pe(a){for(var b in a.c)a.c[b].C(a.s)};function Z(a,b,c,d){c||(c=new ob);d||(d=new X);Y.call(this,null,c,d);this.Fa=a;this.V=null;this.X=b;this.da=[];this.la=[];this.ma=[];this.D=null}p(Z,Y);n("shaka.player.DashVideoSource",Z);Z.prototype.Ya=function(){return this.Fa};Z.prototype.getUrl=Z.prototype.Ya;Z.prototype.Xa=function(){return this.a};Z.prototype.getManifestInfo=Z.prototype.Xa;Z.prototype.Za=function(a,b,c){this.da.push(a);this.la.push(b||"");this.ma.push(c||"")};Z.prototype.addExternalCaptions=Z.prototype.Za;
Z.prototype.$a=function(a){this.D=a};Z.prototype.setNetworkCallback=Z.prototype.$a;Z.prototype.destroy=function(){this.V=this.D=this.X=null;Y.prototype.destroy.call(this)};
Z.prototype.za=function(){var a=new H(this.D,[new I(this.Fa)]);return md(new ld(a,this.ea)).then(G(this,function(a){this.V=a;for(var c=0;c<this.da.length;c++){var d=a,e=this.da[c],f=this.la[c],g=this.ma[c];if(0!==d.a.length){var h=new Cc;h.contentType="text";h.lang=f||"en";h.c=!0;f=new Fc;f.bandwidth=0;f.f=g||"text/vtt";f.o=[new I(e)];h.a.push(f);d.a[0].b.push(h);Yc(d.a[0])}}this.a=Yd(new Xd(this.X),a,this.D);return Y.prototype.za.call(this)}))};
Z.prototype.Pa=function(a){return md(new ld(a,this.ea)).then(G(this,function(a){this.V=a;a=Yd(new Xd(this.X),a,this.D);return Promise.resolve(a)}))};Z.prototype.Oa=function(){var a=Yd(new Xd(this.X),this.V,this.D);return Promise.resolve(a)};}.bind(g,this))();
if (typeof(module)!="undefined"&&module.exports)module.exports=g.shaka;
else if (typeof(define)!="undefined" && define.amd)define(function(){return g.shaka});
else this.shaka=g.shaka;
})();

//# sourceMappingURL=shaka-player.live.debug.map
